name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
  encryptionKey:
    required: true
    description: Gradle cache encryption key
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
      id: setup-gradle-jdk
      with:
        distribution: temurin
        java-version: 21
        check-latest: true
    - uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4
      with:
        cache-encryption-key: ${{ inputs.encryptionKey }}
    - shell: bash
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      run: |
        ./gradlew \
        -Porg.gradle.java.installations.auto-download=false \
        -Pjunit.develocity.predictiveTestSelection.enabled=true \
        -Pjunit.develocity.predictiveTestSelection.selectRemainingTests=${{ github.event_name != 'pull_request' }} \
        "-Dscan.value.GitHub job=${{ github.job }}" \
        --refresh-dependencies \
        javaToolchains \
        ${{ inputs.arguments }}
