before_install:
  - sdk update
  - sdk install java 24-open
  - sdk use java 24-open
install:
  - ./gradlew --show-version -Pversion=$VERSION -Ppublishing.signArtifacts=false javaToolchains publishToMavenLocal
