[[overview]]
== Overview

The goal of this document is to provide comprehensive reference documentation for
programmers writing tests, extension authors, and engine authors as well as build tool
and IDE vendors.

ifdef::linkToPdf[]
ifdef::backend-html5[]
This document is also available as a link:index.pdf[PDF download].
endif::backend-html5[]
endif::linkToPdf[]

[TIP]
.Translations
====
This document is also available in http://sjyuan.cc/junit5/user-guide-cn[Simplified Chinese]
and https://udzuki.jp/public/junit5-user-guide-ja[Japanese].
====

[[overview-what-is-junit-5]]
=== What is JUnit 5?

Unlike previous versions of JUnit, JUnit 5 is composed of several different modules from
three different sub-projects.

**JUnit 5 = _JUnit Platform_ + _JUnit Jupiter_ + _JUnit Vintage_**

The **JUnit Platform** serves as a foundation for <<launcher-api,launching testing
frameworks>> on the JVM. It also defines the `{TestEngine}` API for developing a testing
framework that runs on the platform. Furthermore, the platform provides a
<<running-tests-console-launcher,Console Launcher>> to launch the platform from the
command line and a <<running-tests-junit-platform-runner,JUnit 4 based Runner>> for
running any `TestEngine` on the platform in a JUnit 4 based environment. First-class
support for the JUnit Platform also exists in popular IDEs (see
<<running-tests-ide-intellij-idea>> and <<running-tests-ide-eclipse>>) and build tools
(see <<running-tests-build-gradle>>, <<running-tests-build-maven>>, and
<<running-tests-build-ant>>).

**JUnit Jupiter** is the combination of the new <<writing-tests,programming model>> and
<<extensions,extension model>> for writing tests and extensions in JUnit 5. The Jupiter
sub-project provides a `TestEngine` for running Jupiter based tests on the platform.

**JUnit Vintage** provides a `TestEngine` for running JUnit 3 and JUnit 4 based tests on
the platform.

[[overview-java-versions]]
=== Supported Java Versions

JUnit 5 requires Java 8 (or higher) at runtime. However, you can still test code that
has been compiled with previous versions of the JDK.

[[overview-getting-help]]
=== Getting Help

Ask JUnit 5 related questions on {StackOverflow} or chat with us on {Gitter}.

[[overview-getting-started]]
=== Getting Started

To find out what artifacts are available for download and inclusion in your project,
refer to <<dependency-metadata>> for details on the available artifacts and their
versions.

NOTE: Artifacts for final releases and milestones are deployed to {Maven_Central}, and
snapshot artifacts are deployed to Sonatype's {snapshot-repo}[snapshots repository] under
{snapshot-repo}/org/junit/[/org/junit].

To find out what features are available and how to use them, read the corresponding
sections of this User Guide, organized by topic.

To see complete, working examples of projects that you can copy and experiment with, the
{junit5-samples-repo}[`junit5-samples`] repository is a good place to start. The
`junit5-samples` repository hosts a collection of sample projects based on JUnit Jupiter
and JUnit Vintage. You'll find the respective build scripts (e.g., `build.gradle`,
`pom.xml`, etc.) in the projects below.

* For Gradle and Java, check out the `{junit5-jupiter-starter-gradle}` project.
* For Gradle and Kotlin, check out the `{junit5-jupiter-starter-gradle-kotlin}` project.
* For Gradle and Groovy, check out the `{junit5-jupiter-starter-gradle-groovy}` project.
* For Maven, check out the `{junit5-jupiter-starter-maven}` project.
* For Ant, check out the `{junit5-jupiter-starter-ant}` project.
