name: Prepare Maven Central user token
description: Compute the Maven Central user token from username and password
inputs:
  username:
    required: true
    description: Maven Central username
  password:
    required: true
    description: Maven Central password
runs:
  using: "composite"
  steps:
    - shell: bash
      run: | # zizmor: ignore[github-env]
        USER_TOKEN=$(printf "${USERNAME}:${PASSWORD}" | base64)
        echo "::add-mask::$USER_TOKEN"
        echo "MAVEN_CENTRAL_USER_TOKEN=$USER_TOKEN" >> $GITHUB_ENV
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}