[[release-notes-5.1.0]]
== 5.1.0

*Date of Release:* February 18, 2018

*Scope:*

* Discovering tests in Java 9 modules
* Improved Kotlin support
* <<../user-guide/index.adoc#extensions-registration-programmatic, Programmatic
extension registration>> via `{RegisterExtension}`
* <<../user-guide/index.adoc#running-tests-tag-expressions, Tag expression language>> for
  filtering tests to be executed
* Annotation-based <<../user-guide/index.adoc#writing-tests-conditional-execution,
  conditional test execution>> with support for environment variables, system properties,
  operating systems, JRE versions, and dynamic scripts
* Various improvements for writing
  <<../user-guide/index.adoc#writing-tests-parameterized-tests, parameterized tests>>
* Refinements to the `{ExtensionContext}` API
* Support for re-running individual dynamic tests, parameterized tests, and test template
  invocations within an IDE

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/14?closed=1+[5.1 M1],
link:{junit5-repo}+/milestone/18?closed=1+[5.1 M2],
link:{junit5-repo}+/milestone/19?closed=1+[5.1 RC1], and
link:{junit5-repo}+/milestone/20?closed=1+[5.1 GA] milestone pages in the JUnit repository
on GitHub. This section describes all _changes_ from version 5.0.3 to 5.1.0.

[[release-notes-5.1.0-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Test methods selected by _fully qualified method name_ via
  `DiscoverySelectors.selectMethod(String)`, via the `method` or `methods` element of the
  `selectors` configuration for the `junitPlatform` Gradle plugin, or via the
  `-select-method` or `-m` command-line options for the `ConsoleLauncher` can now contain
  special characters -- for example, for JVM languages such as Kotlin and Groovy.

==== New Features and Improvements

===== Support for Java 9 Modules

* New `ModuleSelector` discovery selector for scanning Java 9 modules for test classes.
  - This is an alternative to the existing classpath scanning support.
* New console launcher option `--select-module <name>` or `-o <name>` for selecting Java
  9 modules for test discovery.
  - This is an alternative to the existing classpath scanning support.
* New console launcher option `--scan-modules` for scanning all resolved Java 9 modules
  available on the boot layer configuration for test discovery.
  - This is an alternative to the existing classpath scanning support.
* When running on Java 9 or higher the `default` implementations of `getVersion()` and
  `getArtifactId()` in the `TestEngine` interface query the _Java Platform Module System_
  for this information.

===== Miscellaneous

* Tests can now be included or excluded based on their tags using a
  <<../user-guide/index.adoc#running-tests-tag-expressions, tag expression language>> when
  executed using the `Launcher`, `ConsoleLauncher`, Gradle plugin, or Maven Surefire
  provider.
* New `@SuiteDisplayName` annotation in the `junit-platform-suite-api` module for
  declaring a custom _display name_ for a test suite.
  - Supported by the `JUnitPlatform` runner for JUnit 4 in the `junit-platform-runner`
    module.
* The summary table of a console launcher run now contains the initial ten stack trace
  lines to better describe the location of the failure.
* Class loading errors that occur during classpath scanning are now logged at `DEBUG`
  level (i.e., the `FINE` log level in `java.util.logging`) instead of as warnings.


[[release-notes-5.1.0-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Test classes selected via one of the `selectClass()` variants in `DiscoverySelectors`,
  via the `aClass` or `classes` element of the `selectors` configuration for the
  `junitPlatform` Gradle plugin, or via the `-select-class` or `-c` command-line options
  for the `ConsoleLauncher` are no longer allowed to be `private`. This aligns with the
  behavior for test classes discovered via package, class path, and module path scanning.
* Null elements specified in the last column after the first row via `@CsvSource` for
  parameterized tests are now correctly converted to `null` instead of the empty `String`.

==== New Features and Improvements

===== Test Discovery

* The `JupiterTestEngine` supports the new JUnit Platform `ModuleSelector` for selecting
  Java 9 modules.
  - This is an alternative to the existing classpath scanning support.
* Selected dynamic tests and test template invocations can now be executed separately
  without running the complete test factory or test template. This allows to rerun single
  or selected parameterized, repeated or dynamic tests by selecting their unique IDs in
  subsequent discovery requests.

===== Programming Model

* Developers can now register extensions _programmatically_ by annotating fields in test
  classes with `{RegisterExtension}`.
** See <<../user-guide/index.adoc#extensions-registration-programmatic, Programmatic
   Extension Registration>> in the User Guide for details.
* New predefined `@Enabled*` and `@Disabled*` annotations for declarative _conditional
  test execution_. See the following sections of the User Guide for details.
** <<../user-guide/index.adoc#writing-tests-conditional-execution-os, Operating Systems>>
** <<../user-guide/index.adoc#writing-tests-conditional-execution-jre, Java Runtime
   Environment Versions>>
** <<../user-guide/index.adoc#writing-tests-conditional-execution-system-properties,
   System Properties>>
** <<../user-guide/index.adoc#writing-tests-conditional-execution-environment-variables,
   Environment Variables>>
* New `@EnabledIf` and `@DisabledIf` annotations that can be used to control whether the
  annotated test class or test method is _enabled_ or _disabled_ by evaluating a script from a dynamic scripting language such as JavaScript or Groovy.
** See <<../user-guide/index.adoc#writing-tests-conditional-execution-scripts,
   Script-based Conditions>> in the User Guide for details.
* New `assertAll()` variants in `Assertions` that accept collections of executables.

===== Improved Kotlin Support

* New Kotlin friendly assertions added as _top-level functions_ in the
  `org.junit.jupiter.api` package.
  - `assertAll()`: takes `Stream<() \-> Unit>`, `Collection<() \-> Unit>`, or
  `vararg () \-> Unit`.
  - `assertThrows()`: uses Kotlin reified generics.
  - `fail()`: remove need to specify generic type explicitly.
  ** When calling the `Assertions.fail` methods from Kotlin, the compiler required the
     generic return type of `fail` to be declared explicitly when calling it -- for
     example, `fail<Nothing>("Some message")`. These new top-level functions remove this
     requirement by returning
     https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-nothing.html[`Nothing`].

===== Parameterized Tests

* `@CsvFileSource` now supports a `numLinesToSkip` attribute which can be used to skip
  header lines in CSV files.
* `@ValueSource` now additionally supports literal values of type `short`, `byte`,
  `float`, `char`, and `java.lang.Class` for parameterized tests.
* The `value` attribute of `@MethodSource` is no longer mandatory. If no value (or an
  empty String) is supplied as a method name, a method with the same name as the current
  `@ParameterizedTest` method will be used as the factory method by convention.
** See <<../user-guide/index.adoc#writing-tests-parameterized-tests-sources-MethodSource,
   @MethodSource>> in the User Guide for details.
* New support for parameterized tests for implicit conversion from a `String` to an
  argument of any of the following common Java types. See the
  <<../user-guide/index.adoc#writing-tests-parameterized-tests-argument-conversion-implicit-table,
  implicit conversion table>> in the User Guide for examples.
** `java.io.File`
** `java.math.BigDecimal`
** `java.math.BigInteger`
** `java.net.URI`
** `java.net.URL`
** `java.nio.charset.Charset`
** `java.nio.file.Path`
** `java.util.Currency`
** `java.util.Locale`
** `java.util.UUID`
* New fallback mechanism for parameterized tests for implicit conversion from a `String`
  to an argument of a given target type if the target type declares exactly one suitable
  _factory method_ or a _factory constructor_.
** See <<../user-guide/index.adoc#writing-tests-parameterized-tests-argument-conversion-implicit-fallback,
   Fallback String-to-Object Conversion>> in the User Guide for details.

===== Extension Model

* Extensions for JUnit Jupiter can now access JUnit Platform configuration parameters at
  runtime via the new `getConfigurationParameter(String key)` method in the
  `ExtensionContext` API.
* Extensions for JUnit Jupiter can now access the `Lifecycle` of the current test
  instance via the new `getTestInstanceLifecycle()` method in the `ExtensionContext` API.
* New callback interface `CloseableResource` introduced in `ExtensionContext.Store`. A
  `Store` is bound to the lifecycle of its extension context. When the lifecycle of an
  extension context ends, the associated store is closed, and each stored value that is
  an instance of `ExtensionContext.Store.CloseableResource` is notified by an invocation
  of its `close()` method.
* New `getOrComputeIfAbsent(Class)` convenience method in `ExtensionContext.Store` that
  simplifies use cases where an extension wishes to store a single object of a given type
  (keyed by that type) in the `Store` and the object is created using the default
  constructor for that type.
  - For example, code such as
    `store.getOrComputeIfAbsent(X.class, key \-> new X(), X.class)` can now replaced with
    `store.getOrComputeIfAbsent(X.class)`.


[[release-notes-5.1.0-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* When using a tag filter to include/exclude a tag that represents a JUnit 4 category,
  e.g. `"com.example.Integration"`, the Vintage Engine no longer mistakenly executes all
  test methods of test classes that contain at least one included test method, e.g. one
  that is annotated with `@Category(com.example.Integration.class)`, regardless whether
  they belong to the same category.

==== New Features and Improvements

* The `VintageTestEngine` supports the new JUnit Platform `ModuleSelector` for selecting
  Java 9 modules.
  - This is an alternative to the existing classpath scanning support.
* Prior to this release, the Vintage test engine only returned a childless
  `TestDescriptor` for test classes annotated with `@Ignore`. However, build tools like
  Gradle need to show an accurate number of tests, i.e. they want to access and count the
  test methods of a test class regardless whether it's ignored.
  The Jupiter engine already discovers skipped containers, e.g. test classes annotated
  with `@Disabled`, including their children and descendants. The Vintage engine now
  adopts this approach and returns a full subtree of `TestDescriptors` for classes
  annotated with `@Ignore`. During execution, it will only report the `TestDescriptor`
  of the test class as skipped which is consistent with how the Jupiter engine reports
  skipped containers.
