[[release-notes-5.9.0-M1]]
== 5.9.0-M1

*Date of Release:* May 15, 2022

*Scope:*

* XML reports in new https://github.com/ota4j-team/open-test-reporting[Open Test Reporting]
  format
* Configurable cleanup mode for `@TempDir`
* New `TestInstancePreConstructCallback` extension API
* Reusable parameter resolution for custom extension methods via `ExecutableInvoker`
* New `IterationSelector`
* Various improvements to `ConsoleLauncher`

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/58?closed=1+[5.9 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.9.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Fixed handling of global post-discovery filters that apply to `@Suite` classes.
* Since the Turkish language has special characters such as 'ı' and 'İ', the uppercase
  conversion in `DefaultParallelExecutionConfigurationStrategy#getStrategy` previously
  caused all tests to finish with exit code -1. This has been fixed by using the root
  locale instead of the default one.

==== Deprecations and Breaking Changes

* `ConfigurationParameters.size()` has been deprecated in favor of the new `keySet()`
  method.

==== New Features and Improvements

* Support for the https://github.com/ota4j-team/open-test-reporting[Open Test Reporting]
  format which supports all features of the JUnit Platform such as hierarchical test
  structures, display names, tags, etc. Please refer to the
  <<../user-guide/index.adoc#junit-platform-reporting-open-test-reporting, User Guide>>
  for instructions on how to enable such reports in your build.
* `ConfigurationParameters` has a new `keySet()` method which allows you to retrieve all
  configuration parameter keys.
* New `IterationSelector` for selecting a subset of a test's or container's iterations.
* `ParallelExecutionConfiguration` allows configuring the `saturate` predicate of the
  `ForkJoinPool` used for parallel test execution.
* JUnit OSGi bundles now contain `engine` and `launcher` requirements ensuring that at
  resolution time a fully running set of dependencies is calculated, avoiding the need for
  these to be manually specified.
* JUnit Platform Standalone Console JAR now also includes the JUnit Platform Suite Engine.
* New `failIfNoTests` attribute added to `@Suite`. This will fail the suite if no tests
  are discovered.
* The output color for the `ConsoleLauncher` can now be customized. The option
  `--single-color` will apply a built-in monochrome style, while `--color-palette` will
  accept a properties file. See the
  <<../user-guide/index.adoc#running-tests-console-launcher-color-customization,
  User Guide>> for details.
* The default theme for the `ConsoleLauncher` is now determined by the charset reported by
  the system console on Java 17 and later.
* New `--list-engines` option added to the `ConsoleLauncher` which displays all registered
  test engine implementations.
* Configuring included `EngineFilters` that do not match any registered `TestEngine`
  results in an error to avoid misconfiguration – for example, due to typos.


[[release-notes-5.9.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* When cleaning up a `@TempDir`, only one retry attempt will be made to delete directories.
* Since the Turkish language has special characters such as 'ı' and 'İ', the uppercase
  conversion in `DefaultParallelExecutionConfigurationStrategy#getStrategy` previously
  caused all tests to finish with exit code -1. This has been fixed by using the root
  locale instead of the default one.

==== Deprecations and Breaking Changes

* `@TempDir` fields are no longer allowed to be declared as `final`.
  - This improves diagnostics for failures resulting from a user-declared `static final`
    `@TempDir` field by throwing an exception with an informative error message.

==== New Features and Improvements

* `@TempDir` now includes a `cleanup` mode attribute for preventing a temporary directory
  from being deleted after a test. The default cleanup mode can be configured via a
  configuration parameter.
* Support for FreeBSD and OpenBSD operating systems in `@EnabledOnOs` and `@DisabledOnOs`.
* New `MATCH_NONE` mode for `@EnumSource` that selects only those enum constants whose
  names match none of the supplied patterns.
* The `@Order` annotation is now a `STABLE` API.
* New `TestInstancePreConstructCallback` extension API that is called prior to test
  instance construction – symmetric to the existing `TestInstancePreDestroyCallback`
  extension API.
* Extensions can now leverage registered `ParameterResolver` extensions when invoking
  methods and constructors via the new `ExecutableInvoker` API available in the
  `ExtensionContext`.
* A subset of the invocations of parameterized or dynamic tests can now be selected via
  the new `IterationSelector` discovery selector when launching the JUnit Platform.
* `JAVA_19` has been added to the `JRE` enum for use with JRE-based execution conditions.
* `@MethodSource` factory methods can now accept arguments resolved by registered
  `ParameterResolver` extensions.
* Added support for `architectures` parameter in @EnabledOnOs and @DisabledOnOs


[[release-notes-5.9.0-M1-junit-vintage]]
=== JUnit Vintage

No changes.
