[[release-notes-5.3.0]]
== 5.3.0

*Date of Release:* September 3, 2018

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/28?closed=1+[5.3] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.3.0-junit-platform]]
=== JUnit Platform

==== Deprecations and Breaking Changes

* The JUnit Platform `Launcher` now enforces that only `TestEngine` implementations
  published by the JUnit Team may use the `junit-` prefix for their `TestEngine` IDs.
  - See the <<../user-guide/index.adoc#launcher-api-engines-custom-ids, User Guide>> for
    details.


[[release-notes-5.3.0-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* The `junit-jupiter-params` JAR file was missing the required Kotlin metadata for the
  `getAs<Class>(index)` Kotlin extension method. The underlying packaging issue has now
  been solved, and the extension method has been renamed to `get<Class>(index)` as
  originally intended in 5.3.0-M1.
* `TestInstanceFactory` extensions are now properly _inherited_ within `@Nested` test
  class hierarchies.

==== Deprecations and Breaking Changes

* `@Nested` test classes can no longer _override_ `TestInstanceFactory` extensions
  registered on an _enclosing_ class. This aligns with the behavior for
  `TestInstanceFactory` extensions registered within a conventional test class hierarchy.

==== New Features and Improvements

* The dynamic test API has been promoted from _experimental_ to _maintained_ status. This
  affects the `@TestFactory` annotation as well as the `DynamicTest`, `DynamicContainer`,
  and `DynamicNode` types in the `org.junit.jupiter.api` package.
* Implicit argument conversion for parameterized tests can now convert strings such as
  `"java.lang.Integer"`, `"long"`, and `"byte[]"` to `Class` instances.


[[release-notes-5.3.0-junit-vintage]]
=== JUnit Vintage

No changes.
