[[release-notes-5.1.0]]
== 5.1.0

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/20?closed=1+[5.1 GA] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.1.0-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Null elements specified in the last column after the first row via `@CsvSource` for
  parameterized tests are now correctly converted to `null` instead of the empty `String`.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.1.0-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* Due to a regression introduced in 5.1.0-RC1, test classes were reported as started
  to `TestExecutionListeners` after their `@BeforeClass` methods were executed.
  Now, they are reported as early as possible again, in particular before invoking
  `@BeforeClass` methods.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
