[[release-notes-5.2.0-M1]]
== 5.2.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/22?closed=1+[5.2 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.2.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.2.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `assertDoesNotThrow()` methods in `Assertions` which assert that the execution of
  a given code block does _not_ throw any kind of exception.
* Implicit support for _widening primitive conversion_ for an argument supplied to a
  `@ParameterizedTest`.
  - For example, a parameterized test annotated with `@ValueSource(ints = { 1, 2, 3 })`
    can be declared to accept an argument of type `int`, `long`, `float`, or `double`.
* `@MethodSource` now supports `static` factory methods declared in external classes
  referenced by _fully qualified method name_.
* The `ParameterContext` API used in `ParameterResolver` implementations now includes the
  following convenience methods for looking up annotations on parameters. Extension
  authors are strongly encouraged to use these methods instead of those provided in the
  core `java.lang.reflect.Parameter` API due to a bug in `javac` on JDK versions prior to
  JDK 9 which causes lookups for annotations on parameters in inner class constructors to
  fail consistently -- for example, when resolving a parameter for a `@Nested` test class
  constructor.
  - `boolean isAnnotated(Class<? extends Annotation> annotationType)`
  - `Optional<A> findAnnotation(Class<A> annotationType)`
  - `List<A> findRepeatableAnnotations(Class<A> annotationType)`


[[release-notes-5.2.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
