[[release-notes-5.4.0-RC1]]
== 5.4.0-RC1

*Date of Release:* ❓

*Scope:* `@RegisterExtension` ordering, `null` and _empty_ argument sources for
`@ParameterizedTest` methods, new `TestWatcher` extension API, as well as minor
improvements and bug fixes since 5.4.0-M1.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/32?closed=1+[5.4.0-RC1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.4.0-RC1-overall-improvements]]
=== Overall Improvements

* A regression introduced in version 5.4.0-M1 of the `junit-bom` has been fixed:
  `<scope/>` elements are omitted from the `<dependency/>` elements again.


[[release-notes-5.4.0-RC1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* `TestPlan.add(TestIdentifier)` has always been considered _internal_ and is now
  _deprecated_. While calls from third-party code will continue to work for the time
  being, IDEs and build tools should remove any such code as soon as possible.

==== New Features and Improvements

* The `Launcher` API now provides an `execute(TestPlan, TestExecutionListener...)`
  method that allows one to execute a previously discovered `TestPlan`.
* `@RunWith(JUnitPlatform.class)` no longer executes test discovery twice.
* The root cause and suppressed exceptions are now included in the stack trace printed by
  the `ConsoleLauncher`.


[[release-notes-5.4.0-RC1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `@RegisterExtension` fields that are `null` when evaluated are no longer silently
  ignored. Instead, the corresponding test class or test method now fails with an
  informative exception.
* `@ParameterizedTest` once again supports `MessageFormat` patterns for individual
  parameters -- for example, `{0,number,#.##}`.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* Extensions registered _programmatically_ via `@RegisterExtension` may now be registered
  in an explicit order via the `@Order` annotation.
  - See <<../user-guide/index.adoc#extensions-registration-programmatic-order, Extension
    Registration Order>> in the User Guide for details.
* New `@NullSource`, `@EmptySource`, and `@NullAndEmptySource` argument sources that
  provide `null` and _empty_ arguments to `@ParameterizedTest` methods.
  - See <<../user-guide/index.adoc#writing-tests-parameterized-tests-sources-null-and-empty,
    Null and Empty Sources>> in the User Guide for details.
* New `TestWatcher` extension API that allows extensions to process test results by
  defining result-based callbacks invoked after text execution.
  - See <<../user-guide/index.adoc#extensions-test-result-processing, Test Result
    Processing>> in the User Guide for details.


[[release-notes-5.4.0-RC1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* The `VintageTestEngine` now uses the fully qualified class name as the _legacy reporting
  name_ for Vintage test classes instead of the simple class name which caused problems in
  test reports based on legacy reporting names -- for example, reports generated by Maven
  Surefire.
