[[release-notes-5.9.0-M2]]
== 5.9.0-M2

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/61?closed=1+[5.9 M2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.9.0-M2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Absolute path entries are now supported in JUnit's Platform Console Launcher on Windows.
* Attempts to load a `Class` for an invalid class name representing an extremely large
  multidimensional array now fail within a reasonable amount of time.
* Fix concurrency issue in classpath scanning.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New public factory method to instantiate an `ExecutionRequest`.


[[release-notes-5.9.0-M2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* Default `@MethodSource` factory methods can now accept arguments. A _default_ factory
  method is a method declared in the test class with the same name as the
  `@ParameterizedTest` method that is inferred as the factory method when no explicit
  factory method is specified in the `@MethodSource` annotation.

* Thread mode can be set on `@Timeout` annotation. It allows to configure whether the test code
  is executed in the thread of the calling code or in a separate thread, the modes are:
  `INFERRED` (default) which resolves the thread mode configured via the
  property `junit.jupiter.execution.timeout.thread.mode.default`, `SAME_THREAD` that executes
  the test code in the same thread than the calling code, and `SEPARATE_THREAD` which
  executes the test code in a separate thread.


[[release-notes-5.9.0-M2-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
