[[release-notes-5.13.2]]
== 5.13.2

*Date of Release:* June 24, 2025

*Scope:* Bug fixes and enhancements since 5.13.1

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit-framework-repo}+/milestone/98?closed=1+[5.13.2] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.13.2-junit-platform]]
=== JUnit Platform

[[release-notes-5.13.2-junit-platform-bug-fixes]]
==== Bug Fixes

* If Git information is included in the Open Test Reporting XML format (see below), any
  credentials that may be configured as part the `remote.origin.url` setting in Git were
  previously written to the `originUrl` attribute of `<git:repository>` elements. For
  example, when cloning a GitHub repository using a URL like
  `https://username:password@github.com/organization/repository.git`, both username and
  password were included in the XML report. Since a report which includes this information
  may be shared, published, or archived (for example, on a CI server), this was reported
  as a potential security vulnerability (CVE-2025-53103). Any credentials are now replaced
  with `\***` before writing them to the XML report.

[[release-notes-5.13.2-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* Including information about the Git repository (such as the commit hash and branch name)
  in the Open Test Reporting XML format is now an opt-in feature that can be enabled via a
  configuration parameter. Please refer to the
  <<../user-guide/index.adoc#junit-platform-reporting-open-test-reporting, User Guide>>
  for details.


[[release-notes-5.13.2-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.13.2-junit-jupiter-bug-fixes]]
==== Bug Fixes

* Stop reporting discovery issues for cyclic inner class hierarchies not annotated with
  `@Nested`.
* Stop reporting discovery issues for _abstract_ inner classes that contain test methods
  but are not annotated with `@Nested`.
* Stop reporting discovery issues for _abstract_ test methods. Although they will not be
  executed, it is a valid pattern to annotate them with `@Test` for documentation purposes
  and override them in subclasses while re-declaring the `@Test` annotation.

[[release-notes-5.13.2-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* `JAVA_26` has been added to the `JRE` enum for use with JRE-based execution conditions.


[[release-notes-5.13.2-junit-vintage]]
=== JUnit Vintage

No changes.
