[[release-notes-5.6.2]]
== 5.6.2

*Date of Release:* April 10, 2020

*Scope:* Bug fixes since 5.6.1

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/48?closed=1+[5.6.2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.6.2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* `ReflectionSupport.findNestedClasses()` no longer detects inner class cycles for classes
  that do not match the supplied `Predicate`. For example, JUnit Jupiter no longer throws
  an exception if an inner class cycle is detected in a nested class hierarchy whose inner
  classes are not annotated with `@Nested`.


[[release-notes-5.6.2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Test discovery no longer halts with an exception for inner class hierarchies that form a
  cycle if such inner classes are not annotated with `@Nested`.


[[release-notes-5.6.2-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* Generating display names from JUnit 4 `Descriptions` now falls back to `getDisplayName`
  if `getMethodName` returns a blank `String` instead of throwing an exception.
