[[release-notes-5.7.0-M1]]
== 5.7.0-M1

*Date of Release:* April 19, 2020

*Scope:*

* New `@EnabledIf`/`@DisabledIf` annotations for conditional execution based on method
  calls
* New `MethodOrderer` named `DisplayName` that orders methods based on their display names
* New `DisplayNameGenerator` named `Simple` that removes parentheses for empty parameter
  lists
* `assertThrows()` for Kotlin can now be used with suspending functions
* `TestExecutionListener` deactivation via a configuration parameter
* `EngineTestKit` now allows for testing post-discovery filtering and pruning
* Improved interoperability with Spock for the Vintage test engine

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/44?closed=1+[5.7 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.7.0-M1-junit-platform]]
=== JUnit Platform

==== Deprecations and Breaking Changes

* In the `EngineTestKit` API, the `all()`, `containers()`, and `tests()` methods in
  `EngineExecutionResults` that were deprecated in JUnit Platform 1.6.0 have been removed
  in favor of `allEvents()`, `containerEvents()`, and `testEvents()`, respectively.
* The following methods in `EngineTestKit` are now deprecated with replacements:
  - `execute(String, EngineDiscoveryRequest)` → `execute(String, LauncherDiscoveryRequest)`
  - `execute(TestEngine, EngineDiscoveryRequest)` → `execute(TestEngine, LauncherDiscoveryRequest)`
  - `Builder.filters(DiscoveryFilter...)` → `Builder.filters(Filter...)`

==== New Features and Improvements

* The number of containers and tests excluded by post discovery filters based on their tags
  is now logged, along with the exclusion reasons.
* New `junit.platform.execution.listeners.deactivate` configuration parameter that allows
  one to specify a comma-separated list of patterns for deactivating
  `TestExecutionListener` implementations registered via the `ServiceLoader` mechanism.
* The `@Testable` annotation may now be applied _directly_ to fields.
* New `Node.DynamicTestExecutor#execute(TestDescriptor, EngineExecutionListener)` method
  for engines that wish to provide a custom `EngineExecutionListener` and cancel or wait
  for the execution of a submitted test via the returned `Future`.
* New `EngineExecutionListener.NOOP` `EngineExecutionListener` implementation.
* All declared methods in the `EngineExecutionListener` API now have empty `default`
  implementations.
* The `EngineTestKit` now reuses the same test discovery and execution logic as the
  `Launcher`. Thus, it's now possible to test an engine's behavior in the presence of
  post-discovery filters (e.g. tag filters) and with regard to pruning.
* The `EngineTestKit` now supports matching conditions with events loosely, i.e. an
  incomplete match with or without a fixed order.


[[release-notes-5.7.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `@TempDir` is now able to clean up files in read-only directories.
* The Jupiter engine now ignores `MethodSelectors` for methods in non-Jupiter test
  classes instead of failing for missing methods in such cases.

==== New Features and Improvements

* New `@EnabledIf` and `@DisabledIf` annotations can be used to enable or disable a test
  or container based on condition methods.
* New `MethodOrderer` named `DisplayName` that sorts test methods alphanumerically based
  on their display names.
* New `DisplayNameGenerator` named `Simple` (based on `Standard`) that removes trailing
  parentheses for methods with no parameters.
* `assertThrows()` for Kotlin can now be used with suspending functions and other lambda
  contexts that require inlining.
* The `JRE` enum now provides a static `currentVersion()` method that returns the enum
  constant for the currently executing JRE, e.g. for use in custom execution conditions
  and other extensions.
* The `name` attribute of `@ParameterizedTest` is now clearly documented to be a
  `MessageFormat` pattern.
* Synthetic constructors are now ignored when instantiating a test class.
* The Javadoc for the `provideTestTemplateInvocationContexts()` method in
  `TestTemplateInvocationContextProvider` has been aligned with the actual implementation.
  Providers are now officially allowed to return an empty stream, and the error message
  when all provided streams are empty is now more helpful.
* New `getDisplayName()` method in `MethodDescriptor` for use in `MethodOrderer`
  implementations.


[[release-notes-5.7.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* The Vintage engine no longer fails when resolving a `MethodSelector` for methods of test
  classes that cannot be found via reflection. This allows selecting Spock feature methods
  by their source code name even though they have a generated method name in the bytecode.

==== New Features and Improvements

* The internal `JUnit4VersionCheck` class -- which verifies that a supported version of
  JUnit 4 is on the classpath -- now implements a lenient version ID parsing algorithm in
  order to support custom version ID formats such as `4.12.0`, `4.12-patch_1`, etc.
