[[release-notes-5.10.0-M1️]]
== 5.10.0-M1️

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/5.10.0-M1️?closed=1+[5.10.0-M1️] milestone page in the JUnit repository on
GitHub.


[[release-notes-5.10.0-M1️-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Fixed fallback to ForkJoinPools Java 7 constructor on Java 9 and higher

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
* Support for limiting the `max-pool-size` for parallel execution via a configuration parameter

* All utility methods from `ReflectionSupport` now have counterparts returning `Stream`
  instead of `List`.


[[release-notes-5.10.0-M1️-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* The `fixed` parallel execution strategy now allows the thread pool to be saturated by
  default.

==== New Features and Improvements

* ❓
* New `junit.jupiter.execution.parallel.config.fixed.max-pool-size` configuration
  parameter to set the maximum pool size.
* New `junit.jupiter.execution.parallel.config.fixed.saturate` configuration
  parameter to disable pool saturation.
* New `ArgumentsAccessor.getInvocationIndex()` method that supplies the index of a
  `@ParameterizedTest` invocation.
* `DisplayNameGenerator` methods are now allowed to return `null`, in order to signal
  to fall back to the default display name generator.


[[release-notes-5.10.0-M1️-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
