[[release-notes-5.5.0-RC2]]
== 5.5.0-RC2

*Date of Release:* June 20, 2019

*Scope:* minor improvements and bug fixes since 5.5 RC1

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/41?closed=1+[5.5 RC2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.5.0-RC2-junit-platform]]
=== JUnit Platform

No changes.


[[release-notes-5.5.0-RC2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Extensions registered programmatically using `@RegisterExtension` on fields of test
  classes now work correctly for tests in contained `@Nested` test classes. Previously,
  such extensions were registered multiple times for each test method in @Nested` classes.

==== New Features and Improvements

* Parameterized tests now support implicit conversion from a `String` to the following
  `java.time` types: `Duration`, `Period`, `MonthDay`, `ZoneId`, and `ZoneOffset`.
* The `JRE` enum now supports Java 14.
* A new `getOrDefault()` convenience method has been added to `ExtensionContext.Store`.


[[release-notes-5.5.0-RC2-junit-vintage]]
=== JUnit Vintage

No changes.
