[[release-notes-5.1.0-M2]]
== 5.1.0-M2

*Date of Release:* ❓

*Scope:* Minor bug fixes and various enhancements

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/18?closed=1+[5.1 M2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-M2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Summary table is no longer printed via the `ConsoleLauncher` and Gradle plugin when
  details mode `NONE` is selected, unless there are errors.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `SUMMARY` details mode for the `ConsoleLauncher` and Gradle plugin which prints
  the table of success and failure counts at the end of test plan execution. This new
  mode is analogous to the previous behavior of the `NONE` details mode.
* The summary table of a console launcher run now contains the initial ten stack trace
  lines to better describe the location of the failure.
* Non-inherited _composed annotations_ which are meta-annotated with a given `@Inherited`
  annotation are now considered to be implicitly _inherited_ when searching for the given
  meta-annotation within a class hierarchy.

[[release-notes-5.1.0-M2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* The current module layer is now used when scanning for test classes within modules. The
  current module layer is the one that the class loader for the `ModuleUtils` class
  returns. If the current layer cannot be obtained, the algorithm falls back to the boot
  layer.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* Due to a change in the JUnit Platform's `AnnotationUtils` class, non-inherited
  _composed annotations_ which are meta-annotated with a given `@Inherited` annotation
  are now considered to be implicitly _inherited_ when searching for the given
  meta-annotation within a class hierarchy.
** For example, an `@Inherited` annotation such as `@TestInstance` will now be discovered
   on a custom _composed annotation_ declared on a superclass even if the _composed
   annotation_ is not declared as `@Inherited`.
* New callback interface `CloseableResource` introduced in `ExtensionContext.Store`.
  An extension context store is bound to its extension context lifecycle. When an
  extension context lifecycle ends it closes its associated store. All stored values
  that are instances of `ExtensionContext.Store.CloseableResource` are notified by
  invoking their `close()` method.

[[release-notes-5.1.0-M2-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
