[[release-notes-5.10.0-RC1]]
== 5.10.0-RC1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/69?closed=1+[5.10.0-RC1] milestone page in the
JUnit repository on GitHub.


[[release-notes-5.10.0-RC1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* The `getMethodParameterTypes()` methods in `MethodSelector` and `NestedMethodSelector`
  have been deprecated and replaced by `getParameterTypeNames()` for greater clarity.
* Methods in `DiscoverySelectors` that accept a `ClassLoader` now declare the
  `ClassLoader` as the first parameter. This is only a breaking change for code that
  relies on the new methods introduced in JUnit Platform 1.10 M1.

==== New Features and Improvements

* New `@SelectMethod` selector support in the `@Suite` test engine.
* Classes may now be selected by fully-qualified name via the `names` attribute in
  `@SelectClasses`.
* New `selectMethod()` and `selectNestedMethod()` variants in `DiscoverySelectors` that
  accept a `Class<?>...` argument of parameter types as a type-safe alternative to
  providing the names of parameter types as a comma-delimited string.
* Stack trace pruning has been revised and now only removes calls from the `org.junit`,
  `jdk.internal.reflect`, and `sun.reflect` packages. Please refer to the
  <<../user-guide/index.adoc#stacktrace-pruning, User Guide>> for details.
* New `getAncestors()` method in `TestDescriptor`.

[[release-notes-5.10.0-RC1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* `@TempDir` can now be used as a meta-annotation in order to create custom _composed
  annotations_. See the `@JimfsTempDir` example in the
  <<../user-guide/index.adoc#writing-tests-built-in-extensions-TempDirectory, User Guide>>
  for details.
* Lifecycle and thread-safety semantics are now documented for the `TempDirFactory` SPI.
* New `reason` attribute in `@Execution` which can be used to document the reason for
  using the selected execution mode.
* The <<../user-guide/index.adoc#extensions-RandomNumberExtension, User Guide>> now
  includes an example implementation of the `RandomNumberExtension` in order to improve
  the documentation for extension registration via `@ExtendWith` on fields.
* The scope of applicability for `TestWatcher` implementations is now more extensively
  documented in the User Guide and Javadoc.


[[release-notes-5.10.0-RC1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements
* New `assertInstanceOf` methods added for Kotlin following up with similar Java `assertInstanceOf`
methods introduced in `5.8.0` version.
