[[release-notes-5.11.3]]
== 5.11.3

*Date of Release:* October 21, 2024

*Scope:* Bug fixes and enhancements since 5.11.2

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/84?closed=1+[5.11.3] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.11.3-junit-platform]]
=== JUnit Platform

[[release-notes-5.11.3-junit-platform-bug-fixes]]
==== Bug Fixes

* Fixed a regression in method search algorithms introduced in 5.11.0 when classes reside
  in the default package and using a Java 8 runtime.


[[release-notes-5.11.3-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.11.3-junit-jupiter-bug-fixes]]
==== Bug Fixes

* Extensions can once again be registered via multiple `@ExtendWith` meta-annotations on
  the same composed annotation on a field within a test class.
* `@ExtendWith` annotations can now also be repeated when used directly on fields and
  parameters.
* All `@...Source` annotations of parameterized tests can now also be repeated when used
  as meta annotations.


[[release-notes-5.11.3-junit-vintage]]
=== JUnit Vintage

No changes.
