[[release-notes-5.1.0-M2]]
== 5.1.0-M2

*Date of Release:* ❓

*Scope:* Minor bug fixes and various enhancements

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/18?closed=1+[5.1 M2] milestone page in the JUnit repository
on GitHub.

[[release-notes-5.1.0-M2-overall-improvements]]
=== Overall Improvements

* In 5.0.1, all artifacts were changed to have an _optional_ instead of a mandatory
  dependency on the _@API Guardian_ JAR in their published Maven POMs. However, although
  the Java compiler should ignore missing annotation types, a lot of users have reported
  that compiling tests without having the _@API Guardian_ JAR on the classpath results in
  warnings emitted by `javac` that look like this:
+
----
warning: unknown enum constant Status.STABLE
reason: class file for org.apiguardian.api.API$Status not found
----
+
To avoid confusion, the JUnit team has decided to make the dependency to the
_@API Guardian_ JAR _mandatory_ again.

[[release-notes-5.1.0-M2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Summary table is no longer printed via the `ConsoleLauncher` and Gradle plugin when
  details mode `NONE` is selected, unless there are errors.
* The current module layer is now used when scanning for test classes within modules. The
  current module layer is the one that the class loader for the `ModuleUtils` class
  returns. If the current layer cannot be obtained, the algorithm falls back to the boot
  layer.
* The XML report produced by the `ConsoleLauncher` is no longer invalid when the exception
  message of a failed test contains the XML CDATA end marker `]]>`.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `SUMMARY` details mode for the `ConsoleLauncher` and Gradle plugin which prints
  the table of success and failure counts at the end of test plan execution. This new
  mode is analogous to the previous behavior of the `NONE` details mode.
* The summary table of a console launcher run now contains the initial ten stack trace
  lines to better describe the location of the failure.
* Non-inherited _composed annotations_ which are meta-annotated with a given `@Inherited`
  annotation are now considered to be implicitly _inherited_ when searching for the given
  meta-annotation within a class hierarchy.
* New support for a tag expression language in `include-tag` and `exclude-tag`.

[[release-notes-5.1.0-M2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New implicit conversions for parameters of type `java.io.File`, `java.math.BigDecimal`,
  `java.math.BigInteger`, `java.net.URI`, `java.net.URL`, `java.util.Currency`,
  `java.util.Locale`, `java.util.UUID` and `java.nio.file.Path` in parameterized tests.
* Due to a change in the JUnit Platform's `AnnotationUtils` class, non-inherited
  _composed annotations_ which are meta-annotated with a given `@Inherited` annotation
  are now considered to be implicitly _inherited_ when searching for the given
  meta-annotation within a class hierarchy.
** For example, an `@Inherited` annotation such as `@TestInstance` will now be discovered
   on a custom _composed annotation_ declared on a superclass even if the _composed
   annotation_ is not declared as `@Inherited`.
* Extensions for JUnit Jupiter can now access JUnit Platform configuration parameters at
  runtime via the new `getConfigurationParameter(String key)` method in the
  `ExtensionContext` API.
* New callback interface `CloseableResource` introduced in `ExtensionContext.Store`. A
  `Store` is bound to the lifecycle of its extension context. When the lifecycle of an
  extension context ends, the associated store is closed, and each stored value that is
  an instance of `ExtensionContext.Store.CloseableResource` is notified by an invocation
  of its `close()` method.


[[release-notes-5.1.0-M2-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
