[[release-notes-5.10.0-RC1]]
== 5.10.0-RC1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/69?closed=1+[5.10.0-RC1] milestone page in the
JUnit repository on GitHub.


[[release-notes-5.10.0-RC1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* The `getMethodParameterTypes()` methods in `MethodSelector` and `NestedMethodSelector`
  have been deprecated and replaced by `getParameterTypeNames()` for greater clarity.
* Methods in `DiscoverySelectors` that accept a `ClassLoader` now declare the
  `ClassLoader` as the first parameter. This is only a breaking change for code that
  relies on the new methods introduced in JUnit Platform 1.10 M1.

==== New Features and Improvements

* New `@SelectMethod` selector support in the `@Suite` test engine.
* Allow selecting classes by name via new the `names` attribute in `@SelectClasses`.
*Adding a reason for using the selected execution mode.



[[release-notes-5.10.0-RC1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* `@TempDir` can now be used as a meta-annotation in order to create custom _composed
  annotations_. See the `@JimfsTempDir` example in the
  <<../user-guide/index.adoc#writing-tests-built-in-extensions-TempDirectory, User Guide>>
  for details.
* Lifecycle and thread-safety semantics are now documented for the `TempDirFactory` SPI.


[[release-notes-5.10.0-RC1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
