[[release-notes-5.5.0-RC1]]
== 5.5.0-RC1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/37?closed=1+[5.5 RC1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.5.0-RC1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* A custom `ClassLoader` created for additional `--class-path` entries passed to the
  `ConsoleLauncher` will now be closed after usage to gracefully free file handles.

==== Deprecations and Breaking Changes

* The internal `PreconditionViolationException` class in concealed package
  `org.junit.platform.commons.util` is now deprecated and has been replaced by an
  exception class with the same name in exported package `org.junit.platform.commons`.

==== New Features and Improvements

* `AnnotationSupport.findRepeatableAnnotations()` now finds repeatable annotations used as
  meta-annotations on other repeatable annotations.
* New `AnnotationSupport.findRepeatableAnnotations()` variant that accepts a
  `java.util.Optional<? extends AnnotatedElement>` argument.
* Exceptions thrown by `TestExecutionListeners` no longer cause test execution to abort.
  Instead, they will be logged as warnings now.
* New `MethodSource.from()` variant that accepts `String, String, Class<?>...` as
  arguments.


[[release-notes-5.5.0-RC1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Execution of dynamic tests registered via a `@TestFactory` method no longer results in
  an `OutOfMemoryError` if the executables in the dynamic tests retain references to
  objects consuming large amounts of memory. Technically speaking, JUnit Jupiter no longer
  retains references to instances of `DynamicTest` after they have been executed.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New overloaded variants of `Assertions.assertLinesMatch(...)` that accept a `String` or
  a `Supplier<String>` for a custom failure message.
* Failure messages for `Assertions.assertLinesMatch(...)` now emit each expected and
  actual line in a dedicated line.
* New Kotlin friendly `assertDoesNotThrow`, `assertTimeout`, and `assertTimeoutPreemptively`
  assertions have been added as top-level functions in the `org.junit.jupiter.api` package.
* Display names for test methods generated by the `ReplaceUnderscores`
  `DisplayNameGenerator` no longer include empty parentheses for test methods that do not
  declare any parameters.
* `MethodOrderer.Random` now generates a default random seed only once and prints it to
  the log in order to allow reproducible builds.
* Methods ordered with `MethodOrderer.Random` now execute using the `SAME_THREAD`
  concurrency mode instead of the `CONCURRENT` mode when no custom seed is provided.
* New `emptyValue` attribute in `@CsvFileSource` and `@CsvSource`.
* All methods in the `TestWatcher` API are now interface `default` methods with empty
  implementations.
* New `InvocationInterceptor` extension API (see
  <<../user-guide/index.adoc#extensions-intercepting-invocations, User Guide>> for
  details).
* New `junit.jupiter.displayname.generator.default` configuration parameter to set the
  default `DisplayNameGenerator` that will be used unless `@DisplayName` or
  `@DisplayNameGeneration` is present.


[[release-notes-5.5.0-RC1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
