[[release-notes-5.0.3]]
== 5.0.3

*Date of Release:* January 15, 2018

*Scope:* Bug fixes and small improvements for `ConsoleLauncher`, Gradle plugin, and Maven
Surefire provider

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/21?closed=1+[5.0.3] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.3-overall-improvements]]
=== Overall Improvements

* In 5.0.1, all artifacts were changed to have an _optional_ instead of a mandatory
  dependency on the _@API Guardian_ JAR in their published Maven POMs. However, although
  the Java compiler should ignore missing annotation types, a lot of users have reported
  that compiling tests without having the _@API Guardian_ JAR on the classpath results in
  warnings emitted by `javac` that look like this:
+
----
warning: unknown enum constant Status.STABLE
reason: class file for org.apiguardian.api.API$Status not found
----
+
To avoid confusion, the JUnit team has decided to make the dependency to the
_@API Guardian_ JAR _mandatory_ again.


[[release-notes-5.0.3-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Summary table is no longer printed via the `ConsoleLauncher` and Gradle plugin when
  details mode `NONE` is selected, unless there are errors.
* The XML report produced by the `ConsoleLauncher` and Gradle plugin is no longer invalid
  when the exception message of a failed test contains the XML CDATA end marker `]]>`.
* The `ConsoleLauncher`, the Gradle plugin, and the Maven Surefire provider now attempt to
  write a valid class name into the `classname` attribute of `<testcase/>` elements in the
  XML reports. In addition, the `name` attribute of dynamic tests and test template
  invocations (such as repeated and parameterized tests) is now suffixed with the index of
  the invocation so they are distinguishable by reporting tools.
* The Maven Surefire provider now includes the method parameter types when writing the
  `name` attribute of `<testcase/>` elements into XML reports. However, due to a
  limitation of Maven Surefire, instead of `methodName(Type)` they are written as
  `methodName{Type}`.
* Non-inherited _composed annotations_ which are meta-annotated with a given `@Inherited`
  annotation are now considered to be implicitly _inherited_ when searching for the given
  meta-annotation within a class hierarchy.

==== New Features and Improvements

* The JUnit Platform Maven Surefire provider now runs all specified tests in a single
  test run, i.e. all registered `TestExecutionListeners` will receive a single `TestPlan`.
  Previously, a separate `TestPlan` was discovered and executed for each test class.
* New `SUMMARY` details mode for the `ConsoleLauncher` and Gradle plugin which prints
  the table of success and failure counts at the end of test plan execution. This new
  mode is analogous to the previous behavior of the `NONE` details mode.
* The Maven Surefire provider now supports the `test` parameter that tells Surefire to
  only execute a subset of test classes or methods, e.g. by specifying `-Dtest=...` on the
  command line (see the
  http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test[Surefire documentation]
  for details).


[[release-notes-5.0.3-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* The `@Tag` and `@Tags` annotations are now inherited within test class hierarchies.
* Due to a change in the JUnit Platform's `AnnotationUtils` class, non-inherited
  _composed annotations_ which are meta-annotated with a given `@Inherited` annotation
  are now considered to be implicitly _inherited_ when searching for the given
  meta-annotation within a class hierarchy.
** For example, an `@Inherited` annotation such as `@TestInstance` will now be discovered
   on a custom _composed annotation_ declared on a superclass even if the _composed
   annotation_ is not declared as `@Inherited`.


[[release-notes-5.0.3-junit-vintage]]
=== JUnit Vintage

No changes.
