[[release-notes-5.11.0-M1]]
== 5.11.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/68?closed=1+[5.11.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.11.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Allow `junit-platform-launcher` to be used as a Java module when
  `junit.platform.launcher.interceptors.enabled` is set to `true`.
  - See link:https://github.com/junit-team/junit5/issues/3561[issue 3561] for details.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `ConversionSupport` utility in `junit-platform-commons` which exposes the conversion
  logic that was previously private to JUnit Jupiter's `@ParameterizedTest` infrastructure
  -- for use in third-party extensions and test engines.
* Error messages for type mismatches in `NamespacedHierarchicalStore` now include the
  actual type and value in addition to the required type.
* New `NamedExecutable` interface that associates a name, a payload and an Executable.
* New DynamicTests generators in DynamicTest class that takes one Stream/Iterator of NamedExecutables,
  this helps simplify the generation of DynamicTests Stream.


[[release-notes-5.11.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* Change used Kotlin API and language version from 1.3 to 1.6.

==== New Features and Improvements

* New `@AutoClose` annotation that can be applied to fields within tests to automatically
  close the annotated resource after test execution. See the
  <<../user-guide/index.adoc#writing-tests-built-in-extensions-AutoClose, User Guide>> for
  details.


[[release-notes-5.11.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
