[[release-notes-5.10.0-M1]]
== 5.10.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/65?closed=1+[5.10.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.10.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* Building native images with GraalVM now requires configuring the build arg
  `--initialize-at-build-time=org.junit.platform.launcher.core.LauncherConfig`.

==== New Features and Improvements

* All utility methods from `ReflectionSupport` now have counterparts returning `Stream`
  instead of `List`.
* For consistency with Jupiter lifecycle callbacks, listener method pairs for started/
  finished and opened/closed events are now called using "wrap" semantics, i.e. the latter
  methods are called in reverse order compared to the former when multiple listeners are
  registered. This affects the following listener interfaces: `TestExecutionListener`,
  `EngineExecutionListener`, `LauncherDiscoveryListener`, and `LauncherSessionListener`.
* Introduce `LauncherInterceptor` SPI for intercepting the creation of instances of
  `Launcher` and `LauncherSessionlistener` as well as calls for `discover` and `execute`
  of the former. Please refer to the
  <<../user-guide/index.adoc#launcher-api-launcher-interceptors-custom, User Guide>> for
  details.

[[release-notes-5.10.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Parameter types for _local_ `@MethodSource` factory method names are now validated. For
  example, `@MethodSource("myFactory(example.NonexistentType)")` will now result in an
  exception stating that `example.NonexistentType` cannot be resolved to a valid type.
* The syntax for parameter types in _local_ `@MethodSource` factory method names now
  supports canonical array names -- for example, you may now specify `int[]` as in
  `@MethodSource("myFactory(int[])"` instead of the _binary_ name `[I` as in
  `@MethodSource("myFactory([I)"` (which was already supported) and
  `@MethodSource("myFactory(java.lang.String[])` instead of
  `@MethodSource("myFactory([Ljava.lang.String;)`.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `ArgumentsAccessor.getInvocationIndex()` method that supplies the index of a
  `@ParameterizedTest` invocation.
* `DisplayNameGenerator` methods are now allowed to return `null`, in order to signal
  to fall back to the default display name generator.
* `@EmptySource` now supports additional types, including `Collection` and `Map` subtypes
  with a public no-arg constructor.


[[release-notes-5.10.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
