[[release-notes-5.13.0-M1]]
== 5.13.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/85?closed=1+[5.13.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.13.0-M1-junit-platform]]
=== JUnit Platform

[[release-notes-5.13.0-M1-junit-platform-bug-fixes]]
==== Bug Fixes

* Notify `LauncherDiscoveryListener` implementation registered via `LaucherConfig` or on
  the `Launcher` of `selectorProcessed` events.

[[release-notes-5.13.0-M1-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* New `ConsoleLauncher` options `--redirect-stdout` and `--redirect-stderr` for
  redirecting `stdout` and `stderr` output streams to files.
* Add `TestDescriptor.Visitor.composite(List)` factory method for creating a composite
  visitor that delegates to the given visitors in order.
* Introduce test _discovery_ support in `EngineTestKit` to ease testing for discovery
  issues produced by a `TestEngine`. Please refer to the
  <<../user-guide/index.adoc#testkit-engine, User Guide>> for details.


[[release-notes-5.13.0-M1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.13.0-M1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* If the `autoCloseArguments` attribute in `@ParameterizedTest` is set to `true`, all
  arguments returned by registered `ArgumentsProvider` implementations are now closed even
  if the test method declares fewer parameters.
* `AutoCloseable` arguments returned by an `ArgumentsProvider` are now closed even if they
  are wrapped with `Named`.
* `AutoCloseable` arguments returned by an `ArgumentsProvider` are now closed even if a
  failure happens prior to invoking the parameterized method.

[[release-notes-5.13.0-M1-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* New `@ClassTemplate` annotation and `ClassTemplateInvocationContextProvider` API that
  allow declaring a top-level or `@Nested` test class as a template to be invoked multiple
  times. This may be used, for example, to inject different parameters to be used by all
  tests in the class template or to set up each invocation of the class template
  differently. Please refer to the
  <<../user-guide/index.adoc#writing-tests-class-templates, User Guide>> for details.
* New `BeforeClassTemplateInvocationCallback` and `AfterClassTemplateInvocationCallback`
  extension callback interfaces allow implementing extensions that are invoked before and
  after each invocation of a class template.
* New `@ParameterizedClass` support that builds on `@ClassTemplate` and allows declaring a
  top-level or `@Nested` test class as a parameterized test class to be invoked multiple
  times with different arguments. The same `@...Source` annotations supported with
  `@ParameterizedTest` may be used to provide arguments via constructor or field
  injection. Please refer to the
  <<../user-guide/index.adoc#writing-tests-parameterized-tests, User Guide>> for details.
* New `@ParameterizedClass`-specific
  `@BeforeParameterizedClassInvocation`/`@AfterParameterizedClassInvocation` lifecycle
  methods that are invoked once before/after each invocation of the parameterized class.
* Provide access to the parameters and resolved arguments of a `@ParameterizedTest` or
  `@ParameterizedClass` by storing `ParameterInfo` in the `ExtensionContext.Store` for
  retrieval by other extensions. Please refer to the
  link:../api/org.junit.jupiter.params/org/junit/jupiter/params/support/ParameterInfo.html[Javadoc]
  for details.
* New `@SentenceFragment` annotation which allows one to supply custom text for individual
  sentence fragments when using the `IndicativeSentences` `DisplayNameGenerator`. See the
  updated documentation in the
  <<../user-guide/index.adoc#writing-tests-display-name-generator, User Guide>> for an
  example.
* New `TestTemplateInvocationContext.prepareInvocation(ExtensionContext)` callback method
  which allows extensions to prepare the `ExtensionContext` before the test template
  method is invoked. This may be used, for example, to store entries in the
  `ExtensionContext.Store` to benefit from its cleanup support or for retrieval by other
  extensions.


[[release-notes-5.13.0-M1-junit-vintage]]
=== JUnit Vintage

[[release-notes-5.13.0-M1-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M1-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M1-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
