[[release-notes-5.6.0-M1]]
== 5.6.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/39?closed=1+[5.6 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.6.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* In the `EngineTestKit` API, the `all()`, `containers()`, and `tests()` methods in
  `EngineExecutionResults` have been deprecated in favor of the new `allEvents()`,
  `containerEvents()`, and `testEvents()` methods, respectively. The deprecated methods
  will be removed in JUnit Platform 1.7.0.

==== New Features and Improvements

* New `printFailuresTo(PrintWriter, int)` method in `TestExecutionSummary` that allows one
  to specify the maximum number of lines to print for exception stack traces.


[[release-notes-5.6.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* `@EnabledIf` and `@DisabledIf` have been removed from Jupiter's API. Script-based
  condition APIs and their supporting implementations were deprecated in JUnit Jupiter 5.5
  with the intent to remove them in JUnit Jupiter 5.6. Users must now rely on a
  combination of other built-in conditions or create and use a custom implementation of
  `ExecutionCondition` to evaluate the same conditions.

==== New Features and Improvements

* Support for String delimiters in `@CsvSource` and `@CsvFileSource`.
* Documented support for comments in CSV files loaded via `@CsvFileSource`.
* Auto-detection of enum type from method signature for `@EnumSource`.
* New `TypeBasedParameterResolver<T>` abstract base class that serves as a generic adapter
  for the `ParameterResolver` API and simplifies the implementation of a custom resolver
  that supports parameters of a specific type.


[[release-notes-5.6.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
