[[release-notes-5.5.0-M1]]
== 5.5.0-M1

*Date of Release:* March 19, 2019

*Scope:* Configurable test discovery implementation

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/34?closed=1+[5.5 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.5.0-M1-junit-platform]]
=== JUnit Platform

==== New Features and Improvements

* Configurable test discovery implementation that can be reused by different test engines
  (see Javadoc of the `{junit-platform-engine-support-discovery}` package).
* New `isFinal()` and `isNotFinal()` methods in `ModifierSupport`.


[[release-notes-5.5.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== New Features and Improvements

* Expected and actual values are now supplied for failed `boolean` assertions for enhanced
  IDE and reporting support -- for example, when `assertTrue()` or `assertFalse()` fails.
* `@ValueSource` now additionally supports literal values of type `boolean` for
  parameterized tests.


[[release-notes-5.5.0-M1-junit-vintage]]
=== JUnit Vintage

No changes.
