[[release-notes-5.2.0-M1]]
== 5.2.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/22?closed=1+[5.2 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.2.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The default _include pattern_ for filtering class names now matches test classes whose
  names either start with `Test` or end with `Test` or `Tests`.
  - This pattern is used by the `ConsoleLauncher`, the JUnit Platform Gradle Plugin, and
    the `JUnitPlatform` runner.


[[release-notes-5.2.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `assertDoesNotThrow()` methods in `Assertions` which assert that the execution of
  a given code block does _not_ throw any kind of exception.
* Implicit support for _widening primitive conversion_ for an argument supplied to a
  `@ParameterizedTest`.
  - For example, a parameterized test annotated with `@ValueSource(ints = { 1, 2, 3 })`
    can be declared to accept an argument of type `int`, `long`, `float`, or `double`.
* `@MethodSource` now supports `static` factory methods declared in external classes
  referenced by _fully qualified method name_.
* Support for aggregation of multiple `@ParameterizedTest` arguments into a single
  object.


[[release-notes-5.2.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
