[[release-notes-5.3.0-RC1]]
== 5.3.0-RC1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/27?closed=1+[5.3 RC1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.3.0-RC1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.3.0-RC1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `TestInstanceFactory` extension API that enables custom creation of test class
  instances.
  - See <<../user-guide/index.adoc#extensions-test-instance-factories, Test Instance
    Factories>> in the User Guide for details.
* `ArgumentConverters` and `ArgumentsAggregators` registered using `@ConvertWith` and
  `@AggregateWith`, respectively, are now only instantiated once per `@ParameterizedTest`
  instead of once for each invocation.


[[release-notes-5.3.0-RC1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The `VintageTestEngine` now uses the _simple name_ of a test class as the display
  name instead of the _fully qualified class name_. This aligns with the behavior of the
  `JupiterTestEngine`.
