[[release-notes-5.8.0-M1]]
== 5.8.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/51?closed=1+[5.8 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.8.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* `InvocationInterceptor.interceptDynamicTest(Invocation<Void> , ExtensionContext)` has been deprecated in favor of
  `InvocationInterceptor.interceptDynamicTest(Invocation<Void> , DynamicTestInvocationContext, ExtensionContext)` that
  allows to access the dynamic test executable via `DynamicTestInvocationContext.getExecutable()`.

==== New Features and Improvements

* New `test(Condition<Event>)` and `nestedContainer(Class<?>, Condition<Event>)` methods
  in `EventConditions` that allow you to provide conditions for matching against test and
  nested container events when using the `EngineTestKit`. For example,
  `test(displayName("my test"))` can be used to match against a test whose display name is
  `my test`.


[[release-notes-5.8.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `assertInstanceOf` methods as a replacement for `assertTrue(obj instanceof X)` which
  provide better error messages comparable to those of `assertThrows`.

[[release-notes-5.8.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
