[[release-notes-5.13.0-M3]]
== 5.13.0-M3

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/93?closed=1+[5.13.0-M3] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.13.0-M3-junit-platform]]
=== JUnit Platform

[[release-notes-5.13.0-M3-junit-platform-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M3-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M3-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* Introduce resource management mechanism that allows preparing and sharing state across
  executions or test engines via stores that are scoped to a `LauncherSession` or
  `ExecutionRequest`. The Jupiter API uses these stores as ancestors to the `Store`
  instances accessible via `ExtensionContext` and provides a new method to access them
  directly. Please refer to the User Guide for examples of managing
  <<../user-guide/index.adoc#launcher-api-launcher-session-listeners-tool-example-usage, session-scoped>>
  and
  <<../user-guide/index.adoc#launcher-api-managing-state-across-test-engines, request-scoped>>
  resources.

* CloseableResource is now deprecated and extends `AutoCloseable`. This change is
  intended to improve the usability of the API and to align it with the standard Java
  `AutoCloseable` interface.


[[release-notes-5.13.0-M3-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.13.0-M3-junit-jupiter-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M3-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M3-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Return types of `@TestFactory` methods are now validated during discovery rather than
  during execution. Invalid `@TestFactory` methods are no longer executed but reported as
  discovery issues for consistency with how `@Test` and `@TestTemplate` methods are
  handled.


[[release-notes-5.13.0-M3-junit-vintage]]
=== JUnit Vintage

[[release-notes-5.13.0-M3-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M3-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M3-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
