[[release-notes-5.8.0-M2]]
== 5.8.0-M2

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/55?closed=1+[5.8 M2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.8.0-M2-general-improvements]]
=== General improvements

* The API Guardian dependency is now exported as a compile-only dependency for consuming
  Gradle projects.


[[release-notes-5.8.0-M2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Classes explicitly selected via `@SelectClasses` are now always included in the test
  suite. This applies to `@Suite` classes running via the `SuiteTestEngine` and suite
  classes running via the `JUnitPlatform` `Runner`.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `findAnnotation(Class,Class,SearchOption)` method in `AnnotationSupport` that
  performs the same search algorithm as `findAnnotation(AnnotatedElement,Class)` but also
  searches the enclosing class hierarchy for inner classes if the
  `INCLUDE_ENCLOSING_CLASSES` `SearchOption` is specified. This new method can be used by
  extension authors to find annotations on enclosing classes for JUnit Jupiter `@Nested`
  test classes.
* New `ClassSource.from(URI)` static factory method for creating a `ClassSource` from a
  URI using the `class` scheme and optional query parameters specifying the line number
  and column number. This is analogous to the existing `ClasspathResourceSource.from(URI)`
  factory method.
* New `getConfigurationParameters()` method in the `TestPlan` which allows a
  `TestExecutionListener` to access
  <<../user-guide/index.adoc#running-tests-config-params, configuration parameters>>. See
  <<../user-guide/index.adoc#launcher-api-listeners-config, Configuring an Execution
  Listener>> for details.
* New `UniqueIdTrackingListener` which is a `TestExecutionListener` that tracks the unique
  IDs of all tests that were skipped or executed during the `TestPlan` and generates a
  file containing the unique IDs. The generated file can be used to rerun those tests --
  for example, in order to run the same set of tests executed on the JVM subsequently
  within a GraalVM native image. See the Javadoc for `{UniqueIdTrackingListener}` for
  details.
* Generating Java Flight Recorder events via module `org.junit.platform.jfr` is now also
  supported on Java 8 Update 262 or higher, in addition to Java 11 or later. See
  <<../user-guide/index.adoc#running-tests, Flight Recorder Support>> for details.


[[release-notes-5.8.0-M2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `@DisplayNameGeneration` and `@IndicativeSentencesGeneration` are now only inherited
  from enclosing classes if the current class is a `@Nested` test class.
* The `IndicativeSentences` `DisplayNameGenerator` no longer includes the display name of
  the enclosing class when generating an _indicative sentence_ if the enclosing class is
  not configured to use the `IndicativeSentences` display name generator as well.
* The `TypedArgumentConverter` base class now supports the conversion of a `null` source
  value in parameterized tests.
* The `TypedArgumentConverter` base class now supports conversion to a primitive type if
  the configured target type is a wrapper for the target primitive type, including
  primitive widening support -- for example, from `Integer` to `int` or `long`.
* Exceptions thrown from instances of `CloseableResource` no longer hide test failures but
  are instead reported as suppressed exceptions.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* `@TempDir` can now be used to create multiple temporary directories. Instead of creating
  a single temporary directory per context (i.e. test class or method) every declaration
  of the `@TempDir` annotation on a field or method parameter now results in a separate
  temporary directory. To revert to the old behavior of using a single temporary directory
  for the entire test class or method (depending on which level the annotation is used),
  you can set the `junit.jupiter.tempdir.scope` configuration parameter to `per_context`.
* `@TempDir` cleanup resets readable and executable permissions of the root temporary
  directory and any contained directories instead of failing to delete them.
* `@TempDir` fields may now be private.
* New `named()` static factory method in the `Named` interface that serves as an _alias_
  for `Named.of()`. `named()` is intended to be used via `import static`.
* New `class` URI scheme for dynamic test sources. This allows tests to be located using
  the information available in a `StackTraceElement`.
* New `assertThrowsExactly` method which is a more strict version of `assertThrows`
  that allows you to assert that the thrown exception has the exact specified class.
* New `autoCloseArguments` attribute in `@ParameterizedTest` to close `AutoCloseable`
  arguments at the end of the test. This attribute defaults to true.


[[release-notes-5.8.0-M2-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
