[[release-notes-5.7.0-M1]]
== 5.7.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/44?closed=1+[5.7 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.7.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The number of containers and tests excluded by post discovery filters based on their tags
  is now logged, along with the exclusion reasons.
* New `junit.platform.execution.listeners.deactivate` configuration parameter that allows
  one to specify a comma-separated list of patterns for deactivating
  `TestExecutionListener` implementations registered via the `ServiceLoader` mechanism.
* The `@Testable` annotation may now be applied _directly_ to fields.
* Add `Node.DynamicTestExecutor#execute(TestDescriptor, EngineExecutionListener)` for
  engines that wish to pass a custom `EngineExecutionListener` and cancel or wait for the
  execution of a submitted test via the returned `Future`.
* Add `EngineExecutionListener.NOOP` and change all declared methods to have empty default
  implementations.


[[release-notes-5.7.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* `assertThrows` for Kotlin can now be used with suspending functions and other lambda
  contexts that require inlining.
* Synthetic constructors are now ignored when instantiating a test class.
* The Javadoc for the `provideTestTemplateInvocationContexts()` method in
  `TestTemplateInvocationContextProvider` has been aligned with the actual implementation.
  Providers are now officially allowed to return an empty stream, and the error message
  when all provided streams are empty is now more helpful.
* The `JRE` enum now provides a static `currentVersion()` method that returns the enum
  constant for the currently executing JRE, e.g. for use in custom execution conditions
  and other extensions.
* The `name` attribute of `@ParameterizedTest` is now clearly documented to be a
  `MessageFormat` pattern.
* New `DisplayNameGenerator` named `Simple` (based on `Standard`) that removes trailing
  parentheses for methods with no parameters.
* New `MethodOrderer` named `DisplayName` that sorts test methods alphanumerically based
  on their display names.
* New `getDisplayName()` method in `MethodDescriptor`.


[[release-notes-5.7.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The internal `JUnit4VersionCheck` class -- which verifies that a supported version of
  JUnit 4 is on the classpath -- now implements a lenient version ID parsing algorithm in
  order to support custom version ID formats such as `4.12.0`, `4.12-patch_1`, etc.
