[[release-notes-5.11.4]]
== 5.11.4

*Date of Release:* December 16, 2024

*Scope:* Bug fixes and enhancements since 5.11.3

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/86?closed=1+[5.11.4] milestone page in the
JUnit repository on GitHub.


[[release-notes-5.11.4-junit-platform]]
=== JUnit Platform

[[release-notes-5.11.4-junit-platform-bug-fixes]]
==== Bug Fixes

* Escape whitespace characters (such as line breaks) in XML attribute values (such as
  exception messages) in the legacy XML report generated by the Console Launcher. This
  change ensures the resulting XML files can be processed by downstream tools while
  preserving whitespace characters.
* Enable auto-flushing of output in the `ConsoleLauncher` to fix issues with buffering,
  in particular when using the `--details=testfeed` option.


[[release-notes-5.11.4-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.11.4-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* `JAVA_25` has been added to the `JRE` enum for use with JRE-based execution conditions.


[[release-notes-5.11.4-junit-vintage]]
=== JUnit Vintage

No changes.
