[[release-notes-5.0.1]]
== 5.0.1

*Date of Release:* October 3, 2017

*Scope:* Bug fixes for the 5.0.0 release

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/16?closed=1+[5.0.1] milestone page in the JUnit repository
on GitHub.

[[release-notes-5.0.1-overall-improvements]]
=== Overall Improvements

* All artifacts now have an `optional` instead of a mandatory dependency on the
  _@API Guardian_ JAR in their published Maven POMs.


[[release-notes-5.0.1-junit-platform]]
=== JUnit Platform

No code changes.


[[release-notes-5.0.1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `ExpectedExceptionSupport` from the `junit-jupiter-migrationsupport` module no longer
  swallows exceptions if the test class does not declare a JUnit 4 `ExpectedException`
  rule.
  - Consequently, `@EnableRuleMigrationSupport` and `ExpectedExceptionSupport` may now be
    used without declaring an `ExpectedException` rule.


[[release-notes-5.0.1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* `PackageNameFilters` are now applied to tests selected via a `ClassSelector`,
  `MethodSelector` or `UniqueIdSelector`.
