[[release-notes-5.3.0-RC1]]
== 5.3.0-RC1

*Date of Release:* August 13, 2018

*Scope:* Finishing touches on parallel test execution and output capturing, bug fixes and
miscellaneous usability improvements.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/27?closed=1+[5.3 RC1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.3.0-RC1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* All `DiscoverySelector` implementations (e.g., `PackageSelector`, `ClassSelector`,
  `MethodSelector`, etc.) now implement `equals()` and `hashCode()` for proper behavior
  when stored in collections.
* `ClassSource` has been revised so that `equals()` and `hashCode()` are now properly
  based on the required _class name_ instead of the optional `Class` reference. In
  addition, the non-blank precondition for a class name is now enforced.

==== Deprecations

* The JUnit Platform Surefire Provider (`junit-platform-surefire-provider`) is now
  deprecated in favor of the native support for the JUnit Platform provided by Maven
  Surefire 2.22.0 and later versions.

==== New Features and Improvements

* New `LauncherConfig` and associated _builder_ for configuring the `LauncherFactory`.
  Specifically, auto-registration of test engines and test execution listeners can now be
  disabled, and additional engines and listeners can be registered programmatically.
* New `MethodSource.from(Class, Method)` static factory method for creating a
  `MethodSource` from a specific class and method. This method should be used in favor of
  `MethodSource.from(Method)` when the test method is inherited from a superclass or
  present as an interface `default` method.
* A `ClasspathResourceSource` can now be created from a `URI` via the new `from(URI)`
  static factory method if the `URI` uses the `classpath` scheme.
* If the new experimental feature is enabled, captured output to `System.out` and
  `System.err` is now written to the dedicated `system-out` and `system-err` elements,
  respectively, in the XML report generated by `ConsoleLauncher`.
* The `ConsoleLauncher` now uses the https://github.com/remkop/picocli[picocli] library
  under the hood to parse the command line and generate usage help. Users may now pass
  command line arguments via an argument file (`@-file`) to the console launcher.
  Argument files allow users to work around system limitations on the length of a command
  line when creating a command line with lots of options or with long arguments for
  options. The usage help is now displayed using ANSI colors on supported platforms.


[[release-notes-5.3.0-RC1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* The `MethodSource` for an _inherited_ `@Test` method now correctly references the
  _current_ test class instead of the class or interface in which the `@Test` method is
  _declared_. This allows build tools such as Maven Surefire to properly include
  inherited `@Test` methods when executing a single test class or specific test classes
  based on filters -- for example, via `mvn test -Dtest=SubclassTests`).
* Exceptions thrown in `@After` and `@AfterAll` lifecycle methods now take precedence over
  violated assumptions (i.e. `TestAbortedExceptions`) in test or prior lifecycle methods.

==== New Features and Improvements

* Generation of a detailed failure message for a failed assertion no longer fails if the
  `toString()` implementation of an object supplied to the assertion throws an exception.
  Instead, the object with the broken `toString()` implementation will be referenced via
  a default String representation based on the object's fully qualified class name and
  system hash code, separated by an `@` symbol.
* Although it is _highly discouraged_, it is now possible to extend the `{Assertions}`
  and `{Assumptions}` classes for special use cases.
* New `publishEntry(String)` method in `TestReporter` that makes it easier to publish a
  report entry based solely on a _value_ without requiring that a _key_ be specified
  (as is required by the existing `publishEntry()` variants).
* A custom test source `URI` for a dynamic container or dynamic test will now be
  registered as a `ClasspathResourceSource` if the `URI` uses the `classpath` scheme.
* New `TestInstanceFactory` extension API that enables custom creation of test class
  instances.
  - See <<../user-guide/index.adoc#extensions-test-instance-factories, Test Instance
    Factories>> in the User Guide for details.
* `ArgumentConverters` and `ArgumentsAggregators` registered using `@ConvertWith` and
  `@AggregateWith`, respectively, are now only instantiated once per `@ParameterizedTest`
  instead of once for each invocation.
* Performance improvements for executing parameterized tests, particularly when the method
  declares more than a few parameters.
* New `{displayName}` placeholder for the `name` attribute in `@ParameterizedTest` that
  allows developers to include the display name of the `@ParameterizedTest` method in a
  custom display name for invocations of that parameterized test.
  - This aligns with the existing `{displayName}` placeholder support for `@RepeatedTest`.
* Generation of the display name for a `@ParameterizedTest` no longer fails if the
  `toString()` implementation of an argument for the parameterized test throws an
  exception. Instead, the object with the broken `toString()` implementation will be
  referenced via a default String representation based on the object's fully qualified
  class name and system hash code, separated by an `@` symbol.
* New `getAs<Class>(index)` Kotlin extension method to make `ArgumentsAccessor` friendlier
  to use from Kotlin.
* Tests in classes that use `Lifecycle.PER_CLASS` are now executed in the same thread by
  default when parallel execution is enabled.


[[release-notes-5.3.0-RC1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* The `MethodSource` for an _inherited_ `@Test` method now correctly references the
  _current_ test class instead of the class or interface in which the `@Test` method is
  _declared_. This allows build tools such as Maven Surefire to properly include
  inherited `@Test` methods when executing a single test class or specific test classes
  based on filters -- for example, via `mvn test -Dtest=SubclassTests`).

==== New Features and Improvements

* The `VintageTestEngine` now uses the _simple name_ of a test class as the display
  name instead of the _fully qualified class name_. This aligns with the behavior of the
  `JupiterTestEngine`.
