[[release-notes-5.13.0-M1]]
== 5.13.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/85?closed=1+[5.13.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.13.0-M1-junit-platform]]
=== JUnit Platform

[[release-notes-5.13.0-M1-junit-platform-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M1-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* ❓


[[release-notes-5.13.0-M1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.13.0-M1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* If the `autoCloseArguments` attribute in `@ParameterizedTest` is set to `true`, all
  arguments returned by registered `ArgumentsProvider` implementations are now closed even
  if the test method declares fewer parameters.
* `AutoCloseable` arguments returned by an `ArgumentsProvider` are now closed even if they
  are wrapped with `Named`.
* `AutoCloseable` arguments returned by an `ArgumentsProvider` are now closed even if a
  failure happens prior to invoking the parameterized method.

[[release-notes-5.13.0-M1-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Introduce `@ContainerTemplate` and `ContainerTemplateInvocationContextProvider` that
  allow declaring a top-level or `@Nested` test class as a template to be invoked multiple
  times. This may be used, for example, to inject different parameters to be used by all
  tests in the container template class or to set up each invocation of the container
  template differently. Please refer to the
  <<../user-guide/index.adoc#writing-tests-container-templates, User Guide>> for details.
* Introduce `@ParameterizedClass` concept that builds on `@ContainerTemplate` and allows
  declaring a top-level or `@Nested` test class as a parameterized test class to be
  invoked multiple times with different arguments. The same `@...Source` annotations as
  for `@ParameterizedTest` may be used to provide arguments via constructor or field
  injection. Please refer to the
  <<../user-guide/index.adoc#writing-tests-parameterized-tests, User Guide>> for details.
* New `TestTemplateInvocationContext.prepareInvocation(ExtensionContext)` callback method
  allows preparing the `ExtensionContext` before the test template method is invoked. This
  may be used, for example, to store entries in its `Store` to benefit from its cleanup
  support or for retrieval by other extensions.


[[release-notes-5.13.0-M1-junit-vintage]]
=== JUnit Vintage

[[release-notes-5.13.0-M1-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M1-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M1-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
