[[release-notes-5.1.0-RC1]]
== 5.1.0-RC1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/19?closed=1+[5.1 RC1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-RC1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.1.0-RC1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The `value` attribute of `@MethodSource` is no longer mandatory. If no value (or an
  empty String) is supplied as a method name, a method with the same name as the current
  `@ParameterizedTest` method will be used as the factory method by convention.
** See <<../user-guide/index.adoc#writing-tests-parameterized-tests-sources-MethodSource,
   @MethodSource>> in the User Guide for details.
* New `@DisabledIf` annotation that is used to control whether the annotated test class or
  test method is _enabled_ or _disabled_. It inverts the logic applied by `@EnabledIf`.
** See <<../user-guide/index.adoc#writing-tests-conditional, Conditional Test Execution>>
   in the User Guide for details.


[[release-notes-5.1.0-RC1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
