[[release-notes-5.10.0-M1]]
== 5.10.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/65?closed=1+[5.10.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.10.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* Building native images with GraalVM now requires configuring the build arg
  `--initialize-at-build-time=org.junit.platform.launcher.core.LauncherConfig`.

==== New Features and Improvements

* All utility methods in `ReflectionSupport` that return a `List` now have counterparts
  which return a `Stream`.
* For consistency with JUnit Jupiter lifecycle callbacks, listener method pairs for
  started/finished and opened/closed events are now invoked using "wrapping" semantics.
  This means that finished/closed event methods are invoked in reverse order compared to
  the corresponding started/opened event methods when multiple listeners are registered.
  This affects the following listener interfaces:
  `TestExecutionListener`, `EngineExecutionListener`, `LauncherDiscoveryListener`, and
  `LauncherSessionListener`.
* New `LauncherInterceptor` SPI for intercepting the creation of instances of `Launcher`
  and `LauncherSessionlistener` as well as invocations of the `discover` and `execute`
  methods of the former. Please refer to the
  <<../user-guide/index.adoc#launcher-api-launcher-interceptors-custom, User Guide>> for
  details.
* Support for limiting the `max-pool-size-factor` for parallel execution via a configuration parameter.
* The new `testfeed` details mode for `ConsoleLauncher` prints test execution events as
  they occur in a concise format.


[[release-notes-5.10.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Parameter types for _local_ `@MethodSource` factory method names are now validated. For
  example, `@MethodSource("myFactory(example.NonexistentType)")` will now result in an
  exception stating that `example.NonexistentType` cannot be resolved to a valid type.
* The syntax for parameter types in _local_ `@MethodSource` factory method names now
  supports canonical array names -- for example, you may now specify `int[]` as in
  `@MethodSource("myFactory(int[])"` instead of the _binary_ name `[I` as in
  `@MethodSource("myFactory([I)"` (which was already supported) and
  `@MethodSource("myFactory(java.lang.String[])` instead of
  `@MethodSource("myFactory([Ljava.lang.String;)`.
* Exceptions thrown for undeletable files when cleaning up a temporary directory created
  via `@TempDir` now include the root cause.

==== Deprecations and Breaking Changes

* The `dynamic` parallel execution strategy now allows the thread pool to be saturated by
default.

==== New Features and Improvements

* `@RepeatedTest` can now be configured with a failure threshold which signifies the
  number of failures after which remaining repetitions will be automatically skipped. See
  the <<../user-guide/index.adoc#writing-tests-repeated-tests, User Guide>> for details.
* New `ArgumentsAccessor.getInvocationIndex()` method that supplies the index of a
  `@ParameterizedTest` invocation.
* `@EmptySource` now supports additional types, including `Collection` and `Map` subtypes
  with a public no-arg constructor.
* New `AnnotationBasedArgumentsProvider` that implements both `ArgumentsProvider` and
  `AnnotationConsumer` interfaces.
* New `AnnotationBasedArgumentConverter` that implements both `ArgumentConverter` and
  `AnnotationConsumer` interfaces.
* `DisplayNameGenerator` methods are now allowed to return `null`, in order to signal to
  fall back to the default display name generator.
* New `junit.jupiter.execution.parallel.config.dynamic.max-pool-size-factor` configuration
  parameter to set the maximum pool size factor.
* New `junit.jupiter.execution.parallel.config.dynamic.saturate` configuration
  parameter to disable pool saturation.


[[release-notes-5.10.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
