[[release-notes-5.4.0-M1]]
== 5.4.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult
the link:{junit5-repo}+/milestone/29?closed=1+[5.4.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.4.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* JUnit 4's `AssumptionViolatedException` is now supported in JUnit Jupiter for aborting
  a test mid-flight due to a failed assumption -- for example, via JUnit 4's
  `org.junit.Assume` utility class.
* In addition to returning streams, `@TestFactory`-annotated methods may return a single
  `DynamicNode`, i.e. a `DynamicTest` or a `DynamicContainer`, instance.
* New `DisplayNameGenerator` interface and `@DisplayNameGeneration` annotation that allow
  declarative configuration of a pre-defined or custom display name generator.

[[release-notes-5.4.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `Assertions.assertAll()` is now thread-safe, i.e. it can be used with _parallel_ `Streams`.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.4.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
