[[release-notes-5.12.0-M1]]
== 5.12.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/75?closed=1+[5.12.0-M1] milestone page in the
JUnit repository on GitHub.


[[release-notes-5.12.0-M1-overall-improvements]]
=== Overall Improvements

[[release-notes-5.12.0-M1-overall-new-features-and-improvements]]
==== New Features and Improvements

* All affected JAR files now include `native-image.properties` files that contain the
  `--initialize-at-build-time` option to avoid breakages in GraalVM projects when updating
  to newer versions of JUnit.


[[release-notes-5.12.0-M1-junit-platform]]
=== JUnit Platform

[[release-notes-5.12.0-M1-junit-platform-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.12.0-M1-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.12.0-M1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* New `addResourceContainerSelectorResolver()` in `EngineDiscoveryRequestResolver.Builder` to
  support the discovery of class path resource based tests, analogous to the
  `addClassContainerSelectorResolver()`.
* Introduce `ReflectionSupport.makeAccessible(Field)` for third-party use rather than
  calling the internal `ReflectionUtils.makeAccessible(Field)` method directly.
* Support both the primitive type `void` and the wrapper type `Void` in the internal
  `ReflectionUtils` to allow `String` to `Class` conversion in parameterized tests.
* Add support for passing line and column number to `ConsoleLauncher` via
  `--select-file` and `--select-resource`.
* `ConsoleLauncher` now accepts multiple values for all `--select` options.
* Add `--select-unique-id` support to ConsoleLauncher.
* Add `getOutputDirectoryProvider()` method to `EngineDiscoveryRequest` and `TestPlan` to
  allow test engines to publish/attach files to containers and tests by calling
  `EngineExecutionListener.fileEntryPublished(...)`. Registered `TestExecutionListeners`
  can then access these files by overriding the `fileEntryPublished(...)` method.
* The following improvements have been made to the
  <<../user-guide/index.adoc#junit-platform-reporting-open-test-reporting, Open Test Reporting>>
  XML output:
  - Information about the Git repository, the current branch, the commit hash, and the
    current worktree status are now included in the XML report, if applicable.
  - A section containing JUnit-specific metadata about each test/container to the HTML
    report is now written by open-test-reporting when added to the classpath/module path
  - Information about published files is now included as attachments.
  - If <<../user-guide/index.adoc#running-tests-capturing-output, output capturing>> is
    enabled, the captured output written to `System.out` and `System.err` is now included
    in the XML report.
* Output written to `System.out` and `System.err` from non-test threads is now attributed
  to the most recent test or container that was started or has written output.
* Introduced contracts for Kotlin-specific assertion methods.
* New public interface `ClasspathScanner` allowing third parties to provide a custom
  implementation for scanning the classpath for classes and resources.


[[release-notes-5.12.0-M1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.12.0-M1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.12.0-M1-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* When injecting `TestInfo` into test class constructors it now contains data of the test
  method the test class instance is being created for unless the test instance lifecycle
  is set to `PER_CLASS` (in which case it continues to contain the data of the test
  class). If you require the `TestInfo` of the test class, you can implement a class-level
  lifecycle method (e.g., `@BeforeAll`) and inject `TestInfo` into that method.
* When injecting `TestReporter` into test class constructors the published report entries
  are now associated with the test method rather than the test class unless the test
  instance lifecycle is set to `PER_CLASS` (in which case they will continue to be
  associated with the test class). If you want to publish report entries for the test
  class, you can implement a class-level lifecycle method (e.g., `@BeforeAll`) and inject
  `TestReporter` into that method.

[[release-notes-5.12.0-M1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* New `--exclude-methodname` and `--include-methodname` options added to the
  `ConsoleLauncher` to include or exclude methods based on fully qualified method names
  without parameters. For example, `--exclude-methodname=^org\.example\..+#methodname`
  will exclude all methods called `methodName` under package `org.example`.
* In a `@ParameterizedTest` method, a `null` value can now be supplied for Java Date/Time
  types such as `LocalDate` if the new `nullable` attribute in
  `@JavaTimeConversionPattern` is set to `true`.
* `ArgumentsProvider` (declared via `@ArgumentsSource`), `ArgumentConverter` (declared via
  `@ConvertWith`), and `ArgumentsAggregator` (declared via `@AggregateWith`)
  implementations can now use constructor injection from registered `ParameterResolver`
  extensions.
* Extensions based on `TestTemplateInvocationContextProvider` can now allow returning zero
  invocation contexts by overriding the new `mayReturnZeroTestTemplateInvocationContexts`
  method.
* The new `@ParameterizedTest(allowZeroInvocations = true)` attribute allows to specify that
  the absence of invocations is expected in some cases and should not cause a test failure.
* Allow determining "shared resources" at runtime via the new `@ResourceLock#providers`
  attribute that accepts implementations of `ResourceLocksProvider`.
* Allow declaring "shared resources" for _direct_ child nodes via the new
  `@ResourceLock(target = CHILDREN)` attribute. This may improve parallelization when
  a test class declares a `READ` lock, but only a few methods hold a `READ_WRITE` lock.
* Extensions that implement `TestInstancePreConstructCallback`, `TestInstanceFactory`,
  `TestInstancePostProcessor`, `ParameterResolver`, or `InvocationInterceptor` may
  override the `getTestInstantiationExtensionContextScope()` method to enable receiving
  a test-scoped `ExtensionContext` in `Extension` methods called during test class
  instantiation. This behavior will become the default in future versions of JUnit.
* `@TempDir` is now supported on test class constructors.
* Parameterized tests now support argument count validation.
  If the `junit.jupiter.params.argumentCountValidation=strict` configuration parameter
  or the `@ParameterizedTest(argumentCountValidation = STRICT)` attribute is set, any
  mismatch between the declared number of arguments and the number of arguments provided
  by the arguments source will result in an error. By default, it's still only an error if
  there are fewer arguments provided than declared.
* The new `PreInterruptCallback` extension point defines the API for `Extensions` that
  wish to be called prior to invocations of `Thread#interrupt()` by the `@Timeout`
  extension.
* When enabled via the `junit.jupiter.execution.timeout.threaddump.enabled` configuration
  parameter, an implementation of `PreInterruptCallback` is registered that writes a
  thread dump to `System.out` prior to interrupting a test thread due to a timeout.
* `TestReporter` now allows publishing files for a test method or test class which can be
  used to include them in test reports, such as the Open Test Reporting format.
* New `from` and `to` attributes added to `@EnumSource` to support range selection of
  enum constants.


[[release-notes-5.12.0-M1-junit-vintage]]
=== JUnit Vintage

[[release-notes-5.12.0-M1-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.12.0-M1-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.12.0-M1-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
