[[release-notes-5.4.0-RC2]]
== 5.4.0-RC2

*Date of Release:* ❓

*Scope:* Simplification of the `@TempDir` support, as well as minor improvements and bug
fixes since 5.4.0-RC1.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/35?closed=1+[5.4.0-RC2] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.4.0-RC2-junit-platform]]
=== JUnit Platform

No changes


[[release-notes-5.4.0-RC2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* A change to the `TempDirectory` extension in 5.4.0-RC1 made it impossible for test
  classes to have any parameters declared in their constructor if the `TempDirectory`
  extension was registered. This regression has been fixed.

==== Deprecations and Breaking Changes

* The implementation of the `TempDirectory` extension is now internal to the
  `JupiterTestEngine`.
  - Declarations of `@ExtendWith(TempDirectory.class)` will now result in a compiler
    error; however, explicit registration is no longer necessary since the `TempDirectory`
    extension is now registered automatically.
  - The `ParentDirProvider` and `TempDirContext` APIs and corresponding factory methods in
    the `TempDirectory` extension have been removed without replacement. `@TempDir` can
    therefore no longer be configured with a custom file system or custom parent directory.
  - See the <<../user-guide/index.adoc#writing-tests-built-in-extensions-TempDirectory,
    User Guide>> for details.

==== New Features and Improvements

* `@TempDir` can now be used without the need to explicitly register the `TempDirectory`
  (which is now an internal implementation).
  - See the <<../user-guide/index.adoc#writing-tests-built-in-extensions-TempDirectory,
    User Guide>> for examples.


[[release-notes-5.4.0-RC2-junit-vintage]]
=== JUnit Vintage

No changes
