[[release-notes-5.12.0-RC1]]
== 5.12.0-RC1

*Date of Release:* February 7, 2025

*Scope:* Minor enhancements since JUnit 5.12.0-M1.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/88?closed=1+[5.12.0-RC1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.12.0-RC1-junit-platform]]
=== JUnit Platform

[[release-notes-5.12.0-RC1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* New `TestDescriptor.orderChildren(UnaryOperator<List<TestDescriptor>> orderer)`
  method to order children in place


[[release-notes-5.12.0-RC1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.12.0-RC1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* Fix handling of "junctions" on Windows during `@TempDir` cleanup: junctions will no
  longer be followed when deleting directories and broken junctions will be deleted.

[[release-notes-5.12.0-RC1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* `JRE`-based conditions such as `@EnabledOnJre` and `@DisabledForJreRange` now support
  arbitrary Java versions. See the
  <<../user-guide/index.adoc#writing-tests-conditional-execution-jre, User Guide>> for
  details.


[[release-notes-5.12.0-RC1-junit-vintage]]
=== JUnit Vintage

No changes.
