[[release-notes-5.7.0-M2]]
== 5.7.0-M2

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/49?closed=1+[5.7 M2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.7.0-M2-overall-improvements]]
=== Overall Improvements

* Javadoc JARs now contain `package-list` in addition to `element-list` for compatibility
  with tools like NetBeans 11.


[[release-notes-5.7.0-M2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Characters in exception messages and other user-supplied values that are not allowed in
  XML are now replaced with their character reference – for example, `\0` becomes `&#0;`.

==== Deprecations and Breaking Changes

* `EngineTestKit` no longer takes into account implicit configuration parameters (i.e.
  system properties and the `junit-platform.properties` classpath resource) by default.
  This change makes tests executed via `EngineTestKit` independent of the environment they
  are executed in.

==== New Features and Improvements

* When using `ConsoleLauncher`, explicitly selected classes from `--select-class` and
  `--select-method` are now always executed regardless of class name patterns provided
  with `--include-classname` or the default class name pattern.
* The `ConsoleLauncher` now honors the `--disable-ansi-colors` option when printing usage
  help.
* New `FilePosition` support in `FileSelector` and `ClasspathResourceSelector`.
* Custom `PostDiscoveryFilter` implementations can now be registered via Java’s
  `ServiceLoader` mechanism.
* New `getJavaClass()` and `getJavaMethod()` methods in
  `org.junit.platform.engine.support.descriptor.MethodSource`.
* New module `org.junit.platform.jfr` added. When running on Java 11 or later, it
 provides and registers a `TestExecutionListener` that generates Java Flight Recorder
 events.

[[release-notes-5.7.0-M2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Registered `TestInstancePreDestroyCallback` extensions are now always called if an
  instance of a test class was created, regardless whether any registered
  `TestInstancePostProcessor` extension threw an exception.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* All `@Enabled*`/`@Disabled*` annotations now have an optional `disabledReason` attribute
  that can be used to provide and additional explanation as to why a test or container
  might be disabled.
* New `assertLinesMatch()` method overloads in `Assertions` that accept two
  `Stream<String>` instances for comparison.
* `@CsvFileSource` now allows one to specify file paths as an alternative to classpath
  resources.
* `JAVA_16` has been added to the `JRE` enum for use with JRE-based execution conditions.


[[release-notes-5.7.0-M2-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
