[[release-notes-5.12.1]]
== 5.12.1

*Date of Release:* March 14, 2025

*Scope:* Bug fixes and enhancements since 5.12.0

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/91?closed=1+[5.12.1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.12.1-junit-platform]]
=== JUnit Platform

[[release-notes-5.12.1-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* Set stable module name `org.junit.platform.console.standalone` for the
  `junit-platform-console-standalone` artifact, superseding the unstable name generated
  from the name of the JAR file when putting the artifact on the module path.


[[release-notes-5.12.1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.12.1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* New `ExtensionContext.getEnclosingTestClasses()` method to help with migration away from
  `AnnotationSupport.findAnnotation(Class, Class, SearchOption)` (deprecated since 1.12.0)
  to `AnnotationSupport.findAnnotation(Class, Class, List)`.


[[release-notes-5.12.1-junit-vintage]]
=== JUnit Vintage

No changes.
