[[release-notes-5.8.0-M1]]
== 5.8.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/51?closed=1+[5.8 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.8.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Method `scanForClassesInPackage(String)` in `ClasspathScanner` now returns a valid list
  of class names when the package name is equal to the name of a module on the module path.

==== Deprecations and Breaking Changes

* For consistency with the rest of the JUnit Platform, the experimental
  `LauncherDiscoveryListener` is now an interface instead of an abstract class.

==== New Features and Improvements

* New `test(Condition<Event>)` and `nestedContainer(Class<?>, Condition<Event>)` methods
  in `EventConditions` that allow you to provide conditions for matching against test and
  nested container events when using the `EngineTestKit`. For example,
  `test(displayName("my test"))` can be used to match against a test whose display name is
  `my test`.
* The `junit-platform-jfr` module now also reports execution events for containers, e.g.
  test classes.
* The `junit-platform-jfr` module now also reports test discovery events for the launcher
  and registered test engines.
* Custom `LauncherDiscoveryListener` implementations can now be registered via Java’s
  `{ServiceLoader}` mechanism.
* Documented constant value of `ExclusiveResource.GLOBAL_KEY`.
* Instances of `TestIdentifier` and `UniqueId` now retain less memory because they no
  longer store `String` representations of unique IDs.
* Improvement of `ExclusiveResource` handling, if a `Node` has only read locks and no read-write locks,
  then descendants are not forced into `SAME_THREAD` execution, and can run concurrently.
* Tools that make multiple calls to the `Launcher` API should now create a
  `LauncherSession` instead in order to allow for executing global setup and teardown code
  exactly once via the new `LauncherSessionListener` interface that can be registered via
  Java’s `{ServiceLoader}` mechanism.


[[release-notes-5.8.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* `InvocationInterceptor.interceptDynamicTest(Invocation<Void> , ExtensionContext)` has
  been deprecated in favor of
  `InvocationInterceptor.interceptDynamicTest(Invocation<Void> , DynamicTestInvocationContext, ExtensionContext)`
  that allows to access the dynamic test executable via
  `DynamicTestInvocationContext.getExecutable()`.

==== New Features and Improvements

* Numeric literals used with `@CsvSource` or `CsvFileSource` can now be expressed using
  underscores as in some JVM languages, to improve readability of long numbers like
  `700_000_000`.
* Documented constant values in `Resources`.
* New `assertInstanceOf` methods as a replacement for `assertTrue(obj instanceof X)` which
  provide better error messages comparable to those of `assertThrows`.
* Dynamic tests now require less memory thanks to a number of improvements to internal
  data structures.
* Allow rows in `@CsvSource` to start with a number sign (#)
* New `ignoreLeadingAndTrailingWhitespace` attribute to control whether or not to trim
  whitespaces in `@CsvSource` and `@CsvFileSource` (set to `true` by default).
* Top-level test classes can now be ordered by passing the fully-qualified name of a
  class implementing `ClassOrderer` as value of the new
  `junit.jupiter.testclass.order.default` configuration property.


[[release-notes-5.8.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The JUnit Vintage engine now requires less memory and allows for earlier garbage
  collection thanks to a number of improvements to internal data structures.
