[[release-notes-5.8.0-M1]]
== 5.8.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/51?closed=1+[5.8 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.8.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* For consistency with the rest of the JUnit Platform, the experimental
  `LauncherDiscoveryListener` is now an interface instead of an abstract class.

==== New Features and Improvements

* New `test(Condition<Event>)` and `nestedContainer(Class<?>, Condition<Event>)` methods
  in `EventConditions` that allow you to provide conditions for matching against test and
  nested container events when using the `EngineTestKit`. For example,
  `test(displayName("my test"))` can be used to match against a test whose display name is
  `my test`.
* The `junit-platform-jfr` module now reports execution events for containers -- for
  example, test classes.
* The `junit-platform-jfr` module now reports test discovery events for the launcher and
  registered test engines.
* Custom `LauncherDiscoveryListener` implementations can now be registered via Java’s
  `{ServiceLoader}` mechanism.
* Documented constant value of `ExclusiveResource.GLOBAL_KEY`.
* Instances of `TestIdentifier` and `UniqueId` now retain less memory because they no
  longer store `String` representations of unique IDs.
* Improved of `ExclusiveResource` handling: if a `Node` has only read locks and no
  read-write locks, then descendants are not forced into `SAME_THREAD` execution and can
  run concurrently.
* Tools that make multiple calls to the `Launcher` API should now create a
  `LauncherSession` in order to allow for executing global setup and teardown code exactly
  once via the new `LauncherSessionListener` interface that can be registered via Java’s
  `{ServiceLoader}` mechanism.


[[release-notes-5.8.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* `InvocationInterceptor.interceptDynamicTest(Invocation<Void>, ExtensionContext)` has
  been deprecated in favor of
  `InvocationInterceptor.interceptDynamicTest(Invocation<Void>, DynamicTestInvocationContext, ExtensionContext)`
  that provides access to the dynamic test executable via
  `DynamicTestInvocationContext.getExecutable()`.

==== New Features and Improvements

* Top-level test classes can now be ordered by passing the fully-qualified name of a
  class implementing `ClassOrderer` as the value of the new
  `junit.jupiter.testclass.order.default` configuration parameter.
* New `assertInstanceOf()` methods which produce better error messages comparable to those
  produced by `assertThrows`. These new methods serve as a replacement for
  `assertTrue(obj instanceof X)`.
* `assertNull()` failure messages now include the actual object's type if the `toString()`
  implementation for the actual object returns `null` or `"null"`. This avoids the
  generation of confusing failure messages such as `expected <null> but was <null>`.

* Numeric literals used with `@CsvSource` or `CsvFileSource` can now be expressed using
  underscores as in some JVM languages, to improve readability of long numbers like
  `700_000_000`.
* CSV rows provided via `@CsvSource` may now start with a number sign (`#`).
* New `ignoreLeadingAndTrailingWhitespace` attributes in `@CsvSource` and `@CsvFileSource`
  (set to `true` by default) to control whether or not to trim whitespace.
* Dynamic tests now require less memory thanks to a number of improvements to internal
  data structures.
* Documented constant values in `org.junit.jupiter.api.parallel.Resources`.
* New `assertThrowsExactly` method is introduced as a more strict version of `assertThrows`
  allowing you to assert that the thrown exception has the exact specified class.



[[release-notes-5.8.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The JUnit Vintage engine now requires less memory and allows for earlier garbage
  collection thanks to a number of improvements to internal data structures.
