[[release-notes-6.0.0-RC2]]
== 6.0.0-RC2

*Date of Release:* ❓

*Scope:* Minor enhancements and bug fixes since 6.0.0-RC1.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit-framework-repo}+/milestone/105?closed=1+[6.0.0-RC2] milestone page in the
JUnit repository on GitHub.

[TIP]
.Migration Guide
====
Please refer to the
https://github.com/junit-team/junit-framework/wiki/Upgrading-to-JUnit-6.0[wiki] for
guidance on upgrading from JUnit 5.x.y to 6.0.0.
====


[[release-notes-6.0.0-RC2-junit-platform]]
=== JUnit Platform

[[release-notes-6.0.0-RC2-junit-platform-bug-fixes]]
==== Bug Fixes

* The `Launcher` (specifically `LauncherDiscoveryResult`) now retains the original
  `TestEngine` registration order after pruning test engines without tests, thereby
  ensuring reliable test execution order of multiple test engines.

[[release-notes-6.0.0-RC2-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-6.0.0-RC2-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* New `discoveryRequest()` method in `{LauncherDiscoveryRequestBuilder}`, which is an
  alias for the existing `request()` method and is intended to be used via a `static`
  import.
* New `executionRequest(...)` methods in `{LauncherExecutionRequestBuilder}`, which are
  aliases for the existing `request(...)` methods and are intended to be used via a
  `static` import.
* New `selectClasses(...)` and `selectClassesByName(...)` factory methods have been
  introduced in `{DiscoverySelectors}` to simplify use cases where one needs to select
  multiple individual test classes for the `Launcher` or `EngineTestKit`.
* New `selectors(List)` builder method for `{EngineTestKit}` which can be used in
  conjunction with the new `selectClasses(...)` and `selectClassesByName(...)` factory
  methods in `DiscoverySelectors`.


[[release-notes-6.0.0-RC2-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-6.0.0-RC2-junit-jupiter-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-6.0.0-RC2-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-6.0.0-RC2-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* ❓


[[release-notes-6.0.0-RC2-junit-vintage]]
=== JUnit Vintage

[[release-notes-6.0.0-RC2-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-6.0.0-RC2-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-6.0.0-RC2-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
