[[release-notes-5.12.0]]
== 5.12.0

*Date of Release:* February 21, 2025

*Scope:*

* Output file attachments for tests and containers
* Improvements to the Open Test Reporting XML output
* Resource lock definition improvements
* Thread dumps on test timeouts
* Parameterized test validation improvements
* Filtering support for auto-registered extensions
* Kotlin contracts for assertions
* Configurable Jupiter extension context scope
* Enhancements to the `ConsoleLauncher`
* Better support for GraalVM native image usage
* Improved discovery support for file-based test engines
* Customizable classpath scanning
* Parallel execution support in JUnit Vintage engine
* Numerous bug fixes and other enhancements

For a complete list of all _closed_ issues and pull requests for this release, consult the link:{junit5-repo}+/milestone/75?closed=1+[5.12.0-M1],
link:{junit5-repo}+/milestone/88?closed=1+[5.12.0-RC1],
link:{junit5-repo}+/milestone/90?closed=1+[5.12.0-RC2], and
link:{junit5-repo}+/milestone/89?closed=1+[5.12.0] milestone pages in the JUnit repository
on GitHub.


[[release-notes-5.12.0-overall-improvements]]
=== Overall Improvements

[[release-notes-5.12.0-overall-new-features-and-improvements]]
==== New Features and Improvements

* All affected JAR files now include `native-image.properties` files that contain the
`--initialize-at-build-time` option to avoid breakages in GraalVM projects when updating
to newer versions of JUnit.


[[release-notes-5.12.0-junit-platform]]
=== JUnit Platform

[[release-notes-5.12.0-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* `SearchOption` and `AnnotationSupport.findAnnotation(Class, Class, SearchOption)` from
  `junit-platform-commons` have been deprecated.

[[release-notes-5.12.0-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* `ConsoleLauncher` now accepts multiple values for all `--select` options.
* `ConsoleLauncher` now supports a `--select-unique-id` option to select containers and
  tests by unique ID.
* `ConsoleLauncher` supports new `--exclude-methodname` and `--include-methodname` options
  to include or exclude methods based on fully qualified method names without parameters.
  For example, `--exclude-methodname=^org\.example\..+#methodname` will exclude all
  methods called `methodName` under package `org.example`.
* The `--select-file` and `--select-resource` options for the `ConsoleLauncher` now
  support line and column numbers.
* New `ReflectionSupport.makeAccessible(Field)` public utility method to be used by third
  parties instead of calling the internal `ReflectionUtils.makeAccessible(Field)` method
  directly.
* The `ReflectionSupport.tryToLoadClass(...)` utility methods now support lookups for the
  `"void"` pseudo-type, which indirectly supports `String` to `Class` conversion for
  `"void"` in parameterized tests in JUnit Jupiter.
* New `addResourceContainerSelectorResolver()` method in
  `EngineDiscoveryRequestResolver.Builder` which supports the discovery of class path
  resource based tests, analogous to the existing `addClassContainerSelectorResolver()`
  method.
* New `getOutputDirectoryProvider()` method in `EngineDiscoveryRequest` and `TestPlan` to
  allow test engines to publish/attach files to containers and tests by calling
  `EngineExecutionListener.fileEntryPublished(...)`. Registered `TestExecutionListeners`
  can then access these files by overriding the `fileEntryPublished(...)` method.
* The following improvements have been made to the
  <<../user-guide/index.adoc#junit-platform-reporting-open-test-reporting, Open Test Reporting>>
  XML output:
  - Information about the Git repository, the current branch, the commit hash, and the
    current worktree status are now included in the XML report, if applicable.
  - A section containing JUnit-specific metadata about each test/container to the HTML
    report is now written by open-test-reporting when added to the classpath/module path
  - Information about published files is now included as attachments.
  - If <<../user-guide/index.adoc#running-tests-capturing-output, output capturing>> is
    enabled, the captured output written to `System.out` and `System.err` is now included
    in the XML report.
* Output written to `System.out` and `System.err` from non-test threads is now attributed
  to the most recent test or container that was started or has written output.
* New public interface `ClasspathScanner` allowing third parties to provide a custom
  implementation for scanning the classpath for classes and resources.
* New `AnnotationSupport.findAnnotation(Class, Class, List)` method to support searching
  for an annotation on an inner class and its runtime enclosing instance types.
* New `TestDescriptor.orderChildren(UnaryOperator<List<TestDescriptor>> orderer)`
  method to order children in place


[[release-notes-5.12.0-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.12.0-junit-jupiter-bug-fixes]]
==== Bug Fixes

* Provide _runtime_ enclosing types of `@Nested` test classes and contained test methods
  to `DisplayNameGenerator` implementations. Prior to this change, such generators were
  only able to access the enclosing class in which `@Nested` was declared, but they could
  not access the concrete runtime type of the enclosing instance.
* `@DisplayNameGeneration` annotations are now discovered on the _runtime_ enclosing types
  of `@Nested` test classes instead of the compile-time enclosing class in which the
  `@Nested` class was _declared_.
* Fix handling of "junctions" on Windows during `@TempDir` cleanup: junctions will no
  longer be followed when deleting directories and broken junctions will be deleted.

[[release-notes-5.12.0-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* When injecting `TestInfo` into test class constructors, the `TestInfo` now contains data
  for the test method for which the test class instance is being created, unless the test
  instance lifecycle is set to `PER_CLASS` (in which case it continues to contain the data
  for the test class). If you require the `TestInfo` of the test class, you can implement
  a `@BeforeAll` lifecycle method and inject `TestInfo` into that method.
* When injecting `TestReporter` into test class constructors the published report entries
  are now associated with the test method rather than the test class, unless the test
  instance lifecycle is set to `PER_CLASS` (in which case the published report entries
  will continue to be associated with the test class). If you want to publish report
  entries for the test class, you can implement a `@BeforeAll` lifecycle method and inject
  `TestReporter` into that method.

[[release-notes-5.12.0-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Kotlin contracts for Kotlin-specific assertion methods in `Assertions`.
* `@TempDir` is now supported on test class constructors.
* Shared resource locks may now be determined programmatically at runtime via the new
  `@ResourceLock#providers` attribute that accepts implementations of
  `ResourceLocksProvider`.
* Shared resource locks for _direct_ child nodes may now be configured via the new
  `@ResourceLock(target = CHILDREN)` attribute. This may improve parallelization when
  a test class declares a `READ` lock, but only a few methods hold a `READ_WRITE` lock.
* `@EnumSource` has new `from` and `to` attributes that support the selection of enum
  constants within the specified range.
* In a `@ParameterizedTest` method, a `null` value can now be supplied for Java Date/Time
  types such as `LocalDate` if the new `nullable` attribute in
  `@JavaTimeConversionPattern` is set to `true`.
* The new `@ParameterizedTest(allowZeroInvocations = true)` attribute allows to specify that
  the absence of invocations is expected in some cases and should not cause a test failure.
* Parameterized tests now support argument count validation. If the
  `junit.jupiter.params.argumentCountValidation=strict` configuration parameter or the
  `@ParameterizedTest(argumentCountValidation = STRICT)` attribute is set, any mismatch
  between the declared number of arguments and the number of arguments provided by the
  arguments source will result in an error. By default, it is still only an error if there
  are fewer arguments provided than declared.
* `ArgumentsProvider` (declared via `@ArgumentsSource`), `ArgumentConverter` (declared via
  `@ConvertWith`), and `ArgumentsAggregator` (declared via `@AggregateWith`)
  implementations can now use constructor injection from registered `ParameterResolver`
  extensions.
* `TestTemplateInvocationContextProvider` extensions can now signal that they may
  potentially return zero invocation contexts by overriding the new
  `mayReturnZeroTestTemplateInvocationContexts()` method.
* Extensions that implement `TestInstancePreConstructCallback`, `TestInstanceFactory`,
  `TestInstancePostProcessor`, `ParameterResolver`, or `InvocationInterceptor` may
  override the `getTestInstantiationExtensionContextScope()` method to enable receiving
  a test-scoped `ExtensionContext` in `Extension` methods called during test class
  instantiation. This behavior will become the default in future versions of JUnit.
* The new `PreInterruptCallback` interface defines the API for `Extensions` that wish to
  be called prior to invocations of `Thread#interrupt()` by the `@Timeout` extension.
* When enabled via the `junit.jupiter.execution.timeout.threaddump.enabled` configuration
  parameter, an implementation of `PreInterruptCallback` is registered that writes a
  thread dump to `System.out` prior to interrupting a test thread due to a timeout.
* `TestReporter` now allows publishing files for a test method or test class which can be
  used to include them in test reports, such as the Open Test Reporting format.
* Auto-registered extensions can now be
  <<../user-guide/index.adoc#extensions-registration-automatic-filtering, filtered>> using
  include and exclude patterns that can be specified as configuration parameters.
* `JRE`-based conditions such as `@EnabledOnJre` and `@DisabledForJreRange` now support
  arbitrary Java versions. See the
  <<../user-guide/index.adoc#writing-tests-conditional-execution-jre, User Guide>> for
  details.
* The `@TempDir` extension now warns during cleanup when deleting symlinks that target
  locations outside the temporary directory to signal that the target file or directory is
  _not_ deleted, only the link to it.


[[release-notes-5.12.0-junit-vintage]]
=== JUnit Vintage

[[release-notes-5.12.0-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* Added support for executing test classes and/or methods in parallel. Please refer to the
  <<../user-guide/index.adoc#migrating-from-junit4-parallel-execution, User Guide>> for
  more information.
