[[release-notes-5.3.0-M1]]
== 5.3.0-M1

*Date of Release:* June 24, 2018

*Scope:* Parallel test execution, output capturing, test sources for dynamic tests as well
as various minor improvements and bug fixes.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/23?closed=1+[5.3 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.3.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* The full stacktrace is now printed to the console when running the `ConsoleLauncher`
  in `--details verbose` mode.
* `ReflectionUtils.findNestedClasses()` and `ReflectionSupport.findNestedClasses()` no
  longer allow a `NoClassDefFoundError` to propagate if a nested class or nested
  interface has an invalid class file. Instead, the error will now be swallowed and
  logged at `WARNING` level.

==== Deprecations and Breaking Changes

* The `junit-platform-gradle-plugin` has been discontinued and is no longer released as
  part of JUnit 5. Please use <<../user-guide/index.adoc#running-tests-build-gradle,
  Gradle's native support>> for running tests on the JUnit Platform (requires Gradle 4.6
  or higher) instead.
* The `findAnnotation()` methods in `AnnotationSupport` and `AnnotationUtils` no longer
  cache annotation lookups. Note, however, that the algorithm remains otherwise
  unmodified and is therefore semantically identical to the previous behavior.

==== New Features and Improvements

* Experimental support for capturing output printed to `System.out` and `System.err`
  during test execution. This feature is disabled by default and can be enabled using a
  configuration parameter (see the
  <<../user-guide/index.adoc#running-tests-capturing-output, User Guide>> for details).
* Reusable support for parallel test execution for test engines that extend
  `HierarchicalTestEngine`.
  - `HierarchicalTestEngine` implementations may now specify a
    `HierarchicalTestExecutorService`.
  - By default, a `SameThreadHierarchicalTestExecutorService` is used.
  - Test engines may use `ForkJoinPoolHierarchicalTestExecutorService` to support
    parallel test execution based on Java's Fork/Join framework.
  - `Node` implementations may provide a set of `ExclusiveResources` and an
    `ExecutionMode` to be used by `ForkJoinPoolHierarchicalTestExecutorService`.
* New `UriSource.from(URI)` static factory method that allows a `TestSource` to be
  created from a `URI`. If the `URI` references a file or directory in the local
  filesystem, a `FileSource` or `DirectorySource` will be created; otherwise, an instance
  of the default `UriSource` implementation will be created.
* New overloaded variant of `isAnnotated()` in `AnnotationSupport` that accepts
  `Optional<? extends AnnotatedElement>` instead of `AnnotatedElement`.
* New `--fail-if-no-tests` command-line option for the `ConsoleLauncher`.
  - When this option is enabled and no tests are discovered, the launcher will fail and
    exit with a status code of `2`.


[[release-notes-5.3.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* When using `@TestInstance(Lifecycle.PER_CLASS)` semantics, registered
  `AfterAllCallback` extensions are no longer invoked if an exception is thrown by the
  test class constructor. Consequently, `AfterAllCallback` extensions are now only
  invoked if `BeforeAllCallback` extensions are invoked.
* Test discovery no longer halts prematurely if a nested class or nested interface in a
  test class has an invalid class file.
* Certain categories of errors encountered during the test discovery phase no longer
  cause JUnit Jupiter to prematurely abort the entire discovery process.
  - Such errors are now logged, thereby enabling JUnit Jupiter to discover and execute as
    many tests as possible while still informing the user of containers and tests that
    could not be properly discovered.

==== New Features and Improvements

* Experimental support for parallel test execution. By default, tests are still executed
  sequentially; parallelism can be enabled using a configuration parameter (please refer
  to the <<../user-guide/index.adoc#writing-tests-parallel-execution, User Guide>> for
  examples and configuration options).
* New support for the IBM AIX operating system in `@EnabledOnOs` and `@DisabledOnOs`.
* New `assertThrows` methods in `Assertions` provide a more specific failure message if
  the supplied lambda expression or method reference returns a result instead of throwing
  an exception.
* New `arguments()` static factory method in the `Arguments` interface that serves as an
  _alias_ for `Arguments.of()`. `arguments()` is intended to be used via `import static`.
* New `get<Class>(index)` Kotlin extension method to make `ArgumentsAccessor` friendlier
  to use from Kotlin.
* New support for supplying a custom test source `URI` when creating a dynamic container
  or test.
  - See the new factory methods `dynamicContainer(String, URI, ...)` in
    `DynamicContainer` and `dynamicTest(String, URI, Executable)` in `DynamicTest` for
    details.


[[release-notes-5.3.0-M1-junit-vintage]]
=== JUnit Vintage

No changes.
