[[release-notes-5.12.0-M1]]
== 5.12.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/75?closed=1+[5.12.0-M1] milestone page in the
JUnit repository on GitHub.


[[release-notes-5.12.0-M1-junit-platform]]
=== JUnit Platform

[[release-notes-5.12.0-M1-junit-platform-bug-fixes]]
==== Bug Fixes

* Fix support for disabling ANSI colors on the console when the `NO_COLOR` environment
  variable is available.

[[release-notes-5.12.0-M1-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.12.0-M1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* Introduce `ReflectionSupport.makeAccessible(Field)` for third-party use rather than
  calling the internal `ReflectionUtils.makeAccessible(Field)` method directly.
* Support both the primitive type `void` and the wrapper type `Void` in the internal
  `ReflectionUtils` to allow `String` to `Class` conversion in parameterized tests.


[[release-notes-5.12.0-M1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.12.0-M1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.12.0-M1-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* When injecting `TestInfo` into test class constructors it now contains data of the test
  method the test class instance is being created for unless the test instance lifecycle
  is set to `PER_CLASS` (in which case it continues to contain the data of the test
  class). If you require the `TestInfo` of the test class, you can implement a class-level
  lifecycle method (e.g., `@BeforeAll`) and inject `TestInfo` into that method.
* When injecting `TestReporter` into test class constructors the published report entries
  are now associated with the test method rather than the test class unless the test
  instance lifecycle is set to `PER_CLASS` (in which case they will continue to be
  associated with the test class). If you want to publish report entries for the test
  class, you can implement a class-level lifecycle method (e.g., `@BeforeAll`) and inject
  `TestReporter` into that method.

[[release-notes-5.12.0-M1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* New `--exclude-methodname` and `--include-methodname` options added to the
  `ConsoleLauncher` to include or exclude methods based on fully qualified method names
  without parameters. For example, `--exclude-methodname=^org\.example\..+#methodname`
  will exclude all methods called `methodName` under package `org.example`.
* In a `@ParameterizedTest` method, a `null` value can now be supplied for Java Date/Time
  types such as `LocalDate` if the new `nullable` attribute in
  `@JavaTimeConversionPattern` is set to `true`.
* `ArgumentsProvider` (declared via `@ArgumentsSource`), `ArgumentConverter` (declared via
  `@ConvertWith`), and `ArgumentsAggregator` (declared via `@AggregateWith`)
  implementations can now use constructor injection from registered `ParameterResolver`
  extensions.
* Extensions based on `TestTemplateInvocationContextProvider` can now allow returning zero
  invocation contexts by overriding the new `mayReturnZeroTestTemplateInvocationContexts`
  method.
* The new `@ParameterizedTest(requireArguments = false)` attribute allows to specify that
  the absence of arguments is expected in some cases and should not cause a test failure.
* Allow determining "shared resources" at runtime via the new `@ResourceLock#providers`
  attribute that accepts implementations of `ResourceLocksProvider`.
* Extensions that implement `TestInstancePreConstructCallback`, `TestInstanceFactory`,
  `TestInstancePostProcessor`, `ParameterResolver`, or `InvocationInterceptor` may
  override the `getTestInstantiationExtensionContextScope()` method to enable receiving
  a test-scoped `ExtensionContext` in `Extension` methods called during test class
  instantiation. This behavior will become the default in future versions of JUnit.
* `@TempDir` is now supported on test class constructors.
* Added `PreInterruptCallback`


[[release-notes-5.12.0-M1-junit-vintage]]
=== JUnit Vintage

[[release-notes-5.12.0-M1-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.12.0-M1-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.12.0-M1-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
