[[release-notes-6.0.0-RC1]]
== 6.0.0-RC1

*Date of Release:* August 20, 2025

*Scope:*

* Display name improvements for parameterized classes and tests
* Replacing of non-printable control characters in display names
* Deterministic order of `@Nested` classes
* Inheritance of `@TestMethodOrder` by enclosed `@Nested` classes
* `MethodOrderer.Default` and `ClassOrderer.Default` for `@Nested` classes

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit-framework-repo}+/milestone/102?closed=1+[6.0.0-RC1] milestone page in the JUnit
repository on GitHub.


[[release-notes-6.0.0-RC1-junit-platform]]
=== JUnit Platform

[[release-notes-6.0.0-RC1-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* The methods `findNestedClasses` and `streamNestedClasses` in `ReflectionSupport` now
  return nested classes declared in the same enclosing class or interface ordered in a
  deterministic but intentionally nonobvious way.

[[release-notes-6.0.0-RC1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* Stack traces are now pruned up to the test method or lifecycle method.
* Convention-based conversion in `ConversionSupport` now supports factory methods and
  factory constructors that accept a single `CharSequence` argument in addition to the
  existing support for factories that accept a single `String` argument.
* Non-printable control characters in display names are now replaced with alternative
  representations. For example, `\n` is replaced with `<LF>`. This applies to all display
  names in JUnit Jupiter, `@SuiteDisplayName`, and any other test engines that subclass
  `AbstractTestDescriptor`. Please refer to the
  <<../user-guide/index.adoc#writing-tests-display-names, User Guide>> for details.
* To help diagnosing potentially invalid invocations, the Console Launcher now logs
  warnings for nonexistent classpath roots added via `--classpath` or `--scan-classpath`
  rather than silently ignoring them.


[[release-notes-6.0.0-RC1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-6.0.0-RC1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* CSV headers are now properly supported with the default display name pattern and the
  explicit `+{argumentsWithNames}+` display name pattern for parameterized tests that
  utilize the `useHeadersInDisplayName` flag in `@CsvSource` and `@CsvFileSource`.
  Specifically, the parameter name is no longer duplicated in the display name when a CSV
  header is desired instead.

[[release-notes-6.0.0-RC1-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* For consistency with test methods, `@Nested` classes declared in the same enclosing
  class or interface are now ordered in a deterministic but intentionally nonobvious
  way.

[[release-notes-6.0.0-RC1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Text-based arguments in display names for parameterized tests are now quoted by default.
  In addition, special characters are escaped within quoted text. Please refer to the
  <<../user-guide/index.adoc#writing-tests-parameterized-tests-display-names-quoted-text,
  User Guide>> for details.
* <<../user-guide/index.adoc#writing-tests-parameterized-tests-argument-conversion-implicit-fallback,
  Fallback String-to-Object Conversion>> for parameterized tests now supports factory
  methods and factory constructors that accept a single `CharSequence` argument in
  addition to the existing support for factories that accept a single `String` argument.
* Non-printable control characters in display names are now replaced with alternative
  representations. Please refer to the
  <<../user-guide/index.adoc#writing-tests-display-names, User Guide>> for details.
* For consistency with `@TestClassOrder`, `@TestMethodOrder` annotations specified on a
  test class are now inherited by its `@Nested` inner classes, recursively.
* Introduce `MethodOrderer.Default` and `ClassOrderer.Default` for reverting back to
  default ordering on a `@Nested` class and its `@Nested` inner classes when an enclosing
  class specifies a different orderer via `@TestMethodOrder` or `@TestClassOrder`,
  respectively.


[[release-notes-6.0.0-RC1-junit-vintage]]
=== JUnit Vintage

No changes.
