[[release-notes-5.11.0]]
== 5.11.0

*Date of Release:* August 14, 2024

*Scope:*

* `@FieldSource` annotation for use with `@ParameterizedTest` methods
* Repeatable `@..Source` annotations for parameterized tests
* Enhancements for authoring dynamic and parameterized tests
* `@AutoClose` annotation to automatically close field resources in tests
* `ConversionSupport` utility for converting from a string to a supported target type
* Extensible syntax for specifying discovery selectors
* `@BeforeSuite` and `@AfterSuite` annotations
* Classpath resource scanning support for engines
* Numerous bug fixes and enhancements regarding field and method search algorithms

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/68?closed=1+[5.11.0-M1],
link:{junit5-repo}+/milestone/74?closed=1+[5.11.0-M2],
link:{junit5-repo}+/milestone/77?closed=1+[5.11.0-RC1], and
link:{junit5-repo}+/milestone/76?closed=1+[5.11.0] milestone pages in the JUnit repository
on GitHub.


[[release-notes-5.11.0-overall-improvements]]
=== Overall Improvements

[[release-notes-5.11.0-overall-new-features-and-improvements]]
==== New Features and Improvements

* Java classes in published artifacts are now compiled with the `-parameters` option of
  `javac` and thus now contain metadata for reflection on parameters such as their names.


[[release-notes-5.11.0-junit-platform]]
=== JUnit Platform

[[release-notes-5.11.0-junit-platform-bug-fixes]]
==== Bug Fixes

* Field and method search algorithms now adhere to standard Java semantics regarding
  whether a given field or method is visible or overridden according to the rules of the
  Java language. See the new
  <<../user-guide/index.adoc#extensions-supported-utilities-search-semantics, Field and
  Method Search Semantics>> section of the User Guide for details.
* `ReflectionSupport.findFields(...)` now returns a distinct set of fields.
* Fixed parsing of recursive jar URIs which allows the JUnit Platform Launcher to be used
  inside Spring Boot executable jars for Spring Boot 3.2 and later.
* The `junit-platform-suite-engine` now includes configuration provided via
  `@ConfigurationParameter` when selecting tests by `UniqueId` (backported to 5.10.3).
* In order to support using `@EnabledInNativeImage` on test classes,
  `UniqueIdTrackingListener` now tracks descendants of skipped test containers (backported
  to 5.10.3).
* Attempting to deserialize a `TestIdentifier` no longer causes a `NullPointerException`
  when there is no parent identifier. See
  link:https://github.com/junit-team/junit5/issues/3819[issue 3819] (backported to
  5.10.3).

[[release-notes-5.11.0-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* As mentioned in the _Bug Fixes_ section above, field and method search algorithms now
  adhere to standard Java semantics regarding whether a given field or method is visible
  or overridden according to the rules of the Java language. The changes in the search
  algorithms may, however, result in breaking changes for some use cases. In light of
  that, it is possible to revert to the previous "legacy semantics". See the new
  <<../user-guide/index.adoc#extensions-supported-utilities-search-semantics, Field and
  Method Search Semantics>> section of the User Guide for details.

[[release-notes-5.11.0-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* New `ConversionSupport` utility in `junit-platform-commons` which exposes the conversion
  logic that was previously private to JUnit Jupiter's `@ParameterizedTest` infrastructure
  -- for use in third-party extensions and test engines.
* Error messages for type mismatches in `NamespacedHierarchicalStore` now include the
  actual type and value in addition to the required type.
* Updated `open-test-reporting` dependency to `0.1.0-M2`.
* All Platform implementations of `DiscoverySelector` now have a parseable string
  representation that can be generated by calling the new
  `DiscoverySelector.toIdentifier()` method and `toString()` on the returned
  `DiscoverySelectorIdentifier`. This string representation can be used to reconstruct
  the original `DiscoverySelector` by calling the new `DiscoverySelectors.parse()` method.
  This change will allow build tools and IDEs to provide generic mechanisms for specifying
  selectors on the command line or in configuration files without having to support each
  selector type individually.
  - The Console Launcher supports specifying selectors via their identifiers using the
    `--select` option. For example, `--select class:foo.Bar` will run all tests in the
    `foo.Bar` class.
  - Similarly, the JUnit Platform Suite engine provides a new `@Select("<identifier>")`
    annotation.
* The Console Launcher now provides a `--version` option.
* `NamespacedHierarchicalStore` now throws an `IllegalStateException` for any attempt to
  modify or query the store after it has been closed. In addition, an attempt to close a
  store that has already been closed will have no effect.
  - See link:https://github.com/junit-team/junit5/issues/3614[issue 3614] for details.
* Introduce `@ConfigurationParametersResource` for `@Suite` classes and
  `--config-resource` option for ConsoleLauncher that allow specifying additional
  properties files on the classpath as sources of configuration parameters.
* New `rootCause()` condition in `TestExecutionResultConditions` that matches if an
  exception's _root_ cause matches all supplied conditions, for use with the
  `EngineTestKit`.
* `ReflectionSupport` now supports scanning for classpath resources.
* Introduce `@BeforeSuite` and `@AfterSuite` lifecycle methods for `@Suite` classes.


[[release-notes-5.11.0-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.11.0-junit-jupiter-bug-fixes]]
==== Bug Fixes

* Due to changes in the JUnit Platform regarding field and method search algorithms (see
  <<release-notes-5.11.0-junit-platform-bug-fixes>> above), numerous bugs have been
  addressed within JUnit Jupiter, including but not limited to the following.
  ** Two `@TempDir` fields with the same name in a superclass and subclass will now both
    be injected.
  ** Two `@Test` methods with the same signature in a superclass and subclass will now
    both be invoked, as long as the `@Test` method in the subclass does not override the
    `@Test` method in the superclass, which can occur if the superclass method is `private`
    or if the superclass method is package-private and resides in a different package than
    the subclass.
    *** The same applies to other types of test methods (`@TestFactory`,
      `@ParameterizedTest`, etc.) as well as lifecycle methods (`@BeforeAll`,
      `@AfterAll`, `@BeforeEach`, and `@AfterEach`).
* `MethodOrderer.Random` and `ClassOrderer.Random` now use the same default seed that is
  generated during class initialization (backported to 5.10.3).
* `TestInstancePostProcessor` extensions can now be registered via the `@ExtendWith`
  annotation on non-static fields.
* Methods and constructors invoked via `ExecutableInvoker` now use the same extensions as
  the context they are invoked from and the same `ExtensionContext` is passed to
  registered instances of `ParameterResolver`.
* The `org.junit.jupiter.api.extension.support` package is now exported from the
  `org.junit.jupiter.api` module

[[release-notes-5.11.0-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* The registration order of extensions was changed to allow non-static fields to be
  processed earlier. This change may affect extensions that rely on the order of
  registration.
* Kotlin support now depends on Kotlin API and language version 1.6; whereas, it
  previously depended on version 1.3.

[[release-notes-5.11.0-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* New `@FieldSource` annotation for use with `@ParameterizedTest` methods which allows
  you to source arguments from a local field or an external field referenced by
  fully qualified field name. This feature is similar to the existing `@MethodSource`
  feature. See the
  <<../user-guide/index.adoc#writing-tests-parameterized-tests-sources-FieldSource, User
  Guide>> for details.
* New `@AutoClose` annotation that can be applied to fields within tests to automatically
  close the annotated resource after test execution. See the
  <<../user-guide/index.adoc#writing-tests-built-in-extensions-AutoClose, User Guide>> for
  details.
* `JAVA_23` and `JAVA_24` have been added to the `JRE` enum for use with JRE-based
  execution conditions.
* New <<../user-guide/index.adoc#writing-tests-exceptions, Exception Handling>>
  documentation in the User Guide.
* Improved documentation for <<../user-guide/index.adoc#writing-tests-assumptions,
  Assumptions>> in the User Guide.
* Improved Javadoc for `assertThrows()` and `assertThrowsExactly()` to make it clear that
  the supplied message is not the _expected message_ of the thrown exception.
* Improved documentation for semantics of a disabled test regarding class-level lifecycle
  methods and callbacks.
* `@..Source` annotations for parameterized tests can now be used as repeatable
  annotations. See the
  <<../user-guide/index.adoc#writing-tests-parameterized-repeatable-sources, User Guide>>
  for details.
* New `argumentSet()` factory method for providing a custom name for an entire set of
  arguments for a `@ParameterizedTest`. See the
  <<../user-guide/index.adoc#writing-tests-parameterized-tests-display-names, User Guide>>
  for details.
* New `assertInstanceOf` methods added for Kotlin following up with similar Java
  `assertInstanceOf` methods introduced in `5.8` version.
* New generators in `DynamicTest` that take a `Stream`/`Iterator` of `Named<Executable>`
  along with a convenient `NamedExecutable` interface that can simplify writing dynamic
  tests, in particular in recent versions of Java that support records.
* `@TempDir` now suppresses `NoSuchFileException` when attempting to delete files that may
  have been already deleted by another thread or process.
* `@TempDir` now fails fast in case `TempDirFactory::createTempDirectory` returns
  `null`, a file, or a symbolic link to a file.
* `@TempDir` now fails fast in case the annotated target is of type `File` and
  `TempDirFactory::createTempDirectory` returns a `Path` that does not belong to the
  default file system.
* Allow potentially unlimited characters per column in `@CsvSource` and `@CsvFileSource`
  by specifying `maxCharsPerColumn = -1`.


[[release-notes-5.11.0-junit-vintage]]
=== JUnit Vintage

No changes.
