[[release-notes-5.8.0]]
== 5.8.0

*Date of Release:* September ❓, 2021

*Scope:*

* Declarative test suites via `@Suite` classes
* `LauncherSession` and accompanying listener
* New `UniqueIdTrackingListener`
* More fine-grained Java Flight Recorder events
* Java Flight Recorder support on Java 8 Update 262 or higher
* Test class ordering
* `@TempDir` can be used to create multiple temporary directories
* Extension registration via `@ExtendWith` on fields and parameters
* Auto-close support for arguments in `@ParameterizedTest` methods
* Memory and performance optimizations
* Numerous bug fixes and minor improvements

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/51?closed=1+[5.8 M1],
link:{junit5-repo}+/milestone/55?closed=1+[5.8 RC1], and
link:{junit5-repo}+/milestone/57?closed=1+[5.8 GA] milestone pages in the JUnit repository
on GitHub.


[[release-notes-5.8.0-overall-improvements]]
=== Overall Improvements

==== Deprecations and Breaking Changes

* Since the API Guardian dependency is no longer exported as a runtime but as a
  compile-only dependency to consuming Gradle projects, Gradle builds that define their own
  https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:what-are-dependency-configurations[dependency configurations]
  may be affected. For example, if the custom configuration is used to manipulate a source
  set's classpath directly, dependency attributes needed for Gradle's variant-aware
  dependency management are dropped and API Guardian is missing from the compile
  classpath. In that case, the Java compiler emits warnings which -- depending on your
  configured options -- may cause the build to fail. The solution is to avoid manipulating
  a source set's classpath directly. Instead, its dependency configurations should extend
  from your custom configuration. An example of such a change can be seen in
  https://github.com/spring-projects/spring-framework/commit/d23afea168b8360d08bf296ac2189239ab9db7fc[this commit]
  to the Spring Framework repository.

==== New Features and Improvements

* The API Guardian dependency is now exported as a compile-only dependency for consuming
  Gradle projects and no longer required at runtime when running on the module path.
* Logging messages are no longer issued at `INFO` level in order to lower the "textual
  noise" on the console when Java's Util Logging is used in its default configuration.


[[release-notes-5.8.0-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Classes explicitly selected via `@SelectClasses` are now always included in the test
  suite. This applies to `@Suite` classes running via the `SuiteTestEngine` and suite
  classes running via the `JUnitPlatform` `Runner`.
* `SummaryGeneratingListener` is now thread-safe and can handle concurrently failing tests.

==== Deprecations and Breaking Changes

* The `JUnitPlatform` runner has been deprecated in favor of the new `@Suite` support. See
  the warning in <<../user-guide/index.adoc#running-tests-junit-platform-runner, Using
  JUnit 4 to run the JUnit Platform>> for details.
* For consistency with the rest of the JUnit Platform, the experimental
  `LauncherDiscoveryListener` is now an interface instead of an abstract class.

==== New Features and Improvements

* New `junit-platform-suite-engine` module to execute declarative test suites on the JUnit
  Platform.
* Additional selectors in the suite API in the `junit-platform-suite-api` module.
* New `UniqueIdTrackingListener` which is a `TestExecutionListener` that tracks the unique
  IDs of all tests that were skipped or executed during the `TestPlan` and generates a
  file containing the unique IDs. The generated file can be used to rerun those tests --
  for example, in order to run the same set of tests executed on the JVM subsequently
  within a GraalVM native image. See the Javadoc for `{UniqueIdTrackingListener}` for
  details.
* New `findAnnotation(Class,Class,SearchOption)` method in `AnnotationSupport` that
  performs the same search algorithm as `findAnnotation(AnnotatedElement,Class)` but also
  searches the enclosing class hierarchy for inner classes if the
  `INCLUDE_ENCLOSING_CLASSES` `SearchOption` is specified. This new method can be used by
  extension authors to find annotations on enclosing classes for JUnit Jupiter `@Nested`
  test classes.
* New `test(Condition<Event>)` and `nestedContainer(Class<?>, Condition<Event>)` methods
  in `EventConditions` that allow you to provide conditions for matching against test and
  nested container events when using the `EngineTestKit`. For example,
  `test(displayName("my test"))` can be used to match against a test whose display name is
  `my test`.
* Generating Java Flight Recorder events via the `junit-platform-jfr` module is now also
  supported on Java 8 Update 262 or higher, in addition to Java 11 or later. See
  <<../user-guide/index.adoc#running-tests, Flight Recorder Support>> for details.
* The `junit-platform-jfr` module now reports execution events for containers -- for
  example, test classes.
* The `junit-platform-jfr` module now reports test discovery events for the launcher and
  registered test engines.
* New `ClassSource.from(URI)` static factory method for creating a `ClassSource` from a
  URI using the `class` scheme and optional query parameters specifying the line number
  and column number. This is analogous to the existing `ClasspathResourceSource.from(URI)`
  factory method.
* New `getConfigurationParameters()` method in the `TestPlan` which allows a
  `TestExecutionListener` to access
  <<../user-guide/index.adoc#running-tests-config-params, configuration parameters>>. See
  <<../user-guide/index.adoc#launcher-api-listeners-config, Configuring an Execution
  Listener>> for details.
* Custom `LauncherDiscoveryListener` implementations can now be registered via Java’s
  `{ServiceLoader}` mechanism.
* Documented constant value of `ExclusiveResource.GLOBAL_KEY`.
* Instances of `TestIdentifier` and `UniqueId` now retain less memory because they no
  longer store `String` representations of unique IDs.
* Tools that make multiple calls to the `Launcher` API should now create a
  `LauncherSession` in order to allow for executing global setup and teardown code exactly
  once via the new `LauncherSessionListener` interface that can be registered via Java’s
  `{ServiceLoader}` mechanism.


[[release-notes-5.8.0-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `@DisplayNameGeneration` and `@IndicativeSentencesGeneration` are now only inherited
  from enclosing classes if the current class is a `@Nested` test class.
* The `IndicativeSentences` `DisplayNameGenerator` no longer includes the display name of
  the enclosing class when generating an _indicative sentence_ if the enclosing class is
  not configured to use the `IndicativeSentences` display name generator as well.
* The `TypedArgumentConverter` base class now supports the conversion of a `null` source
  value in parameterized tests.
* The `TypedArgumentConverter` base class now supports conversion to a primitive type if
  the configured target type is a wrapper for the target primitive type, including
  primitive widening support -- for example, from `Integer` to `int` or `long`.
* Exceptions thrown from instances of `CloseableResource` no longer hide test failures but
  are instead reported as suppressed exceptions.

==== Deprecations and Breaking Changes

* The new `autoCloseArguments` feature in `@ParameterizedTest` may potentially be a
  breaking change for existing parameterized test methods if an argument that implements
  `java.lang.AutoCloseable` is reused for multiple invocations of the same parameterized
  test method. If your parameterized test methods start to fail when you upgrade to JUnit
  Jupiter 5.8, you can disable this feature by declaring
  `@ParameterizedTest(autoCloseArguments = false)`.
* `InvocationInterceptor.interceptDynamicTest(Invocation<Void>, ExtensionContext)` has
  been deprecated in favor of
  `InvocationInterceptor.interceptDynamicTest(Invocation<Void>, DynamicTestInvocationContext, ExtensionContext)`
  that provides access to the dynamic test executable via
  `DynamicTestInvocationContext.getExecutable()`.

==== New Features and Improvements

* Test classes can now be ordered _globally_ by supplying the fully-qualified name of a
  class implementing the `ClassOrderer` API as the value of the new
  `junit.jupiter.testclass.order.default` configuration parameter.
* `@Nested` test classes can be ordered _locally_ via the new `@TestClassOrder` annotation
  in which a `ClassOrderer` can be specified.
* `@ExtendWith` may now be used to register extensions declaratively via fields or
  parameters in test class constructors, test methods, and lifecycle methods. See
  <<../user-guide/index.adoc#extensions-registration-declarative, Declarative Extension
  Registration>> for details.
* `@RegisterExtension` fields may now be `private`.
* New `assertThrowsExactly()` method in `Assertions` which is a more strict version of
  `assertThrows()` that allows you to assert that the exception thrown is of the exact
  type specified.
* `assertDoesNotThrow()` in `Assertions` now supports suspending functions when called
  from Kotlin.
* New `assertInstanceOf()` methods which produce better error messages comparable to those
  produced by `assertThrows`. These new methods serve as a replacement for
  `assertTrue(obj instanceof X)`.
* `assertNull()` failure messages now include the actual object's type if the `toString()`
  implementation for the actual object returns `null` or `"null"`. This avoids the
  generation of confusing failure messages such as `expected <null> but was <null>`.
* `@TempDir` can now be used to create multiple temporary directories. Instead of creating
  a single temporary directory per context (i.e. test class or method) every declaration
  of the `@TempDir` annotation on a field or method parameter now results in a separate
  temporary directory. To revert to the old behavior of using a single temporary directory
  for the entire test class or method (depending on which level the annotation is used),
  you can set the `junit.jupiter.tempdir.scope` configuration parameter to `per_context`.
* `@TempDir` cleanup resets readable and executable permissions of the root temporary
  directory and any contained directories instead of failing to delete them.
* `@TempDir` fields may now be `private`.
* `DynamicTests.stream()` can now consume `Named` input and will use each name-value pair
  as the display name and value for each generated dynamic test (see
  <<../user-guide/index.adoc#writing-tests-dynamic-tests-examples,User Guide>> for details).
* New `class` URI scheme for dynamic test sources. This allows tests to be located using
  the information available in a `StackTraceElement`.
* Dynamic tests now require less memory thanks to a number of improvements to internal
  data structures.
* New `autoCloseArguments` attribute in `@ParameterizedTest` to close
  `java.lang.AutoCloseable` arguments after each invocation of the parameterized test
  method. This attribute defaults to `true`.
* Numeric literals used with `@CsvSource` or `CsvFileSource` can now be expressed using
  underscores as in some JVM languages, to improve readability of long numbers like
  `700_000_000`.
* CSV rows provided via `@CsvSource` may now start with a number sign (`#`).
* New `ignoreLeadingAndTrailingWhitespace` attributes in `@CsvSource` and `@CsvFileSource`
  (set to `true` by default) to control whether or not to trim whitespace.
* In parameterized tests using `@MethodSource` or `@ArgumentSource`, arguments can now have
  optional names (supplied via the new `Named` API). When the argument is included in the
  display name of an invocation, this name will be used instead of the value.
* Documented constant values in `org.junit.jupiter.api.parallel.Resources`.


[[release-notes-5.8.0-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* If multiple exceptions are registered as failures for a JUnit 4 based test -- for
  example, if the `ErrorCollector` rule throws an
  `org.junit.runners.model.MultipleFailureException` -- all of those failures are now
  added as _suppressed exceptions_ in the `org.opentest4j.MultipleFailuresError` created
  by the `VintageTestEngine`. This allows users to analyze the stack trace of each failure
  when such a test fails.

==== New Features and Improvements

* The JUnit Vintage engine now requires less memory and allows for earlier garbage
  collection thanks to a number of improvements to internal data structures.
