[[release-notes-5.10.0-M1]]
== 5.10.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/65?closed=1+[5.10.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.10.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* All utility methods from `ReflectionSupport` now have counterparts returning `Stream`
  instead of `List`.
* For consistency with Jupiter lifecycle callbacks, listener method pairs for started/
  finished and opened/closed events are now called using "wrap" semantics, i.e. the latter
  methods are called in reverse order compared to the former when multiple listeners are
  registered. This affects the following listener interfaces: `TestExecutionListener`,
  `EngineExecutionListener`, `LauncherDiscoveryListener`, and `LauncherSessionListener`.

[[release-notes-5.10.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `ArgumentsAccessor.getInvocationIndex()` method that supplies the index of a
  `@ParameterizedTest` invocation.
* `DisplayNameGenerator` methods are now allowed to return `null`, in order to signal
  to fall back to the default display name generator.


[[release-notes-5.10.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
