[[release-notes-5.9.1]]
== 5.9.1

*Date of Release:* September 20, 2022

*Scope:*

* New `@EnabledInNativeImage` and `@DisabledInNativeImage` annotations for testing in
  GraalVM native images.
* Minor bug fixes and enhancements since 5.9.0

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/63?closed=1+[5.9.1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.9.1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* `ReflectionSupport.findMethods(...)` now returns a distinct set of methods.
* Execution in GraalVM native images no longer requires `--initialize-at-build-time` for
  `OpenTestReportGeneratingListener`.


[[release-notes-5.9.1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Headers provided via the `value` attribute in `@CsvSource` for a `@ParameterizedTest`
  are now properly parsed when the `useHeadersInDisplayName` attribute is set to `true`.
* A `@ParameterizedTest` method configured with a `@MethodSource` annotation that
  references a factory method inherited from multiple interfaces no longer fails with an
  exception stating that multiple factory methods with the same name were found.
* A `@ParameterizedTest` method configured with a `@MethodSource` annotation that
  references a factory method whose name is the same as other non-factory methods in the
  same class no longer fails with an exception stating that multiple factory methods with
  the same name were found.
* Assertion failures thrown from methods with applied timeouts using `ThreadMode.SEPARATE`
  are now properly reported.

==== New Features and Improvements

* New `@EnabledInNativeImage` and `@DisabledInNativeImage` annotations for enabling and
  disabling tests within a GraalVM native image.


[[release-notes-5.9.1-junit-vintage]]
=== JUnit Vintage

No changes.
