[[release-notes-5.13.3]]
== 5.13.3

*Date of Release:* July 4, 2025

*Scope:* Bug fixes and enhancements since 5.13.2

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit-framework-repo}+/milestone/100?closed=1+[5.13.3] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.13.3-overall-improvements]]
=== Overall Changes

[[release-notes-5.13.3-overall-new-features-and-improvements]]
==== New Features and Improvements

* All _experimental_ APIs have been promoted to _maintained_ to indicate that they won't
  be removed in any future 5.x release.


[[release-notes-5.13.3-junit-platform]]
=== JUnit Platform

No changes.


[[release-notes-5.13.3-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.13.3-junit-jupiter-bug-fixes]]
==== Bug Fixes

* Fix regression that caused top-level and static member classes annotated with `@Nested`
  to no longer be executed because they caused a discovery issue to be reported.
* Stop reporting discovery issues for composed annotation classes that are meta-annotated
  with `@Nested`.
* Stop reporting discovery issues for `DefaultImpls` classes generated by the Kotlin
  compiler for interfaces with non-abstract test methods.
* When a `customReason` is supplied along with a `null` value for the default `reason` to
  `ConditionEvaluationResult.disabled(String, String)`, the resulting reason is now
  `"my&nbsp;custom&nbsp;reason"` instead of
  `"null&nbsp;++==>++&nbsp;my&nbsp;custom&nbsp;reason"`.

[[release-notes-5.13.3-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* A _blank_ reason supplied to a `ConditionEvaluationResult` factory method is now treated
  the same as a `null` reason, resulting in an _empty_ `Optional` returned from
  `ConditionEvaluationResult.getReason()`.
* The Javadoc for factory methods in `ConditionEvaluationResult` now explicitly states
  that both `null` and _blank_ values are supported for reason strings and that such
  values will result in an _empty_ `Optional` returned from
  `ConditionEvaluationResult.getReason()`.
* Improve message of discovery issues reported for ineffective `@Order` annotations.


[[release-notes-5.13.3-junit-vintage]]
=== JUnit Vintage

No changes.
