[[release-notes-5.4.0-M1]]
== 5.4.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult
the link:{junit5-repo}+/milestone/29?closed=1+[5.4.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.4.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* The JUnit Platform Surefire Provider (`junit-platform-surefire-provider`) has been
  discontinued and is no longer released as part of JUnit 5. Please use Maven Surefire’s
  native support for running tests on the JUnit Platform instead (requires Maven Surefire
  2.22.0 or higher).

==== New Features and Improvements

* JUnit 4's `AssumptionViolatedException` is now supported in JUnit Jupiter for aborting
  a test mid-flight due to a failed assumption -- for example, via JUnit 4's
  `org.junit.Assume` utility class.
* In addition to returning streams, `@TestFactory`-annotated methods may now return a
  single `DynamicNode` -- for example, a `DynamicTest` or a `DynamicContainer`.
* New `DisplayNameGenerator` interface and `@DisplayNameGeneration` annotation that allow
  declarative configuration of a pre-defined or custom display name generator.


[[release-notes-5.4.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `Assertions.assertAll()` is now thread-safe -- for example, it can now be used with a
  _parallel_ `Stream`.
* The `OS.SOLARIS` enum constant used with `@EnabledOnOs` and `@DisabledOnOs` is now also
  detected as the current operating system if the `os.name` JVM system property contains
  `"SunOs"`.
* `Assertions.assertEquals()` variants that compare floating point numbers using a delta
  now support a _delta_ of zero.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `Assertions.assertNotEquals()` variants that accept the following primitive data
  types: `char`, `byte`, `short`, `int`, `long`, `float`, and `double`.
* Implicit conversion from hexadecimal and octal string representations to integral types
  in `@ParameterizedTest` arguments -- for example, conversion from `"0xff"` to `255`.
* JUnit 4's `@Ignore` annotation is now supported for disabling test classes and test
  methods via the `junit-jupiter-migrationsupport` module.
  - See the <<../user-guide/index.adoc#migrating-from-junit4-ignore-annotation-support,
    User Guide>> for details.


[[release-notes-5.4.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
