[[release-notes-5.10.2]]
== 5.10.2

*Date of Release:* ❓

*Scope:* minor bug fixes and changes since 5.10.1.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/73?closed=1+[5.10.2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.10.2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* The `junit-platform-launcher` may now be used as a Java module when
  `junit.platform.launcher.interceptors.enabled` is set to `true`.
  - See issue link:https://github.com/junit-team/junit5/issues/3561[#3561] for details.

==== Deprecations and Breaking Changes

* Field predicates are no longer applied eagerly while searching the type hierarchy. This
  reverts changes made in 5.10.1 that affected `findFields(...)` and `streamFields(...)`
  in `ReflectionSupport` as well as `findAnnotatedFields(...)` and
  `findAnnotatedFieldValues(...)` in `AnnotationSupport`.
  - See issues link:https://github.com/junit-team/junit5/issues/3638[#3638] and
    link:https://github.com/junit-team/junit5/issues/3553[#3553] for details.


[[release-notes-5.10.2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* A package-private static field annotated with `@TempDir` is once again _shadowed_ by a
  non-static field annotated with `@TempDir` when the non-static field resides in a
  different package and has the same name as the static field. This reverts changes made
  in 5.10.1.
  - See issues link:https://github.com/junit-team/junit5/issues/3638[#3638] and
    link:https://github.com/junit-team/junit5/issues/3553[#3553] for details.


[[release-notes-5.10.2-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓
