[[release-notes-5.13.0-M3]]
== 5.13.0-M3

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/93?closed=1+[5.13.0-M3] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.13.0-M3-junit-platform]]
=== JUnit Platform

[[release-notes-5.13.0-M3-junit-platform-bug-fixes]]
==== Bug Fixes

* Reintroduce support for JVM shutdown hooks when using the `-cp`/`--classpath` option of
  the `ConsoleLauncher`. Prior to this release, the created class loader was closed prior
  to JVM shutdown hooks being invoked, which caused hooks to fail with a
  `ClassNotFoundException` when loading classes during shutdown.

[[release-notes-5.13.0-M3-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M3-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* Introduce resource management mechanism that allows preparing and sharing state across
  executions or test engines via stores that are scoped to a `LauncherSession` or
  `ExecutionRequest`. The Jupiter API uses these stores as ancestors to the `Store`
  instances accessible via `ExtensionContext` and provides a new method to access them
  directly. Please refer to the User Guide for examples of managing
  <<../user-guide/index.adoc#launcher-api-launcher-session-listeners-tool-example-usage, session-scoped>>
  and
  <<../user-guide/index.adoc#launcher-api-managing-state-across-test-engines, request-scoped>>
  resources.
* Introduce a mechanism for `TestEngine` implementations to report issues encountered
  during test discovery. If an engine reports a `DiscoveryIssue` with a `Severity` equal
  to or higher than a configurable critical severity, its tests will not be executed.
  Instead, the engine will be reported as failed during execution with a failure message
  listing all critical issues. Non-critical issues will be logged but will not prevent the
  engine from executing its tests. The critical severity can be configured via a new
  configuration parameter and, currently, defaults to `ERROR`. Please refer to the
  <<../user-guide/index.adoc#running-tests-discovery-issues, User Guide>> for details.
+
If you're a test engine maintainer, please see the
<<../user-guide/index.adoc#test-engines-discovery-issues, User Guide>> for details on how
to start reporting discovery issues.
* Start reporting discovery issues for problematic `@Suite` classes:
  - Invalid `@Suite` class declarations (for example, when `private`)
  - Invalid `@BeforeSuite`/`@AfterSuite` method declarations (for example, when not
    `static`)
  - Cyclic dependencies between `@Suite` classes


[[release-notes-5.13.0-M3-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.13.0-M3-junit-jupiter-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M3-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M3-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Start reporting discovery issues for potentially problematic test classes:
    - Invalid `@Test` and `@TestTemplate` method declarations (for example, when return
      type is not `void`)
    - Invalid `@TestFactory` methods (for example, when return type is invalid)
    - Multiple method-level annotations (for example, `@Test` and `@TestTemplate`)
    - Invalid test class and `@Nested` class declarations (for example, `static` `@Nested`
      classes)
    - Potentially missing `@Nested` annotations (for example, non-abstract inner classes
      that contain test methods)
    - Invalid lifecycle method declarations (for example, when `private`)
    - Invalid `@Tag` syntax
    - Blank `@DisplayName` declarations
    - Blank `@SentenceFragment` declarations
    - `@BeforeParameterizedClassInvocation` and `@AfterParameterizedClassInvocation`
      methods declared in non-parameterized test classes


[[release-notes-5.13.0-M3-junit-vintage]]
=== JUnit Vintage

[[release-notes-5.13.0-M3-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-5.13.0-M3-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-5.13.0-M3-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
