[[release-notes-5.4.0-M1]]
== 5.4.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult
the link:{junit5-repo}+/milestone/29?closed=1+[5.4.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.4.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* The JUnit Platform Surefire Provider (`junit-platform-surefire-provider`) has been
  discontinued and is no longer released as part of JUnit 5. Please use Maven Surefire’s
  native support for running tests on the JUnit Platform instead (requires Maven Surefire
  2.22.0 or higher).

==== New Features and Improvements

* New `junit-platform-reporting` artifact containing the `XmlReportsWritingListener` that
  generates a XML report in format compatible with the de facto standard for JUnit 4
  based test reports that was made popular by the Ant build system.
* New `ModifierSupport` class providing an API for extension and test engine authors to
  inspect modifiers of classes and members.
  - See the <<../user-guide/index.adoc#extensions-supported-utilities-modifier, User
    Guide>> for details.
* Exceptions reported due to failed reflective operations such as loading a class, reading
  a field's value, or looking up a method by name now include the original exception as
  their cause to make it easier to debug underlying issues.


[[release-notes-5.4.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `Assertions.assertAll()` is now thread-safe -- for example, it can now be used with a
  _parallel_ `Stream`.
* Exceptions thrown in `Assertions.assertAll()` are now additionally tracked as
  _suppressed exceptions_ in the resulting `MultipleFailuresError`. Consequently, the
  stack traces for such exceptions are now visible as _Suppressed_ at the end of the
  stack trace for the invocation of `assertAll()`.
* New `JRE.JAVA_12` enum constant for use with `@EnabledOnJre` and `@DisabledOnJre`.
* The `OS.SOLARIS` enum constant used with `@EnabledOnOs` and `@DisabledOnOs` is now also
  detected as the current operating system if the `os.name` JVM system property contains
  `"SunOs"`.
* `Assertions.assertEquals()` variants that compare floating point numbers using a delta
  now support a _delta_ of zero.
* `Assertions.assertLinesMatch()` no longer throws a `NullPointerException` after
  evaluating a fast-forward match if there are more expected lines after the fast-forward
  match than remain in the actual results. This bug only manifested itself if the
  expected list size was equal to or greater than the actual list size.
* Threads created for running tests in parallel now use the same thread context class
  loader (_TCCL_) that was set when creating the underlying executor service. This
  resolves `ClassNotFoundException` issues that only occur in parallel execution mode
  when a custom _TCCL_ is in place.
* When executing tests in parallel, lifecycle methods and callbacks called after a
  `@TestFactory` method are now always executed after the dynamic tests returned by the
  method.
* Exceptions thrown during initialization of static `@RegisterExtension` fields now cause
  the test class to fail instead of being silently swallowed.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* New `Assertions.assertEquals()` variants that accept mixed boxed and unboxed primitive
  values, allowing statements such as `assertEquals(42, Integer.valueOf("42"))` to
  compile.
* New `Assertions.assertNotEquals()` variants that accept the following primitive data
  types: `char`, `byte`, `short`, `int`, `long`, `float`, and `double`. Mixed boxed and
  unboxed primitive values are also supported.
* JUnit 4's `AssumptionViolatedException` is now supported in JUnit Jupiter for aborting
  a test mid-flight due to a failed assumption -- for example, via JUnit 4's
  `org.junit.Assume` utility class.
* In addition to returning streams, `@TestFactory`-annotated methods may now return a
  single `DynamicNode` -- for example, a `DynamicTest` or a `DynamicContainer`.
* Implicit conversion from hexadecimal and octal string representations to integral types
  in `@ParameterizedTest` arguments -- for example, conversion from `"0xff"` to `255`.
* New `LOCALE` and `TIME_ZONE` constants in `org.junit.jupiter.api.parallel.Resources`
  for use with `@ResourceLock` to synchronize test execution regarding the default
  `Locale` and default `TimeZone`, respectively.
* New `MethodOrderer` API for ordering the sequence of tests with built-in support for
  _alphanumeric_, `@Order` annotation based, and _random_ ordering of test methods.
  - See <<../user-guide/index.adoc#writing-tests-test-execution-order, Test Execution
    Order>> in the User Guide for details.
* New `DisplayNameGenerator` interface and `@DisplayNameGeneration` annotation that allow
  declarative configuration of a pre-defined or custom display name generator.
* JUnit 4's `@Ignore` annotation is now supported for disabling test classes and test
  methods via the `junit-jupiter-migrationsupport` module.
  - See the <<../user-guide/index.adoc#migrating-from-junit4-ignore-annotation-support,
    User Guide>> for details.


[[release-notes-5.4.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
