[[release-notes-5.2.0]]
== 5.2.0

*Date of Release:* April 29, 2018

*Scope:* JUnit BOM, support for Maven Surefire 2.21.0 allowing builds with Java 9 and
Java 10, _argument aggregation_ and _widening primitive conversion_ for arguments in
parameterized tests, external factory methods for `@MethodSource`, as well as various
minor improvements and bug fixes.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/22?closed=1+[5.2 M1],
link:{junit5-repo}+/milestone/25?closed=1+[5.2 RC1], and
link:{junit5-repo}+/milestone/26?closed=1+[5.2 GA] milestone pages in the JUnit repository
on GitHub.


[[release-notes-5.2.0-overall-improvements]]
=== Overall Improvements

* JUnit BOM: To ease dependency management using
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies[Maven]
or https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import[Gradle],
a _Bill of Materials_ POM is now provided under the `org.junit:junit-bom:5.2.0` Maven
coordinates.


[[release-notes-5.2.0-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Tag expressions containing spaces are now supported in the JUnit Platform Maven
  Surefire provider.
* Duplicate `--config` keys supplied to the `ConsoleLauncher` are now reported properly.
* Exceptions thrown in `Node.after()` (in the `HierarchicalTestEngine` infrastructure) no
  longer mask earlier exceptions.

==== New Features and Improvements

* The JUnit Platform Surefire Provider (`junit-platform-surefire-provider`) now works
  with and requires Surefire `2.21.0` which allows it to be used with Java 9 and Java 10.
* The default _include pattern_ for filtering class names now matches test classes whose
  names either start with `Test` or end with `Test` or `Tests`.
  - This pattern is used by the `ConsoleLauncher`, the JUnit Platform Gradle Plugin, and
    the `JUnitPlatform` runner.


[[release-notes-5.2.0-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Exceptions thrown by an `AfterAllCallback` no longer mask exceptions thrown at the
  class level when using the `@TestInstance(PER_CLASS)` lifecycle mode.

==== New Features and Improvements

* New `assertDoesNotThrow()` methods in `Assertions` which assert that the execution of
  a given code block does _not_ throw any kind of exception.
* New `fail()` method in `Assertions` makes it possible to fail a test without an
  explicit failure message.
* Implicit support for _widening primitive conversion_ for an argument supplied to a
  `@ParameterizedTest`.
  - For example, a parameterized test annotated with `@ValueSource(ints = { 1, 2, 3 })`
    can be declared to accept an argument of type `int`, `long`, `float`, or `double`.
* `@MethodSource` now supports `static` factory methods declared in external classes
  referenced by _fully qualified method name_.
* Support for aggregation of multiple `@ParameterizedTest` arguments into a single object.
  - For details, see
    <<../user-guide/index.adoc#writing-tests-parameterized-tests-argument-aggregation,
    Argument Aggregation>>.


[[release-notes-5.2.0-junit-vintage]]
=== JUnit Vintage

No changes.
