[[release-notes-5.11.1]]
== 5.11.1

*Date of Release:* September 25, 2024

*Scope:* Bug fixes and enhancements since 5.11.0

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/80?closed=1+[5.11.1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.11.1-junit-platform]]
=== JUnit Platform

[[release-notes-5.11.1-junit-platform-bug-fixes]]
==== Bug Fixes

* Fix support for disabling ANSI colors on the console when the `NO_COLOR` environment
  variable is available.
* `NamespacedHierarchicalStore` no longer throws an exception after it has been closed if
  the store is queried via one of the `get(...)` or `getOrComputeIfAbsent(...)` methods;
  however, if a `getOrComputeIfAbsent(...)` invocation results in the computation of a new
  value, an exception will still be thrown.
* Fixed potential locking issue with `ExclusiveResource` in the
  `HierarchicalTestExecutorService`, which could lead to deadlocks in certain scenarios.

[[release-notes-5.11.1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* Improve parallelism and reduce number of blocked threads used by
  `HierarchicalTestEngine` implementations when parallel execution is enabled and the
  global read-write lock is used.


[[release-notes-5.11.1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-5.11.1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* `TestWatcher` callback methods can once again access data in the
  `ExtensionContext.Store`.

[[release-notes-5.11.1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Improve parallelism and reduce number of blocked threads in the presence of `@Isolated`
  tests when parallel execution is enabled


[[release-notes-5.11.1-junit-vintage]]
=== JUnit Vintage

No changes.
