[[release-notes-5.4.0-M1]]
== 5.4.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult
the link:{junit5-repo}+/milestone/29?closed=1+[5.4.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-5.4.0-M1-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.4.0-M1-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `Assertions.assertAll()` is now thread-safe, i.e. it can be used with _parallel_ `Streams`.
* `OS.SOLARIS` is now also detected for when `os.name` reports `SunOs`.
* `Assertions.assertLinesMatch()` no longer throws a `NullPointerException` after
  evaluating a fast-forward match if there are more expected lines after the fast-forward
  match than remain in the actual results. This bug only manifested itself if the
  expected list size was equal to or greater than the actual list size.
* Threads created for running tests in parallel now use the same thread context
  class loader (_TCCL_) that was set when creating the underlying executor service.
  This resolves `ClassNotFoundException` issues that only occur in parallel execution
  mode and a custom thread context class loader is in place.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.4.0-M1-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
