[[release-notes-5.10.4]]
== 5.10.4

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/79?closed=1+[5.10.4] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.10.4-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Fixed potential locking issue with `ExclusiveResource` in the
  `HierarchicalTestExecutorService`, which could lead to deadlocks in certain scenarios.
* Fix support for disabling ANSI colors on the console when the `NO_COLOR` environment
  variable is available.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* Improve parallelism and reduce number of blocked threads used by
  `HierarchicalTestEngine` implementations when parallel execution is enabled and the
  global read-write lock is used.


[[release-notes-5.10.4-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* Improve parallelism and reduce number of blocked threads in the presence of `@Isolated`
  tests when parallel execution is enabled


[[release-notes-5.10.4-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
