[[release-notes-5.7.0]]
== 5.7.0

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult
the link:{junit5-repo}+/milestone/50?closed=1+[5.7.0] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.7.0-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* The `@Testable` annotation may now target any element type, including fields, methods,
  classes, packages, and modules.


[[release-notes-5.7.0-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* `CloseableResource` instances stored in `ExtensionContext.Store` are now closed in the
  reverse order they were added in. Previously, the order was undefined and unstable.

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓


[[release-notes-5.7.0-junit-vintage]]
=== JUnit Vintage

==== Bug Fixes

* ❓

==== Deprecations and Breaking Changes

* ❓

==== New Features and Improvements

* ❓
