name: Main build
description: Sets up JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: :platform-tooling-support-tests:test build --configuration-cache
  encryptionKey:
    required: true
    description: Gradle cache encryption key
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-test-jdk
    - uses: ./.github/actions/run-gradle
      with:
        arguments: ${{ inputs.arguments }}
        encryptionKey: ${{ inputs.encryptionKey }}
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
      if: ${{ always() }}
      with:
        name: Open Test Reports (${{ github.job.name }})
        path: '**/build/reports/open-test-report.html'
