[[extensions]]
== Extension Model

[[extensions-overview]]
=== Overview

In contrast to the competing `Runner`, `@Rule`, and `@ClassRule` extension points in
JUnit 4, the JUnit Jupiter extension model consists of a single, coherent concept: the
`Extension` API. Note, however, that `Extension` itself is just a marker interface.

[[extensions-registration]]
=== Registering Extensions

Extensions can be registered declaratively via `{ExtendWith}`.

[[extensions-registration-declarative]]
==== Declarative Extension Registration

Developers can register one or more extensions _declaratively_ by annotating a test
class, test method, or custom _<<writing-tests-meta-annotations,composed annotation>>_
with `@ExtendWith(...)` and supplying class references for the extensions to register.

For example, to register a custom `MockitoExtension` for a particular test method, you
would annotate the test method as follows.

[source,java,indent=0]
[subs="verbatim"]
----
@ExtendWith(MockitoExtension.class)
@Test
void mockTest() {
	// ...
}
----

To register a custom `MockitoExtension` for all tests in a particular class and its
subclasses, you would annotate the test class as follows.

[source,java,indent=0]
[subs="verbatim"]
----
@ExtendWith(MockitoExtension.class)
class MockTests {
	// ...
}
----

Multiple extensions can be registered together like this:

[source,java,indent=0]
[subs="verbatim"]
----
@ExtendWith({ FooExtension.class, BarExtension.class })
class MyTestsV1 {
	// ...
}
----

As an alternative, multiple extensions can be registered separately like this:

[source,java,indent=0]
[subs="verbatim"]
----
@ExtendWith(FooExtension.class)
@ExtendWith(BarExtension.class)
class MyTestsV2 {
	// ...
}
----

The execution of tests in both `MyTestsV1` and `MyTestsV2` will be extended by the
`FooExtension` and `BarExtension`, in exactly that order.

[[extensions-registration-inheritance]]
==== Extension Inheritance

Registered extensions are inherited within test class hierarchies with top-down
semantics. Similarly, extensions registered at the class-level are inherited at the
method-level. Furthermore, a specific extension implementation can only be registered
once for a given extension context and its parent contexts. Consequently, any attempt to
register a duplicate extension implementation will be ignored.

[[extensions-conditions]]
=== Conditional Test Execution

`{ContainerExecutionCondition}` and `{TestExecutionCondition}` define the `Extension`
APIs for programmatic, _conditional test execution_.

A `ContainerExecutionCondition` is _evaluated_ to determine if all tests in a given
container (e.g., a test class) should be executed based on the supplied
`ContainerExtensionContext`. Similarly, a `TestExecutionCondition` is _evaluated_ to
determine if a given test method should be executed based on the supplied
`TestExtensionContext`.

When multiple `ContainerExecutionCondition` or `TestExecutionCondition` extensions are registered,
a container or test, respectively, is disabled as soon as one of the conditions returns _disabled_.
Thus, there is no guarantee that a condition is evaluated because another extension might
have already caused a container or test to be disabled. In other words, the evaluation works like
the short-circuiting boolean OR operator.

See the source code of `{DisabledCondition}` and `{Disabled}` for concrete examples.

[[extensions-conditions-deactivation]]
==== Deactivating Conditions

Sometimes it can be useful to run a test suite _without_ certain conditions being active.
For example, you may wish to run tests even if they are annotated with `@Disabled` in
order to see if they are still _broken_. To do this, simply provide a pattern for the
`junit.conditions.deactivate` configuration key to specify which conditions should be
deactivated (i.e., not evaluated) for the current test run. The pattern can be supplied
as a JVM system property or as a _configuration parameter_ in the `LauncherDiscoveryRequest`
that is passed to the `Launcher`.

For example, to deactivate JUnit's `@Disabled` condition, you can start your JVM with
the following system property.

`-Djunit.conditions.deactivate=org.junit.*DisabledCondition`

[[extensions-conditions-deactivation-patterns]]
===== Pattern Matching Syntax

If the `junit.conditions.deactivate` pattern consists solely of an asterisk (`+*+`), all
conditions will be deactivated. Otherwise, the pattern will be used to match against the
fully qualified class name (_FQCN_) of each registered condition. Any dot (`.`) in the
pattern will match against a dot (`.`) or a dollar sign (`$`) in the FQCN. Any asterisk
(`+*+`) will match against one or more characters in the FQCN. All other characters in the
pattern will be matched one-to-one against the FQCN.

Examples:

- `+*+`: deactivates all conditions.
- `+org.junit.*+`: deactivates every condition under the `org.junit` base package and any
  of its subpackages.
- `+*.MyCondition+`: deactivates every condition whose simple class name is exactly
  `MyCondition`.
- `+*System*+`: deactivates every condition whose simple class name contains `System`.
- `org.example.MyCondition`: deactivates the condition whose FQCN is exactly
  `org.example.MyCondition`.

[[extensions-test-instance-post-processing]]
=== Test Instance Post-processing

`{TestInstancePostProcessor}` defines the API for `Extensions` that wish to _post
process_ test instances.

Common use cases include injecting dependencies into the test instance, invoking custom
initialization methods on the test instance, etc.

For concrete examples, consult the source code for the `{MockitoExtension}` and the
`{SpringExtension}`.

[[extensions-parameter-resolution]]
=== Parameter Resolution

`{ParameterResolver}` defines the `Extension` API for dynamically resolving parameters at
runtime.

If a test constructor or a `@Test`, `@TestFactory`, `@BeforeEach`, `@AfterEach`,
`@BeforeAll`, or `@AfterAll` method accepts a parameter, the parameter must be _resolved_
at runtime by a `ParameterResolver`. A `ParameterResolver` can either be built-in (see
`{TestInfoParameterResolver}`) or <<extensions-registration,registered by the user>>.
Generally speaking, parameters may be resolved by _name_, _type_, _annotation_, or any
combination thereof. For concrete examples, consult the source code for
`{CustomTypeParameterResolver}` and `{CustomAnnotationParameterResolver}`.

[[extensions-lifecycle-callbacks]]
=== Test Lifecycle Callbacks

The following interfaces define the APIs for extending tests at various points in the
test execution lifecycle. Consult the following sections for examples and the Javadoc for
each of these interfaces in the `{extension-api-package}` package for further details.

* `{BeforeAllCallback}`
** `{BeforeEachCallback}`
*** `{BeforeTestExecutionCallback}`
*** `{AfterTestExecutionCallback}`
** `{AfterEachCallback}`
* `{AfterAllCallback}`

.Implementing Multiple Extension APIs
NOTE: Extension developers may choose to implement any number of these interfaces
within a single extension. Consult the source code of the `{SpringExtension}` for a
concrete example.

[[extensions-lifecycle-callbacks-before-after-execution]]
==== Before and After Test Execution Callbacks

`{BeforeTestExecutionCallback}` and `{AfterTestExecutionCallback}` define the APIs for
`Extensions` that wish to add behavior that will be executed _immediately before_ and
_immediately after_ a test method is executed, respectively. As such, these callbacks are
well suited for timing, tracing, and similar use cases. If you need to implement
callbacks that are invoked _around_ `@BeforeEach` and `@AfterEach` methods, implement
`BeforeEachCallback` and `AfterEachCallback` instead.

The following example shows how to use these callbacks to calculate and log the execution
time of a test method. `TimingExtension` implements both `BeforeTestExecutionCallback`
and `AfterTestExecutionCallback` in order to time and log the test execution.

[[extensions-lifecycle-callbacks-timing-extension]]
[source,java,indent=0]
[subs="verbatim"]
.An extension that times and logs the execution of test methods
----
include::{testDir}/example/timing/TimingExtension.java[tags=user_guide]
----

Since the `TimingExtensionTests` class registers the `TimingExtension` via `@ExtendWith`,
its tests will have this timing applied when they execute.

[source,java,indent=0]
[subs="verbatim"]
.A test class that uses the example TimingExtension
----
include::{testDir}/example/timing/TimingExtensionTests.java[tags=user_guide]
----

The following is an example of the logging produced when `TimingExtensionTests` is run.

[subs="none"]
----
INFO: Method [sleep20ms] took 24 ms.
INFO: Method [sleep50ms] took 53 ms.
----

[[extensions-exception-handling]]
=== Exception Handling

`{TestExecutionExceptionHandler}` defines the API for `Extensions` that wish to handle
exceptions thrown during test execution.

The following example shows an extension which will swallow all instances of `IOException`
but rethrow any other type of exception.

[source,java,indent=0]
[subs="verbatim"]
.An exception handling extension
----
include::{testDir}/example/exception/IgnoreIOExceptionExtension.java[tags=user_guide]
----

[[extensions-keeping-state]]
=== Keeping State in Extensions

Usually, an extension is instantiated only once. So the question becomes relevant: How do
you keep the state from one invocation of an extension to the next? The
`ExtensionContext` API provides a `Store` exactly for this purpose.  Extensions may
put values into a store for later retrieval.  See the
`<<extensions-lifecycle-callbacks-timing-extension, TimingExtension>>` for an example of using the
`Store` with a method-level scope. It is important to remember that values stored in a
`TestExtensionContext` during test execution will not be available in the surrounding
`ContainerExtensionContext`. Since `ContainerExtensionContexts` may be nested, the scope of inner
contexts may also be limited. Consult the corresponding Javadoc for details on the methods
available for storing and retrieving values via the `{ExtensionContext_Store}`.

[[extensions-supported-utilities]]
=== Supported Utilities in Extensions

The JUnit Platform Commons artifact exposes package `{junit-platform-support-package}` which
contains maintained utility methods handling `Annotation`, reflection and classpath scanning tasks.
Extension authors are encouraged to use these supported methods to align expected the behaviour
with the JUnit Platform.
