[[extension-model]]
== Extension Model


=== Overview

In contrast to the competing `Runner`, `@Rule`, and `@ClassRule` extension points in
JUnit 4, the JUnit 5 extension model consists of a single, coherent concept: the
`Extension` API. Note, however, that `Extension` itself is just a marker interface.

=== Registering Extensions

Extensions can be registered either declaratively via `@ExtendWith` or programmatically
via an `ExtensionRegistrar`.

Note that registered extensions are inherited within test class hierarchies.

==== Declarative Extension Registration

Developers can register one or more extensions _declaratively_ by annotating a test
class, test method, or custom _composed annotation_ with `@ExtendWith(...)` and supplying
class references for the extensions to register. For example, to register a custom
`MockitoExtension` for all tests in a particular class and its subclasses, you would
annotate the test class as follows.

[source,java,indent=0]
[subs="verbatim"]
----
@ExtendWith(MockitoExtension.class)
class MockTests {
	// ...
}
----

Multiple extensions can be registered together like this:

[source,java,indent=0]
[subs="verbatim"]
----
@ExtendWith({ FooExtension.class, BarExtension.class })
class MyTestsV1 {
	// ...
}
----

As an alternative, multiple extensions can be registered separately like this:

[source,java,indent=0]
[subs="verbatim"]
----
@ExtendWith(FooExtension.class)
@ExtendWith(BarExtension.class)
class MyTestsV2 {
	// ...
}
----

The execution of tests in both `MyTestsV1` and `MyTestsV2` will be extended by the
`FooExtension` and `BarExtension`, in exactly that order.

==== Programmatic Extension Registration

Developers can register one or more extensions _programmatically_ by implementing the
`ExtensionRegistrar` API and registering the custom `ExtensionRegistrar` implementation
via `@ExtendWith` as mentioned above. The following examples demonstrate the various
options in implementations of the `ExtensionRegistrar.registerExtensions()` method.

===== Registering an ExtensionPoint Instance

If you have an instance of an extension that implements one or more `ExtensionPoint`
APIs, you can register it as follows using the _default_ `Position`.

[source,java,indent=0]
[subs="verbatim"]
----
public void registerExtensions(ExtensionPointRegistry registry) {
    CustomExtension customExtension = // instantiate extension
    registry.register(customExtension);
}
----

If you would like to influence the order in which multiple implementations of the same
`ExtensionPoint` API are applied, you can do so by registering the extensions
programmatically and supplying the `Position`. The following values are permitted.

- `OUTERMOST`: Applied first. Only a single extension is allowed to be assigned this
  position; otherwise, an `ExtensionConfigurationException` will be thrown.
- `OUTSIDE_DEFAULT`: Applied after `OUTERMOST` but before `DEFAULT`, `INSIDE_DEFAULT`,
  and `INNERMOST`. Multiple extensions can be assigned this position; however, the
  ordering among such extensions is undefined.
- `DEFAULT`: (?)
- `INSIDE_DEFAULT`: (?)
- `INNERMOST`: (?)

The following listing demonstrates how to configure an explicit position for an instance
of an extension; however, a `Position` can also be supplied for lambda expressions and
method references.

[source,java,indent=0]
[subs="verbatim"]
----
public void registerExtensions(ExtensionPointRegistry registry) {
    registry.register(new TimingExtension(), Position.INNERMOST);
}
----

===== Registering a Lambda Expression as an ExtensionPoint

If you would like to implement a single `ExtensionPoint` API as a _lambda expression_,
you can register it as follows. Note, however, that the API must be a _functional
interface_.

[source,java,indent=0]
[subs="verbatim"]
----
public void registerExtensions(ExtensionPointRegistry registry) {
    registry.register((BeforeEachExtensionPoint) context -> { /* ... */ });
}
----

===== Registering a Method Reference as an ExtensionPoint

If you would like to implement a single `ExtensionPoint` API via a _method reference_,
you can register it as follows. Note, however, that the API must be a _functional
interface_.

[source,java,indent=0]
[subs="verbatim"]
----
public void registerExtensions(ExtensionPointRegistry registry) {
    registry.register((BeforeEachExtensionPoint) this::beforeEach);
}

void beforeEach(TestExtensionContext context) {
    /* ... */
}
----


=== Conditional Test Execution

`{ContainerExecutionCondition}` and `{TestExecutionCondition}` define the `Extension`
APIs for programmatic, _conditional test execution_.

A `ContainerExecutionCondition` is _evaluated_ to determine if all tests in a given
container (e.g., a test class) should be executed based on the supplied
`ContainerExtensionContext`. Similarly, a `TestExecutionCondition` is _evaluated_ to
determine if a given test method should be executed based on the supplied
`TestExtensionContext`.

See the source code of `{DisabledCondition}` and `{Disabled}` for concrete examples.


=== Test Instance Post-processing

`{InstancePostProcessor}` defines the API for `Extensions` that wish to _post
process_ test instances.

Common use cases include injecting dependencies into the test instance, invoking custom
initialization methods on the test instance, etc.

For concrete examples, consult the source code for the `{MockitoExtension}` and the
`{SpringExtension}`.

=== Parameter Resolution

`{MethodParameterResolver}` is an `Extension` strategy for dynamically resolving
method parameters at runtime.

If a `@Test`, `@BeforeEach`, `@AfterEach` , `@BeforeAll` or `@AfterAll` method accepts a
parameter, the parameter must be _resolved_ at runtime by a `MethodParameterResolver`. A
`MethodParameterResolver` can either be built-in (see `{TestNameParameterResolver}`) or
registered by the user via `@ExtendWith`. Generally speaking, parameters may be resolved
by _type_ or by _annotation_. For concrete examples, consult the source code for
`{CustomTypeParameterResolver}` and `{CustomAnnotationParameterResolver}`, respectively.

=== Test Lifecycle Callbacks

The following interfaces define the APIs for extending tests at various points in the
test execution lifecycle. Consult the Javadoc for each of these in the
`{extension-api-package}` package.

* `BeforeEachExtensionPoint`
* `AfterEachExtensionPoint`
* `BeforeAllExtensionPoint`
* `AfterAllExtensionPoint`

Note that extension developers may choose to implement any number of these interfaces
within a single extension. Consult the source code of the `{SpringExtension}` for a
concrete example.

=== Keeping State in Extensions

Usually, an extension is instantiated only once. So the question becomes relevant: How do you keep the state
from one invocation of an extension point to the next? ...



=== Additional Planned Extensions

Several additional extensions are planned, including but not limited to the following.

* Dynamic test registration – for example, for computing parameterized tests at runtime
