
== Extension Model


WARNING: The Extension Model chapter needs to be updated regarding the status quo.


=== Overview

In contrast to the competing `Runner`, `@Rule`, and `@ClassRule` extension points in
JUnit 4, the JUnit 5 extension model consists of a single, coherent concept: the
`TestExtension` API. Note, however, that `TestExtension` itself is just a marker
interface.

=== Registering Extensions

Developers can register one or more extensions by annotating a test class or test method
with `@ExtendWith(...)`, supplying class references for the extensions to register. For
example, to register a custom `MockitoExtension`, you would annotate your test class as
follows.

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@ExtendWith(MockitoExtension.class)
class MockTests {
  // ...
}
----

Multiple extensions can be registered together like this:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@ExtendWith({ FooExtension.class, BarExtension.class })
class MyTestsV1 {
  // ...
}
----

As an alternative, multiple extensions can be registered separately like this:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@ExtendWith(FooExtension.class)
@ExtendWith(BarExtension.class)
class MyTestsV2 {
  // ...
}
----

The execution of tests in both `MyTestsV1` and `MyTestsV2` will be extended by the
`FooExtension` and `BarExtension`, in exactly that order.

Registered extensions are inherited within test class hierarchies.


//////////////////////////

TODO needs to be updated to match status quo

=== Conditional Test Execution

https://github.com/junit-team/junit-lambda/tree/master/junit5-api/src/main/java/org/junit/gen5/api/extension/Condition.java[`Condition`]
defines the `TestExtension` API for programmatic, _conditional test execution_.

A `Condition` is _evaluated_ to determine if a given test (e.g., class or method) should
be executed based on the supplied `TestExecutionContext`. When evaluated at the class
level, a `Condition` applies to all test methods within that class.

See the source code of
https://github.com/junit-team/junit-lambda/tree/master/junit5-engine/src/main/java/org/junit/gen5/engine/junit5/extension/DisabledCondition.java[`DisabledCondition`]
and
https://github.com/junit-team/junit-lambda/tree/master/junit5-api/src/main/java/org/junit/gen5/api/Disabled.java[`@Disabled`]
for a concrete example.

//////////////////////////

=== Test Instance Post-processing

https://github.com/junit-team/junit-lambda/tree/master/junit5-api/src/main/java/org/junit/gen5/api/extension/InstancePostProcessor.java[`InstancePostProcessor`]
defines the API for `TestExtensions` that wish to _post process_ test instances.

Common use cases include injecting dependencies into the test instance, invoking custom
initialization methods on the test instance, etc.

For concrete examples, consult the source code for
https://github.com/junit-team/junit-lambda/tree/master/sample-extension/src/main/java/com/example/mockito/MockitoExtension.java[`MockitoExtension`]
and
https://github.com/sbrannen/spring-test-junit5/blob/prototype-1/src/main/java/org/springframework/test/context/junit5/SpringExtension.java[`SpringExtension`].

=== Parameter Resolution

https://github.com/junit-team/junit-lambda/tree/master/junit5-api/src/main/java/org/junit/gen5/api/extension/MethodParameterResolver.java[`MethodParameterResolver`]
is a `TestExtension` strategy for dynamically resolving method parameters at runtime.

If a `@Test`, `@BeforeEach`, `@AfterEach` , `@BeforeAll` or `@AfterAll` method accepts a
parameter, the parameter must be _resolved_ at runtime by a `MethodParameterResolver`. A
`MethodParameterResolver` can either be built-in (see
https://github.com/junit-team/junit-lambda/tree/master/junit5-engine/src/main/java/org/junit/gen5/engine/junit5/extension/TestNameParameterResolver.java[`TestNameParameterResolver`])
or registered by the user via `@ExtendWith`. Generally speaking, parameters may be
resolved by _type_ or by _annotation_. For concrete examples, consult the source code for
https://github.com/junit-team/junit-lambda/tree/master/sample-project/src/test/java/com/example/CustomTypeParameterResolver.java[`CustomTypeParameterResolver`]
and
https://github.com/junit-team/junit-lambda/tree/master/sample-project/src/test/java/com/example/CustomAnnotationParameterResolver.java[`CustomAnnotationParameterResolver`],
respectively.

=== Test Lifecycle Callbacks

The following interfaces define the APIs for extending tests at various points in the
test execution lifecycle. Consult the Javadoc for each of these in the
https://github.com/junit-team/junit-lambda/tree/master/junit5-api/src/main/java/org/junit/gen5/api/extension[`org.junit.gen5.api.extension`]
package.

* `BeforeEachExtensionPoint`
* `AfterEachExtensionPoint`
* `BeforeAllExtensionPoint`
* `AfterAllExtensionPoint`

Note that extension developers may choose to implement any number of these interfaces
within a single extension. Consult the source code of the
https://github.com/sbrannen/spring-test-junit5/blob/prototype-1/src/main/java/org/springframework/test/context/junit5/SpringExtension.java[`SpringExtension`]
for a concrete example.

=== Additional Planned Extension Points

The JUnit Lambda team is planning several additional extension points, including but not
limited to the following.

* Dynamic test registration – for example, for computing parameterized tests at runtime
