[[overview]]
== Overview

The goal of this document is to provide comprehensive reference documentation for both
programmers writing tests and extension authors.

=== Supported Java Versions

JUnit 5 only supports Java 8 and above. However, you can still test classes compiled with
lower versions.


== Installation

Snapshot artifacts are deployed to Sonatype's {snapshot-repo}[snapshots repository].

[[dependency-metadata]]
=== Dependency Metadata

* *Group ID*: `org.junit`
* *Version*: `{junit-version}`
* *Artifact IDs*:
** `junit-jupiter-api`
** `junit-jupiter-engine`
** `junit-platform-commons`
** `junit-platform-console`
** `junit-platform-engine`
** `junit-platform-gradle-plugin`
** `junit-platform-launcher`
** `junit-platform-runner`
** `junit-platform-surefire-provider`
** `junit-vintage-engine`

See also: {snapshot-repo}/org/junit/

=== JUnit 5 Sample Projects

The {junit5-samples-repo}[`junit5-samples`] repository hosts a collection of sample
projects based on JUnit 5. You'll find the respective `build.gradle` and `pom.xml` in
the projects below.

* For Gradle, check out the `{junit5-gradle-consumer}` project.
* For Maven, check out the `{junit5-maven-consumer}` project.
