[[release-notes-5.0.0-m4]]
=== 5.0.0-M4

*Date of Release:* ❓

*Scope:* Fourth milestone release of JUnit 5 with a focus on parameterized tests,
enhanced dynamic tests, and documentation.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/7?closed=1+[5.0 M4] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m4-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* Removed deprecated `selectNames()` name-based discovery selector from
  `DiscoverySelectors` in favor of the dedicated `selectPackage(String)`,
  `selectClass(String)`, and `selectMethod(String)` methods.

===== New Features

* Support for loading and registering custom `TestExecutionListener`
  implementations automatically via Java's `ServiceLoader` mechanism.

* Introduced new `getVersion()` method to `TestEngine` interface returning
  the implementation version of a test engine. By default, the method tries
  to determine the version from package attributes.

* Logging information of discovered engines was enhanced to include the
  version string supplied by the new `TestEngine::getVersion` method and other
  at runtime available package attribute values.

[[release-notes-5.0.0-m4-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* Removed deprecated `Assertions.expectThrows()` method in favor of `Assertions.assertThrows()`.

===== New Features and Improvements

* ❓


[[release-notes-5.0.0-m4-junit-vintage]]
==== JUnit Vintage

_No changes since 5.0.0-M3_
