[[release-notes-5.0.0-m4]]
=== 5.0.0-M4

*Date of Release:* ❓

*Scope:* Fourth milestone release of JUnit 5 with a focus on parameterized tests,
enhanced dynamic tests, and documentation.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/7?closed=1+[5.0 M4] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m4-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* Removed deprecated `selectNames()` name-based discovery selector from
  `DiscoverySelectors` in favor of the dedicated `selectPackage(String)`,
  `selectClass(String)`, and `selectMethod(String)` methods.
* `ClassNameFilter.includeClassNamePattern` was removed, please use
  `ClassNameFilter.includeClassNamePatterns` instead.
* `@IncludeClassNamePattern` was removed, please use `@IncludeClassNamePatterns` instead.
* `--hide-details` option of the `ConsoleLauncher` is deprecated, use `--details none` instead.

===== New Features

* Custom `TestExecutionListener` implementations can now be registered automatically via
  Java's `ServiceLoader` mechanism.
* New `getGroupId()`, `getArtifactId()`, and `getVersion()` default methods in the
  `TestEngine` API for debugging and reporting purposes. By default, package attributes
  (i.e., typically from JAR manifest attributes) are used to determine the artifact ID
  and version; whereas, the group ID is empty by default. Consult the Javadoc for
  `{TestEngine}` for details.
* Logging information for discovered test engines has been enhanced to include the group
  ID, artifact ID, and version of each test engine if available via the `getGroupId()`,
  `getArtifactId()`, and `getVersion()` methods.
* The `--scan-classpath` option of the `ConsoleLauncher` now allows to scan JAR files for tests
  when they are supplied as explicit arguments (see <<running-tests-console-launcher-options>>).
* New `--details <Details>` option of the `ConsoleLauncher` now allows to select output details
  mode while tests are executed. Use one of: `none`, `flat`, `tree` or `verbose`. If `none` is
  selected, only the summary and test failures are shown.


[[release-notes-5.0.0-m4-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Fix bug that prevented discovery of two or more methods of the same class.

===== Deprecations and Breaking Changes

* Removed deprecated `Assertions.expectThrows()` method in favor of `Assertions.assertThrows()`.

===== New Features and Improvements

* `Assertions.assertThrows()` now uses canonical names for exception types when
  generating assertion failure messages.
* `TestInstancePostProcessors` registered on test methods are now invoked.


[[release-notes-5.0.0-m4-junit-vintage]]
==== JUnit Vintage

_No changes since 5.0.0-M3_
