[[release-notes-5.0.2]]
== 5.0.2

*Date of Release:* November 12, 2017

*Scope:* Bug fixes and minor improvements since the 5.0.1 release

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/17?closed=1+[5.0.2] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.2-junit-platform]]
=== JUnit Platform

==== Bug Fixes

* Failed tests are now reported correctly with Maven Surefire for test engines that do
  not use `MethodSource` (e.g. Spek).
* Tests that write to `System.out` or `System.err`, in particular via a logging
  framework, are now consistently reported correctly when executed with a non-zero
  `forkCount` with Maven Surefire.

==== New Features and Improvements

* The JUnit Platform Maven Surefire provider now supports the `redirectTestOutputToFile`
  Surefire feature.
* The JUnit Platform Maven Surefire provider now ignores empty strings supplied via
  `<includeTags/>`, `<groups/>`, `<excludeTags/>`, and `<excludedGroups/>`.


[[release-notes-5.0.2-junit-jupiter]]
=== JUnit Jupiter

==== Bug Fixes

* Trailing spaces in a `@CsvSource` or `@CsvFileSource` input line no longer yield `null`
  values.
* `@EnableRuleMigrationSupport` previously failed to recognize `@Rule` methods that
  returned a subtype of one of the supported `TestRule` types. Moreover, it mistakenly
  instantiated some rules declared using methods multiple times. Now, once enabled, it
  will instantiate all declared rules (fields _and_ methods) exactly once and call them
  in the same order used by JUnit 4.
* Previously, disabled test classes were eagerly instantiated when `Lifecycle.PER_CLASS`
  was used. Now, `ExecutionCondition` evaluation always takes place before test class
  instantiation.
* The `junit-jupiter-migrationsupport` module no longer incorrectly attempts to register
  the `JupiterTestEngine` via the `ServiceLoader` mechanism, thereby allowing it to be
  used as a module on the Java 9 module-path.

==== New Features and Improvements

* Failure messages for `assertTrue()` and `assertFalse()` in the `Assertions` class now
  include details about the expected and actual boolean values.
  - For example, the generated failure message for a call to `assertTrue(false)` is now
    "expected: <true> but was: <false>" instead of an empty string.
* If a parameterized test does not consume all arguments supplied to it via argument
  sources, the unconsumed arguments are no longer included in the display name.


[[release-notes-5.0.2-junit-vintage]]
=== JUnit Vintage

No changes.
