[[release-notes-5.1.0-M1]]
=== 5.1.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/14?closed=1+[5.1 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* Maven Surefire: Ensure failed tests of test engines that do not use `MethodSource` (e.g.
  Spek) are reported correctly.

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* New `@SuiteDisplayName` annotation in the `junit-platform-suite-api` module for
  declaring a custom _display name_ for a test suite.
  - Supported by the `JUnitPlatform` runner for JUnit 4 in the `junit-platform-runner`
    module.
* When running on Java 9 or higher the `default` implementations of `getVersion()` and
  `getArtifactId()` in the `TestEngine` interface query the _Java Platform Module System_
  for this information.
* Class loading errors that occur during classpath scanning are now logged at `DEBUG`
  level (i.e., the `FINE` log level in `java.util.logging`) instead of as warnings.
* New discovery selector `ModuleSelector` for scanning Java 9 modules for test classes.
* New console launcher option `--select-module <name>` or `-o <name>`.
* New console launcher option `--scan-module-path` for selecting all resolved modules
  available on the boot layer configuration.

[[release-notes-5.1.0-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Trailing spaces in a `@CsvSource` or `@CsvFileSource` input line no longer yield `null`
  values.
* `@EnableRuleMigrationSupport` failed to recognize `@Rule` methods that returned a
  subtype of one of the supported `TestRule` types. Moreover, it mistakenly instantiated
  some rules declared using methods multiple times. Now, once enabled, it will instantiate
  all declared rules (fields _and_ methods) exactly once and call them in the same order
  used by Vintage.

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* Failure messages for `assertTrue()` and `assertFalse()` in the `Assertions` class now
  include details about the expected and actual boolean values.
  - For example, the generated failure message for a call to `assertTrue(false)` is now
    "expected: <true> but was: <false>" instead of an empty string.
* Unused arguments are now omitted from display names of parameterized tests.
* New `getOrComputeIfAbsent(Class)` convenience method in `ExtensionContext.Store` that
  simplifies use cases where an extension wishes to store a single object of a given type
  (keyed by that type) in the `Store` and the object is created using the default
  constructor for that type.
  - For example, code such as
    `store.getOrComputeIfAbsent(X.class, key \-> new X(), X.class)` can now replaced with
    `store.getOrComputeIfAbsent(X.class)`.
* Support new JUnit Platform `ModuleSelector`.


[[release-notes-5.1.0-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* Support new JUnit Platform `ModuleSelector`.
