[[release-notes-5.0.0]]
=== 5.0.0

*Date of Release:* September 10, 2017

*Scope:* First General Availability Release

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/10?closed=1+[5.0 GA] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-junit-platform]]
==== JUnit Platform

===== Deprecations and Breaking Changes

* The `@API` annotation has been removed from the `junit-platform-commons` project and
  relocated to a new standalone project on GitHub called the _@API Guardian_.
* Tags are no longer permitted to contain any of the following _reserved characters_.
  - `,`, `(`, `)`, `&`, `|`, `!`
* The constructor for `FilePosition` has been replaced with a static factory method named
  `from(int, int)`.
* A `FilePosition` can now be constructed solely from a line number via the new
  `from(int)` static factory method.
* `FilePosition.getColumn()` now returns `Optional<Integer>` instead of `int`.
* The constructors in the following concrete `TestSource` implementations have been
  replaced with static factory methods named `from(...)`.
  - `ClasspathResourceSource`
  - `ClassSource`
  - `CompositeTestSource`
  - `DirectorySource`
  - `FileSource`
  - `MethodSource`
  - `PackageSource`
* The constructor for `LoggingListener` has been replaced with a static factory method
  named `forBiConsumer(...)`.


[[release-notes-5.0.0-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Fix implementation of `AbstractExtensionContext.getRoot()` so that it actually
  traverses the complete hierarchy and returns the true root.


[[release-notes-5.0.0-junit-vintage]]
==== JUnit Vintage

No changes.
