[[release-notes-5.0.0-m1]]
=== 5.0.0-M1

*Date of Release:* July 7, 2016

*Scope:* First milestone release of JUnit 5

[[release-notes-5.0.0-m1-summary]]
==== Summary of Changes

The following is a list of global changes. For details regarding changes specific to the
Platform, Jupiter, and Vintage, consult the dedicated subsections below. For a complete
list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/2?closed=1+[5.0 M1] milestone page in the JUnit repository
on GitHub.

* JAR manifests in published artifacts now contain additional metadata such as
  `Created-By`, `Built-By`, `Build-Date`, `Build-Time`, `Build-Revision`,
  `Implementation-Title`, `Implementation-Version`, `Implementation-Vendor`, etc.
* Published artifacts now contain `LICENSE.md` in `META-INF`.
* JUnit now participates in the http://up-for-grabs.net/#/tags/junit[Up For Grabs]
  movement for open source contributions.
** See the https://github.com/junit-team/junit5/labels/up-for-grabs[up-for-grabs] label
   on GitHub.
* Group IDs, artifact IDs, and versions have changed for all published artifacts.
** See <<release-notes-5.0.0-m1-migration-artifacts>> and <<dependency-metadata>>.
* All base packages have been renamed.
** See <<release-notes-5.0.0-m1-migration-packages>>.

[[release-notes-5.0.0-m1-migration-artifacts]]
.Artifact Migration
[cols="12,19,20,30,15"]
|===
| Old Group ID | Old Artifact ID    | New Group ID         | New Artifact ID                    | New Base Version

| `org.junit`  | `junit-commons`    | `org.junit.platform` | `junit-platform-commons`           | `1.0.0`
| `org.junit`  | `junit-console`    | `org.junit.platform` | `junit-platform-console`           | `1.0.0`
| `org.junit`  | `junit-engine-api` | `org.junit.platform` | `junit-platform-engine`            | `1.0.0`
| `org.junit`  | `junit-gradle`     | `org.junit.platform` | `junit-platform-gradle-plugin`     | `1.0.0`
| `org.junit`  | `junit-launcher`   | `org.junit.platform` | `junit-platform-launcher`          | `1.0.0`
| `org.junit`  | `junit4-runner`    | `org.junit.platform` | `junit-platform-runner`            | `1.0.0`
| `org.junit`  | `surefire-junit5`  | `org.junit.platform` | `junit-platform-surefire-provider` | `1.0.0`
| `org.junit`  | `junit5-api`       | `org.junit.jupiter`  | `junit-jupiter-api`                | `5.0.0`
| `org.junit`  | `junit5-engine`    | `org.junit.jupiter`  | `junit-jupiter-engine`             | `5.0.0`
| `org.junit`  | `junit4-engine`    | `org.junit.vintage`  | `junit-vintage-engine`             | `4.12.0`
|===

[[release-notes-5.0.0-m1-migration-packages]]
.Package Migration
[cols="20,80"]
|===
| Old Base Package               | New Base Package

| `org.junit.gen5.api`           | `org.junit.jupiter.api`
| `org.junit.gen5.commons`       | `org.junit.platform.commons`
| `org.junit.gen5.console`       | `org.junit.platform.console`
| `org.junit.gen5.engine.junit4` | `org.junit.vintage.engine`
| `org.junit.gen5.engine.junit5` | `org.junit.jupiter.engine`
| `org.junit.gen5.engine`        | `org.junit.platform.engine`
| `org.junit.gen5.gradle`        | `org.junit.platform.gradle.plugin`
| `org.junit.gen5.junit4.runner` | `org.junit.platform.runner`
| `org.junit.gen5.launcher`      | `org.junit.platform.launcher`
| `org.junit.gen5.launcher.main` | `org.junit.platform.launcher.core`
| `org.junit.gen5.surefire`      | `org.junit.platform.surefire.provider`
|===


[[release-notes-5.0.0-m1-junit-platform]]
==== JUnit Platform

* The `ConsoleRunner` has been renamed to `ConsoleLauncher`.
* `ConsoleLauncher` now always returns the status code on exit, and the _enable exit code_
  flags have been removed.
* The `junit-platform-console` artifact no longer defines transitive dependencies on
  `junit-platform-runner`, `junit-jupiter-engine`, or `junit-vintage-engine`.
* The `JUnit5` Runner has been renamed to `JUnitPlatform`.
** `@Packages` has been renamed to `@SelectPackages`.
** `@Classes` has been renamed to `@SelectClasses`.
** `@UniqueIds` has been removed.
** `@UseTechnicalNames` has been introduced.
*** See <<running-tests-junit-platform-runner-technical-names>>.
* The Gradle plugin for the JUnit Platform has been completely overhauled.
** The JUnit Platform Gradle plugin now requires Gradle 2.5 or higher.
** The `junit5Test` Gradle task has been renamed to `junitPlatformTest`.
** The `junit5` Gradle plugin configuration has been renamed to `junitPlatform`.
*** `runJunit4` has been replaced by `enableStandardTestTask`.
*** `version` has been replaced by `platformVersion`.
** See <<running-tests-build-gradle>> for further details.
* XML test report generation has been overhauled.
** XML reports now contain newlines.
** Attributes specific to the JUnit Platform that do not align with standard attributes
   in the de facto standard XML schema are now contained in `CDATA` blocks within the
   `<system-out>` element.
** XML reports now use real method names and fully qualified class names instead of
   display names.
* Unique ID in `TestIdentifier` is now a `String`.
* `TestSource` is now an interface with a dedicated hierarchy consisting of
  `CompositeTestSource`, `JavaSource`, `JavaPackageSource`, `JavaClassSource`,
  `JavaMethodSource`, `UriSource`, `FileSystemSource`, `DirectorySource`, and
  `FileSource`.
* All `DiscoverySelector` factory methods have been moved to a new `DiscoverySelectors`
  class that serves as a centralized collection of all _select_ methods.
* `Filter.filter()` has been renamed to `Filter.apply()`.
* `TestTag.of()` has been renamed to `TestTag.create()`.
* `TestDiscoveryRequest` has been renamed to `LauncherDiscoveryRequest`.
* `TestDiscoveryRequestBuilder` has been renamed to `LauncherDiscoveryRequestBuilder`.
* `LauncherDiscoveryRequest` is now immutable.
* `TestDescriptor.allDescendants()` has been renamed to `TestDescriptor.getAllDescendants()`.
* `TestEngine#discover(EngineDiscoveryRequest)` has been replaced by
  `TestEngine#discover(EngineDiscoveryRequest, UniqueId)`.
* Introduced `ConfigurationParameters` which the `Launcher` supplies to engines via the
  `EngineDiscoveryRequest` and `ExecutionRequest`
* The `Container` and `Leaf` abstractions have been removed from the `HierarchicalTestEngine`.
* The `getName()` method has been removed from `TestIdentifier` and `TestDescriptor` in
  favor of retrieving an implementation specific name via the `TestSource`.
* Test engines are now permitted to be completely dynamic in nature. In other words, a
  `TestEngine` is no longer required to create `TestDescriptor` entries during the
  _discovery phase_; a `TestEngine` may now optionally register containers and tests
  dynamically during the _execution phase_.
* Include and exclude support for engines and tags has been completely revised.
** Engines and tags can no longer be _required_ but rather _included_.
** `ConsoleLauncher` now supports the following options: `t`/`include-tag`,
   `T`/`exclude-tag`, `e/include-engine`, `E/exclude-engine`.
** The Gradle plugin now supports `engines` and `tags` configuration blocks with nested
   `include` and `exclude` entries.
** `EngineFilter` now supports `includeEngines()` and `excludeEngines()` factory methods.
** The `JUnitPlatform` runner now supports `@IncludeTags`, `@ExcludeTags`,
   `@IncludeEngines`, and `@ExcludeEngines`.

[[release-notes-5.0.0-m1-junit-jupiter]]
==== JUnit Jupiter

* The `junit5` engine ID has been renamed to `junit-jupiter`.
* `JUnit5TestEngine` has been renamed to `JupiterTestEngine`.
* `Assertions` now provides the following support:
** `assertEquals()` for primitive types
** `assertEquals()` for doubles and floats with deltas
** `assertArrayEquals()`
** Expected and actual values are now supplied to the `AssertionFailedError`.
* <<writing-tests-dynamic-tests,Dynamic Tests>>: tests can now be registered dynamically
  at runtime via lambda expressions.
* `TestInfo` now provides access to tags via `getTags()`.
* `@AfterEach` methods and _after_ callbacks are now invoked if an exception is thrown by
  a `@Test` method, a `@BeforeEach` method, or a _before_ callback.
* `@AfterAll` methods and _after all_ callbacks are now guaranteed to be invoked.
* Repeatable annotations such as `@ExtendWith` and `@Tag` are now discovered in
  superclasses within a test class hierarchy as well as on interfaces.
* Extensions are now registered _top-down_ within a test class or interface hierarchy.
* Test and container execution <<extensions-conditions-deactivation,_conditions_ can now
  be deactivated>>.
* `InstancePostProcessor` has been renamed to `TestInstancePostProcessor`.
** `TestInstancePostProcessor` implementations are now properly applied within `@Nested`
   test class hierarchies.
* `MethodParameterResolver` has been renamed to `ParameterResolver`.
** The `ParameterResolver` API is now based on `java.lang.reflect.Executable` and can
   therefore be used to resolve parameters for methods _and_ constructors.
** New `ParameterContext` which is passed to the `supports()` and `resolve()` methods of
   `ParameterResolver` extensions.
** Resolution of primitive types is now supported for `ParameterResolver` extensions.
* The `ExtensionPointRegistry` and `ExtensionRegistrar` have been removed in favor of
  declarative registration via `@ExtendWith`.
* `BeforeAllExtensionPoint` has been renamed to `BeforeAllCallback`.
* `AfterAllExtensionPoint` has been renamed to `AfterAllCallback`.
* `BeforeEachExtensionPoint` has been renamed to `BeforeEachCallback`.
* `BeforeAllExtensionPoint` has been renamed to `BeforeAllCallback`.
* New `BeforeTestExecutionCallback` and `AfterTestExecutionCallback` extension APIs.
* `ExceptionHandlerExtensionPoint` has been renamed to `TestExecutionExceptionHandler`.
* Test exceptions are now supplied to extensions via the `TestExtensionContext`.
* `ExtensionContext.Store` now supports type-safe variants of many of its methods.
* `ExtensionContext.getElement()` now returns an `Optional`.
* `Namespace.of()` has been renamed to `Namespace.create()`.
* `TestInfo` and `ExtensionContext` have new `getTestClass()` and `getTestMethod()`
  methods.
* The `getName()` method has been removed from `TestInfo` and `ExtensionContext` in favor
  of retrieving a context specific name via the current test class or test method.

[[release-notes-5.0.0-m1-junit-vintage]]
==== JUnit Vintage

* The `junit4` engine ID has been renamed to `junit-vintage`.
* `JUnit4TestEngine` has been renamed to `VintageTestEngine`.
