[[release-notes-5.0.0-rc1]]
=== 5.0.0-RC1

*Date of Release:* July 30, 2017

*Scope:* Bug fixes and documentation improvements before 5.0 GA

WARNING: This is a pre-release and contains a few breaking changes. Please refer to the
<<running-tests-ide-intellij-idea,instructions>> above to use this version in a version of
IntelliJ IDEA that bundles an older milestone release.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/9?closed=1+[5.0 RC1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-rc1-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* Generic, interface `default` methods that are not overridden by an implementing class
  can now be _selected_ by class, method name, and parameter types or by _fully qualified
  method name_. This applies to method selectors in `DiscoverySelectors` as well as to
  both `findMethod()` variants in `ReflectionSupport`.
* A non-overridden interface default method whose method signature is overloaded by a
  locally declared method is now properly discovered when searching for methods within a
  class hierarchy using `findMethods()` in `ReflectionSupport`.
* Overridden interface default methods are no longer discovered when searching for
  methods within a class hierarchy using `findMethods()` in `ReflectionSupport`.

===== Deprecations and Breaking Changes

* Removed deprecated method `execute(LauncherDiscoveryRequest)` from `Launcher` class.
  The removed method was replaced in milestone 4 by method
  `execute(LauncherDiscoveryRequest, TestExecutionListener...)`.


[[release-notes-5.0.0-rc1-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Configuration errors regarding lifecycle methods annotated with `@BeforeAll`,
  `@AfterAll`, `BeforeEach`, or `@AfterEach` no longer halt the execution of the entire
  test plan during the discovery phase. Rather, such errors are now reported during the
  execution of the affected test class.
* A non-overridden interface default method whose method signature is overloaded by a
  locally declared method is now properly included in the test plan. This applies to
  default methods annotated with Jupiter annotations such as `@Test`, `@BeforeEach`, etc.
* Overridden interface default methods are no longer included in the test plan. This
  applies to default methods annotated with Jupiter annotations such as `@Test`,
  `@BeforeEach`, etc.

===== New Features and Improvements

* New variants of `Assertions.assertThrows()` that accept a custom failure message as a
  `String` or `Supplier<String>`.
* Methods referenced by `@MethodSource` are no longer required to be `static` if the test
  class is annotated with `@TestInstance(Lifecycle.PER_CLASS)`.
* Test classes written in the Kotlin programming language are now executed with
  `@TestInstance(Lifecycle.PER_CLASS)` semantics by default.


[[release-notes-5.0.0-rc1-junit-vintage]]
==== JUnit Vintage

No changes besides internal refactorings.
