[[release-notes-5.0.0-m2]]
=== 5.0.0-M2

*Date of Release:* July 23, 2016

*Scope:* Second milestone release of JUnit 5

[[release-notes-5.0.0-m2-summary]]
==== Summary of Changes

This release is primarily a bugfix release for bugs discovered since `5.0.0-M1`.

The following is a list of global changes. For details regarding changes specific to the
Platform, Jupiter, and Vintage, consult the dedicated subsections below. For a complete
list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/4?closed=1+[5.0 M2] milestone page in the JUnit repository
on GitHub.

* The JUnit 5 Gradle build now runs properly on Microsoft Windows.
* A continuous integration build against Microsoft Windows has been set up on AppVeyor.

[[release-notes-5.0.0-m2-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* Failures in containers -- for example, `@BeforeAll` methods that throw exceptions --
  now fail the build when using the `ConsoleLauncher` or the JUnit Platform Gradle plugin.
* The JUnit Platform Surefire Provider no longer silently ignores purely dynamic test
  classes -- for example, test classes that only declare `@TestFactory` methods.
* The `junit-platform-console` and `junit-platform-console.bat` shell scripts included in
  the `junit-platform-console-<release version>` TAR and ZIP distributions now properly
  refer to the `ConsoleLauncher` instead of the `ConsoleRunner`.
* The `TestExecutionSummary` used by the `ConsoleLauncher` and the JUnit Platform Gradle
  plugin now includes the actual exception type for failures.
* Classpath scanning is now safeguarded against exceptions encountered during class
  loading and processing -- for example, when processing classes with malformed names.
  The underlying exception is swallowed and logged along with the offending file path. If
  the exception is a _blacklisted exception_ such as an `OutOfMemoryError`, however, it
  will be rethrown.

===== Deprecations

* Generic name-based discovery selectors (i.e., `selectName()` and `selectNames()`) in
  `DiscoverySelectors` have been deprecated in favor of the dedicated
  `selectPackage(String)`, `selectClass(String)`, and `selectMethod(String)` methods.

===== New Features

* New  `selectMethod(String)` method in `DiscoverySelectors` that supports selection of
  a _fully qualified method name_.

[[release-notes-5.0.0-m2-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Extension implementations declared via `@ExtendWith` at the class-level and at the
  method-level will no longer be registered multiple times.

[[release-notes-5.0.0-m2-junit-vintage]]
==== JUnit Vintage

_No changes since 5.0.0-M1_
