[[release-notes-5.0.0-m3]]
=== 5.0.0-M3

*Date of Release:* September 30, 2016

*Scope:* Third milestone release of JUnit 5 with a focus on JUnit 4 interoperability,
additional discovery selectors, and documentation.

[[release-notes-5.0.0-m3-summary]]
==== Summary of Changes

The following is a list of global changes. For details regarding changes specific to the
Platform, Jupiter, and Vintage, consult the dedicated subsections below. For a complete
list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/6?closed=1+[5.0 M3] milestone page in the JUnit repository
on GitHub.

* ❓❓❓


[[release-notes-5.0.0-m3-junit-platform]]
===== JUnit Platform

====== Bug Fixes

* `ColoredPrintingTestListener`, which is used by the `ConsoleLauncher`, now outputs the
  actual exception type and its stack trace when printing an exception message.
* Test classes in the _default_ package are now picked up via classpath scanning when
  scanning classpath roots -- for example, in conjunction with the JUnit Platform
  Gradle plugin when no explicit packages have been selected.

====== Deprecations and Breaking Changes

* `ClasspathSelector` has been renamed to `ClasspathRootSelector` to avoid confusion with
  `ClasspathResourceSelector`.
* `PackageSelector` and `DiscoverySelectors.selectPackage()` have been renamed to
  `JavaPackageSelector` and `DiscoverySelectors.selectJavaPackage()` to align with
  `JavaPackageSource`.
* `ClassSelector` and `DiscoverySelectors.selectClass()` have been renamed to
  `JavaClassSelector` and `DiscoverySelectors.selectJavaClass()` to align with
  `JavaClassSource`.
* `MethodSelector` and `DiscoverySelectors.selectMethod()` have been renamed to
  `JavaMethodSelector` and `DiscoverySelectors.selectJavaMethod()` to align with
  `JavaMethodSource`.
* Generic name-based discovery selectors (i.e., `selectName()` and `selectNames()`) in
  `DiscoverySelectors` have been deprecated in favor of the dedicated
  `selectJavaPackage(String)`, `selectJavaClass(String)`, and `selectJavaMethod(String)` methods.
* The `-p` command-line option for configuring additional classpath entries for the
  `ConsoleLauncher` has been renamed to `-cp` in order to align with the option names for
  the standard `java` executable. In addition, a new `--class-path` alias has been
  introduced, while the existing `--classpath` command-line option remains unchanged.
* The `-a` and `--all` command-line options for the `ConsoleLauncher` have been renamed
  to `--scan-class-path`.
* The `--xml-reports-dir` command-line option for the `ConsoleLauncher` has been renamed
  to `--reports-dir`.
* The `-C`, `-D`, and `-r` short command-line options for the `ConsoleLauncher` have been
  removed in favor of using their _long_ equivalents `--disable-ansi-colors`,
  `--hide-details`, and `--reports-dir` respectively.

====== New Features

* New `selectUri(*)` methods in `DiscoverySelectors` for selecting URIs. A `TestEngine`
  can retrieve such values by querying registered instances of `UriSelector`.
* New `selectFile(*)` and `selectDirectory(*) methods in `DiscoverySelectors` for selecting
  files and directories in the file system. A `TestEngine` can retrieve such values by
  querying registered instances of `FileSelector` and `DirectorySelector`.
* New `selectClasspathResource(String)` method in `DiscoverySelectors` for selecting
  _classpath resources_ such as XML or JSON files by name, where the name is a
  `/`-separated path name for the resource within the current classpath. A `TestEngine`
  can retrieve such values by querying registered instances of `ClasspathResourceSelector`.
  Furthermore, a classpath resource can be made available as the `TestSource` of a
  `TestIdentifier` via the new `ClasspathResourceSource`.
* The `selectMethod(String)` method in `DiscoverySelectors` now supports selection of
  a _fully qualified method name_ for a method that accepts parameters -- for example,
  `"org.example.TestClass#testMethod(org.junit.jupiter.api.TestInfo)"`.
* The `TestExecutionSummary` used by the `ConsoleLauncher` and the JUnit Platform Gradle
  plugin now includes statistics for all container events in addition to test events.


[[release-notes-5.0.0-m3-junit-jupiter]]
===== JUnit Jupiter

====== Bug Fixes

* `DynamicTest.stream()` now accepts a `ThrowingConsumer` instead of a conventional
  `Consumer` for its _test executor_, thereby allowing for custom streams of
  dynamic tests that may potentially throw checked exceptions.
* The `JupiterTestEngine` now supports selection of test methods via their unique ID for
  methods that accept arrays or primitive types as parameters.
* `ExtensionContext.Store` is now thread-safe.

====== Deprecations and Breaking Changes

* The `Executable` functional interface has been relocated to a new dedicated
  `org.junit.jupiter.api.function` package.

====== New Features

* Support for lazy and preemptive _timeouts_ with lambda expressions in `Assertions`. See
  examples in <<writing-tests-assertions,`AssertionsDemo`>> and consult the
  `{Assertions}` Javadoc for further details.
* New variants of `Assertions.assertAll()` that accept streams of executables (i.e.,
  `Stream<Executable>`).


[[release-notes-5.0.0-m3-junit-vintage]]
===== JUnit Vintage

_No changes since 5.0.0-M2_
