[[release-notes-5.0.0-m3]]
=== 5.0.0-M3

*Date of Release:* November 30, 2016

*Scope:* Third milestone release of JUnit 5 with a focus on JUnit 4 interoperability,
additional discovery selectors, and documentation.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/6?closed=1+[5.0 M3] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m3-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* `ColoredPrintingTestListener`, which is used by the `ConsoleLauncher`, now outputs the
  actual exception type and its stack trace when printing an exception message.
* Test classes in the _default_ package are now picked up via classpath scanning when
  scanning classpath roots -- for example, in conjunction with the JUnit Platform
  Gradle plugin when no explicit packages have been selected.
* Classpath scanning no longer loads classes that are excluded by a class name filter.
* Classpath scanning no longer attempts to load Java 9 `module-info.class` files.

===== Deprecations and Breaking Changes

* `ClasspathSelector` has been renamed to `ClasspathRootSelector` to avoid confusion with
  `ClasspathResourceSelector`.
* `JavaPackageSource` has been renamed to `PackageSource` to align with `PackageSelector`.
* `JavaClassSource` has been renamed to `ClassSource` to align with `ClassSelector`.
* `JavaMethodSource` has been renamed to `MethodSource` to align with `MethodSelector`.
* `PackageSource`, `ClassSource`, and `MethodSource` now directly implement the `TestSource`
  interface instead of the `JavaSource` interface which has been removed.
* Generic name-based discovery selectors (i.e., `selectName()` and `selectNames()`) in
  `DiscoverySelectors` have been deprecated in favor of the dedicated
  `selectPackage(String)`, `selectClass(String)`, and `selectMethod(String)` methods.
* `ClassFilter` has been renamed to `ClassNameFilter` and now implements `DiscoveryFilter<String>`
  instead of `DiscoveryFilter<Class<?>>` so it can be applied before loading classes during
  classpath scanning.
* `ClassNameFilter.includeClassNamePattern` is now deprecated in favor of
  `ClassNameFilter.includeClassNamePatterns`.
* `@IncludeClassNamePattern` is now deprecated in favor of `@IncludeClassNamePatterns`.
* The `-p` command-line option for configuring additional classpath entries for the
  `ConsoleLauncher` has been renamed to `-cp` in order to align with the option names for
  the standard `java` executable. In addition, a new `--class-path` alias has been
  introduced, while the existing `--classpath` command-line option remains unchanged.
* The `-a` and `--all` command-line options for the `ConsoleLauncher` have been renamed
  to `--scan-class-path`.
* The `--xml-reports-dir` command-line option for the `ConsoleLauncher` has been renamed
  to `--reports-dir`.
* The `-C`, `-D`, and `-r` short command-line options for the `ConsoleLauncher` have been
  removed in favor of using their _long_ equivalents `--disable-ansi-colors`,
  `--hide-details`, and `--reports-dir` respectively.
* The `ConsoleLauncher` no longer supports passing non-option arguments. Please use the new
  explicit selector options to specify package, class, or method names instead. Alternatively,
  `--scan-class-path` now accepts an optional argument that can be used to select classpath entries
  to be scanned. Multiple classpath entries may be used by separating them using the system's path
  separator (`;` on Windows, `:` on Unix).
* `LauncherDiscoveryRequestBuilder` no longer accepts `null` values for `selectors`, `filters`,
  or maps of configuration parameters.
* Filters for class name, engine IDs, and tags in the Gradle plugin configuration now need to be
  wrapped in a `filters` extension element (see <<running-tests-build-gradle-filters>>).

===== New Features

* New `selectUri(...)` methods in `DiscoverySelectors` for selecting URIs. A `TestEngine`
  can retrieve such values by querying registered instances of `UriSelector`.
* New `selectFile(...)` and `selectDirectory(...)` methods in `DiscoverySelectors` for selecting
  files and directories in the file system. A `TestEngine` can retrieve such values by
  querying registered instances of `FileSelector` and `DirectorySelector`.
* New `selectClasspathResource(String)` method in `DiscoverySelectors` for selecting
  _classpath resources_ such as XML or JSON files by name, where the name is a
  `/`-separated path name for the resource within the current classpath. A `TestEngine`
  can retrieve such values by querying registered instances of `ClasspathResourceSelector`.
  Furthermore, a classpath resource can be made available as the `TestSource` of a
  `TestIdentifier` via the new `ClasspathResourceSource`.
* The `selectMethod(String)` method in `DiscoverySelectors` now supports selection of
  a _fully qualified method name_ for a method that accepts parameters -- for example,
  `"org.example.TestClass#testMethod(org.junit.jupiter.api.TestInfo)"`.
* The `TestExecutionSummary` used by the `ConsoleLauncher` and the JUnit Platform Gradle
  plugin now includes statistics for all container events in addition to test events.
* The `TestExecutionSummary` can now be used to get the list of all failures.
* The `{ConsoleLauncher}`, the Gradle plugin, and the `{JUnitPlatform-Runner}` runner now use
  `{standard-include-class-name-pattern}` as the default pattern for class names to be included
  in the test run.
* The Gradle plugin now allows to explicitly select which tests should be executed
  (see <<running-tests-build-gradle-selectors>>).
* New `@Testable` annotation that `TestEngine` implementations can use to signal to IDEs
  and tooling vendors that the annotated or meta-annotated element is _testable_ (i.e.
  that it can be executed as a test on the JUnit Platform).
* Multiple regular expressions that are combined using OR semantics can now be passed to
  `ClassNameFilter.includeClassNamePatterns`.
* Multiple regular expressions that are combined using OR semantics can now be passed via
  `@IncludeClassNamePatterns` to the `JUnitPlatform` runner.
* Multiple regular expressions that are combined using OR semantics can now be passed to the JUnit
  Platform Gradle plugin (see <<running-tests-build-gradle-filters>>) and the `{ConsoleLauncher}`
  (see <<running-tests-console-launcher-options>>).
* Package names can now be included or excluded using `PackageNameFilter.includePackageNames`
  or `PackageNameFilter.excludePackageNames`.
* Package names can now be included or excluded using `@IncludePackages` and `@ExcludePackages`
  in combination with the `JUnitPlatform` runner.
* Package names can now be included or excluded via a filter configuration to the JUnit Platform
  Gradle plugin (see <<running-tests-build-gradle-filters>>) and the `{ConsoleLauncher}`
  (see <<running-tests-console-launcher-options>>).
* The `junit-platform-console` no longer has a mandatory dependency on
  https://pholser.github.io/jopt-simple/[JOpt Simple]. Thus, it's now possible to test custom
  code that uses a different version of that library.
* Resolution of package selectors now also scans JAR files.
* The Surefire provider now supports forking.
* The Surefire provider now supports filtering by tags using one of the following parameters:
  - include: `groups`/`includeTags`
  - exclude: `excludedGroups`/`excludeTags`
* The Surefire provider is now licensed under the Apache License v2.0.


[[release-notes-5.0.0-m3-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* `@AfterEach` methods are now executed with _bottom-up_ semantics within a test
  class hierarchy.
* `DynamicTest.stream()` now accepts a `ThrowingConsumer` instead of a conventional
  `Consumer` for its _test executor_, thereby allowing for custom streams of
  dynamic tests that may potentially throw checked exceptions.
* Extensions registered at the test method level are now used when invoking
  `@BeforeEach` and `@AfterEach` methods for the corresponding test method.
* The `JupiterTestEngine` now supports selection of test methods via their unique ID for
  methods that accept arrays or primitive types as parameters.
* `ExtensionContext.Store` is now thread-safe.

===== Deprecations and Breaking Changes

* The `Executable` functional interface has been relocated to a new dedicated
  `org.junit.jupiter.api.function` package.
* `Assertions.expectThrows()` has been deprecated in favor of `Assertions.assertThrows()`.

===== New Features and Improvements

* Support for lazy and preemptive _timeouts_ with lambda expressions in `Assertions`. See
  examples in <<writing-tests-assertions,`AssertionsDemo`>> and consult the
  `{Assertions}` Javadoc for further details.
* New `assertIterableEquals()` assertion that checks that two Iterables are deeply equal (see
  Javadoc for details).
* New variants of `Assertions.assertAll()` that accept streams of executables (i.e.,
  `Stream<Executable>`).
* `Assertions.assertThrows()` now returns the thrown exception.
* `@BeforeAll` and `@AfterAll` may now be declared on static methods in interfaces.
* The JUnit 4 Rules `org.junit.rules.ExternalResource`, `org.junit.rules.Verifier`,
  `org.junit.rules.ExpectedException` including subclasses are now supported in JUnit Jupiter
  to facilitate migration of JUnit 4 codebases.


[[release-notes-5.0.0-m3-junit-vintage]]
==== JUnit Vintage

_No changes since 5.0.0-M2_
