[[release-notes-5.1.0-M1]]
=== 5.1.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/14?closed=1+[5.1 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* New `@SuiteDisplayName` annotation in the `junit-platform-suite-api` module for
  declaring a custom _display name_ for a test suite.
  - Supported by the `JUnitPlatform` runner for JUnit 4 in the `junit-platform-runner`
    module.
* When running on Java 9 or higher the `default` implementations of `getVersion()` and
  `getArtifactId()` in the `TestEngine` interface query the _Java Platform Module System_
  for this information.
* Class loading errors that occur during classpath scanning are now logged at `DEBUG`
  level (i.e., the `FINE` log level in `java.util.logging`) instead of as warnings.
* New `ModuleSelector` discovery selector for scanning Java 9 modules for test classes.
  - This is an alternative to the existing classpath scanning support.
* New console launcher option `--select-module <name>` or `-o <name>` for selecting Java
  9 modules for test discovery.
  - This is an alternative to the existing classpath scanning support.
* New console launcher option `--scan-modules` for scanning all resolved Java 9
  modules available on the boot layer configuration for test discovery.
  - This is an alternative to the existing classpath scanning support.
* The JUnit Platform Maven Surefire provider now runs all specified tests in a single
  test run, i.e. all registered `TestExecutionListeners` will receive a single `TestPlan`.
  Previously, a separate `TestPlan` was discovered and executed for each test class.


[[release-notes-5.1.0-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* New `getOrComputeIfAbsent(Class)` convenience method in `ExtensionContext.Store` that
  simplifies use cases where an extension wishes to store a single object of a given type
  (keyed by that type) in the `Store` and the object is created using the default
  constructor for that type.
  - For example, code such as
    `store.getOrComputeIfAbsent(X.class, key \-> new X(), X.class)` can now replaced with
    `store.getOrComputeIfAbsent(X.class)`.
* The `JupiterTestEngine` supports the new JUnit Platform `ModuleSelector` for selecting
  Java 9 modules.
  - This is an alternative to the existing classpath scanning support.


[[release-notes-5.1.0-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* The `VintageTestEngine` supports the new JUnit Platform `ModuleSelector` for selecting
  Java 9 modules.
  - This is an alternative to the existing classpath scanning support.
