[[release-notes-5.0.0-rc3]]
=== 5.0.0-RC3

*Date of Release:* August 24, 2017

*Scope:* Last release candidate before the first GA release.

WARNING: This is a pre-release and contains a few breaking changes. Please refer to the
<<running-tests-ide-intellij-idea,instructions>> above to use this version in a version of
IntelliJ IDEA that bundles an older milestone release.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/13?closed=1+[5.0 RC3] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-rc3-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* Source JARs no longer contain every source file twice.

===== Deprecations and Breaking Changes

* Revert change introduced in RC1: Test classes written in the Kotlin programming language
  are now executed with the same default test instance lifecycle mode as Java classes
  again ("per-method").


[[release-notes-5.0.0-rc3-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Source JARs no longer contain every source file twice.


[[release-notes-5.0.0-rc3-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* Source JARs no longer contain every source file twice.
