[[release-notes-5.0.0-m6]]
=== 5.0.0-M6

*Date of Release:* July 18, 2017

*Scope:* Sixth milestone release of JUnit 5 with a focus on Java 9 compatibility,
validation (e.g. tag syntax rules), and bug fixes.

WARNING: This is a milestone release and contains breaking changes. Please refer to the
<<running-tests-ide-intellij-idea,instructions>> above to use this version in a version of
IntelliJ IDEA that bundles an older milestone release.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/11?closed=1+[5.0 M6] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m6-java-9-compatibility]]
==== Java 9 Compatibility

The main runtime target of JUnit 5 is Java 8. Consequently, JUnit 5 artifacts do not ship
with compiled module descriptors for Java 9. However, since
<<release-notes-5.0.0-m5,milestone 5>> each artifact published by JUnit 5 ships with a
stable `Automatic-Module-Name` declared in its JAR manifest. This allows test module
authors to require well-known JUnit module names as in the following example.

```
module foo.bar {
  requires org.junit.jupiter.api;
}
```

It is typically sufficient to run tests on the class path: in this regard there are no
changes between Java 8 and 9. All command-line tools and IDEs continue to work with JUnit
5 _out of the box_ as long as they support the JUnit Platform. If your tool of choice
does not yet support the JUnit Platform, you may always resort to the `ConsoleLauncher`
or even to the executable `junit-platform-console-standalone` all-in-one jar.

Running JUnit Jupiter tests on the module path is implemented by
https://github.com/forax/pro[pro], a Java 9 compatible build tool.

*pro* supports both black-box and white-box testing. The former is used by module surface
tests that only access the exported bits of the application modules. The latter uses a
merged module descriptor technique that allows access to `protected` and package-private
types as well as non-exported packages.

Consult the https://github.com/forax/pro/tree/master/src/test/java[pro GitHub repository]
for test module examples: `integration.pro` is a black-box test module; whereas,
`com.github.forax.pro.api` and `com.github.forax.pro.helper` are white-box test modules.


[[release-notes-5.0.0-m6-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* All tags are now _trimmed_ in order to remove leading and trailing whitespace. This
  applies to any tag supplied _directly_ to the `Launcher` via `TagFilter.includeTags()`
  and `TagFilter.excludeTags()` or _indirectly_ via `@IncludeTags`, `@ExcludeTags`, the
  JUnit Platform Console Launcher, the JUnit Platform Gradle plugin, and the JUnit
  Platform Maven Surefire provider.

===== Deprecations and Breaking Changes

* All tags must now conform to the following syntax rules:
** A tag must not be `null` or _blank_.
** A _trimmed_ tag must not contain whitespace.
** A _trimmed_ tag must not contain ISO control characters.
* The `TagFilter.includeTags()`, `TagFilter.excludeTags()`, and `TestTag.create()`
  factory methods now throw a `PreconditionViolationException` if a supplied tag is not
  syntactically valid.
* The method `getDiscoveryFiltersByType` of `EngineDiscoveryRequest` has been renamed to
  `getFiltersByType`.
* The method `getSegments()` of `UniqueId` now returns an immutable list.
* The method `setSource` of `AbstractTestDescriptor` has been removed. There is an additional
  constructor with a `source` argument that can be used instead.

===== New Features and Improvements

* New `TestTag.isValid(String)` method for checking if a tag is syntactically valid.
* The `findAnnotation()` method in `AnnotationSupport` now searches on interfaces
  implemented by a class if the supplied element is a class.
* The following methods of `org.junit.platform.commons.util.ReflectionUtils` are now
  exposed via `org.junit.platform.commons.support.ReflectionSupport`:
** `public static Optional<Class<?>> loadClass(String name)`
** `public static Optional<Method> findMethod(Class<?> clazz, String methodName, String parameterTypeNames)`
** `public static Optional<Method> findMethod(Class<?> clazz, String methodName, Class<?>... parameterTypes)`
** `public static <T> T newInstance(Class<T> clazz, Object... args)`
** `public static Object invokeMethod(Method method, Object target, Object... args)`
** `public static List<Class<?>> findNestedClasses(Class<?> clazz, Predicate<Class<?>> predicate)`


[[release-notes-5.0.0-m6-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* All tags declared via `@Tag` are now trimmed in order to remove leading and trailing
  whitespace.
* All primitive array types (from `boolean[]` to `short[]`) are now supported as a
  return type of static argument providing methods for parameterized tests.

===== Deprecations and Breaking Changes

* A `void` return type is now enforced for `@Test` and lifecycle methods.

===== New Features and Improvements

* All `fail(...)` methods in `Assertions` can now be used to implement single-statement
  lambda expressions, thereby avoiding the need to implement a code block with an
  explicit return value.
* New `getRoot()` method in `ExtensionContext` lets extension authors easily access the
  top-most, _root_ extension context.
* New `getRequiredTestClass()`, `getRequiredTestInstance()`, and
  `getRequiredTestMethod()` convenience methods in the `ExtensionContext` API that
  provide extension authors shortcuts for retrieving the test class, test instance, and
  test method in use cases for which such elements are _required_ to be present.
* Type-level annotations such as `@TestInstance` and `@Disabled` may now be declared on
  test interfaces (a.k.a., _testing traits_).
* A _warning_ is now logged if more than one `TestDescriptor` is resolved for a single
  method. This helps to debug errors resulting from a method being simultaneously
  annotated with multiple competing annotations such as `@Test`, `@RepeatedTest`,
  `@ParameterizedTest`, `@TestFactory`, etc.
* `@Tag` declarations containing invalid tag syntax will now be logged as a warning but
  effectively ignored.


[[release-notes-5.0.0-m6-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* Added support for `Runners` that report events for tests not part of the `Description`
  tree such as Spock's `Sputnik` when used with `@Unroll`. Previously, such tests were not
  reported at all; now they are reported as dynamic tests.
