[[release-notes-5.0.0-m6]]
=== 5.0.0-M6

*Date of Release:* ❓

*Scope:* Sixth milestone release of JUnit 5 with a focus on Java 9 compatibility,
scenario tests, and additional extension APIs for JUnit Jupiter.

WARNING: This is a milestone release and contains breaking changes. Please refer to the
<<running-tests-ide-intellij-idea,instructions>> above to use this version in a version of
IntelliJ IDEA that bundles an older milestone release.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/11?closed=1+[5.0 M6] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m6-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* The method `getDiscoveryFiltersByType` of `EngineDiscoveryRequest` has been renamed to
  `getFiltersByType`.

===== New Features and Improvements

* ❓


[[release-notes-5.0.0-m6-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* All `fail(...)` methods in `Assertions` can now be used to implement single-statement
  lambda expressions, thereby avoiding the need to implement a code block with an explicit
  return value.


[[release-notes-5.0.0-m6-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* ❓
