[[release-notes-5.1.0-M1]]
=== 5.1.0-M1

*Date of Release:* ❓

*Scope:* Addition of Kotlin assertion helpers.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/14?closed=1+[5.1 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* The `junit-platform-surefire-provider` now requires `maven-surefire-plugin` version
  2.20.1 or higher.


[[release-notes-5.1.0-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* `ExpectedExceptionSupport` from the `junit-jupiter-migrationsupport` module no longer
  swallows exceptions if the test class does not declare a JUnit 4 `ExpectedException`
  rule.
  - Consequently, `@EnableRuleMigrationSupport` and `ExpectedExceptionSupport` may now be
    used without declaring an `ExpectedException` rule.

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* New Kotlin friendly assertions added as top-level functions in the `org.junit.jupiter.api` package.
** `assertAll` that takes `Stream<() -> Unit>` or `vararg () -> Unit`.
** `assertThrow` that uses Kotlin reified generics.


[[release-notes-5.1.0-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* ❓
