[[release-notes-5.1.0-M1]]
=== 5.1.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/14?closed=1+[5.1 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* The `junit-platform-surefire-provider` now requires `maven-surefire-plugin` version
  2.20.1 or higher.

===== New Features and Improvements

* New `@SuiteDisplayName` annotation in the `junit-platform-suite-api` module for
  declaring a custom _display name_ for a test suite.
  - Supported by the `JUnitPlatform` runner for JUnit 4 in the `junit-platform-runner`
    module.
* When running on Java 9 or higher the `default` implementations of `getVersion()` and
  `getArtifactId()` in the `TestEngine` interface query the _Java Platform Module System_
  for this information.
* Class loading errors that occur during classpath scanning are now logged at `DEBUG`
  level (i.e., the `FINE` log level in `java.util.logging`) instead of as warnings.


[[release-notes-5.1.0-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Trailing space characters in a CsvSource input line do not longer yield `null` values.

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* Failure messages for `assertTrue()` and `assertFalse()` in the `Assertions` class now
  include details about the expected and actual boolean values.
  - For example, the generated failure message for a call to `assertTrue(false)` is now
    "expected: <true> but was: <false>" instead of an empty string.
* Unused arguments are now omitted from display names of parameterized tests.


[[release-notes-5.1.0-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* ❓
