[[release-notes-5.1.0-M1]]
=== 5.1.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/14?closed=1+[5.1 M1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.1.0-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* Failed tests are now reported correctly with Maven Surefire for test engines that do
  not use `MethodSource` (e.g. Spek).
* Tests that write to `System.out` or `System.err`, in particular via a logging
  framework, are now consistently reported correctly when executed with a non-zero
  `forkCount` with Maven Surefire.

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* New `@SuiteDisplayName` annotation in the `junit-platform-suite-api` module for
  declaring a custom _display name_ for a test suite.
  - Supported by the `JUnitPlatform` runner for JUnit 4 in the `junit-platform-runner`
    module.
* When running on Java 9 or higher the `default` implementations of `getVersion()` and
  `getArtifactId()` in the `TestEngine` interface query the _Java Platform Module System_
  for this information.
* Class loading errors that occur during classpath scanning are now logged at `DEBUG`
  level (i.e., the `FINE` log level in `java.util.logging`) instead of as warnings.
* New `ModuleSelector` discovery selector for scanning Java 9 modules for test classes.
  - This is an alternative to the existing classpath scanning support.
* New console launcher option `--select-module <name>` or `-o <name>` for selecting Java
  9 modules for test discovery.
  - This is an alternative to the existing classpath scanning support.
* New console launcher option `--scan-module-path` for scanning all resolved Java 9
  modules available on the boot layer configuration for test discovery.
  - This is an alternative to the existing classpath scanning support.
* The JUnit Platform Maven Surefire provider now supports the `redirectTestOutputToFile`
  Surefire feature.
* The JUnit Platform Maven Surefire provider now ignores empty strings supplied via
  `<includeTags/>`, `<groups/>`, `<excludeTags/>`, and `<excludedGroups/>`.


[[release-notes-5.1.0-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Trailing spaces in a `@CsvSource` or `@CsvFileSource` input line no longer yield `null`
  values.
* `@EnableRuleMigrationSupport` previously failed to recognize `@Rule` methods that
  returned a subtype of one of the supported `TestRule` types. Moreover, it mistakenly
  instantiated some rules declared using methods multiple times. Now, once enabled, it
  will instantiate all declared rules (fields _and_ methods) exactly once and call them
  in the same order used by JUnit 4.
* Previously, disabled test classes were eagerly instantiated when `Lifecycle.PER_CLASS`
  was used. Now, `ExecutionCondition` evaluation always takes place before test class
  instantiation.
* The `junit-jupiter-migrationsupport` module no longer incorrectly attempts to register
  the `JupiterTestEngine` via the `ServiceLoader` mechanism, thereby allowing it to be
  used as a module on the Java 9 module-path.

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* Failure messages for `assertTrue()` and `assertFalse()` in the `Assertions` class now
  include details about the expected and actual boolean values.
  - For example, the generated failure message for a call to `assertTrue(false)` is now
    "expected: <true> but was: <false>" instead of an empty string.
* If a parameterized test does not consume all arguments supplied to it via argument
  sources, the unconsumed arguments are no longer included in the display name.
* New `getOrComputeIfAbsent(Class)` convenience method in `ExtensionContext.Store` that
  simplifies use cases where an extension wishes to store a single object of a given type
  (keyed by that type) in the `Store` and the object is created using the default
  constructor for that type.
  - For example, code such as
    `store.getOrComputeIfAbsent(X.class, key \-> new X(), X.class)` can now replaced with
    `store.getOrComputeIfAbsent(X.class)`.
* The `JupiterTestEngine` supports the new JUnit Platform `ModuleSelector` for selecting
  Java 9 modules.
  - This is an alternative to the existing classpath scanning support.


[[release-notes-5.1.0-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* The `VintageTestEngine` supports the new JUnit Platform `ModuleSelector` for selecting
  Java 9 modules.
  - This is an alternative to the existing classpath scanning support.
