[[release-notes-5.0.0-rc1]]
=== 5.0.0-RC1

*Date of Release:* ❓

*Scope:* Final bug fixes and documentation improvements before 5.0 GA

WARNING: This is a pre-release and should only contain bug fixes. Please refer to the
<<running-tests-ide-intellij-idea,instructions>> above to use this version in a version of
IntelliJ IDEA that bundles an older milestone release.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/9?closed=1+[5.0 RC1] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-rc1-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* Removed deprecated method `execute(LauncherDiscoveryRequest)` from `Launcher` class.
  The removed method was replaced in milestone 4 by method
  `execute(LauncherDiscoveryRequest, TestExecutionListener...)`.


[[release-notes-5.0.0-rc1-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓


[[release-notes-5.0.0-rc1-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓
