[[release-notes-5.0.0-m4]]
=== 5.0.0-M4

*Date of Release:* ❓

*Scope:* Fourth milestone release of JUnit 5 with a focus on parameterized tests,
enhanced dynamic tests, and documentation.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/7?closed=1+[5.0 M4] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m4-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* The JUnit Platform Gradle plugin now adds its dependencies with a fixed version (same as plugin
  version) instead of a dynamic versioning scheme (was `1.+`) by default to ensure reproducible
  builds.
* All `findMethods()` implementations in `ReflectionUtils` no longer return synthetic methods.
  Shadowed https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.2[override-equal]
  methods are also no longer included in the result collection.

===== Deprecations and Breaking Changes

* Removed deprecated `selectNames()` name-based discovery selector from
  `DiscoverySelectors` in favor of the dedicated `selectPackage(String)`,
  `selectClass(String)`, and `selectMethod(String)` methods.
* `ClassNameFilter.includeClassNamePattern` was removed, please use
  `ClassNameFilter.includeClassNamePatterns` instead.
* `@IncludeClassNamePattern` was removed, please use `@IncludeClassNamePatterns` instead.
* `--hide-details` option of the `ConsoleLauncher` is deprecated, use `--details none` instead.
* The ZIP distribution containing the console launcher is no longer provided. It is replaced
  by an executable standalone JAR distribution. For details, see "New Features" section below.

===== New Features

* Custom `TestExecutionListener` implementations can now be registered automatically via
  Java's `ServiceLoader` mechanism.
* New `getGroupId()`, `getArtifactId()`, and `getVersion()` default methods in the
  `TestEngine` API for debugging and reporting purposes. By default, package attributes
  (i.e., typically from JAR manifest attributes) are used to determine the artifact ID
  and version; whereas, the group ID is empty by default. Consult the Javadoc for
  `{TestEngine}` for details.
* Logging information for discovered test engines has been enhanced to include the group
  ID, artifact ID, and version of each test engine if available via the `getGroupId()`,
  `getArtifactId()`, and `getVersion()` methods.
* The `--scan-classpath` option of the `ConsoleLauncher` now allows to scan JAR files for tests
  when they are supplied as explicit arguments (see <<running-tests-console-launcher-options>>).
* The new `--details <Details>` option of the `ConsoleLauncher` now allows to select an output
  details mode for when tests are executed. Use one of: `none`, `flat`, `tree` or `verbose`. If
  `none` is selected, then only the summary and test failures are shown (see
  <<running-tests-console-launcher-options>>).
* An executable `junit-platform-console-standalone-{platform-version}.jar` artifact containing
  the Jupiter and Vintage test engines with all dependencies is generated by the default build
  process, stored in `junit-platform-console-standalone/build/libs` and published to the Maven
  Central https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone
  [repository]. It provides hassle-free usage of JUnit 5 in projects that manually manage their
  dependencies similar to the
  https://github.com/junit-team/junit4/wiki/Download-and-Install#plain-old-jar[plain-old JAR]
  known from JUnit 4.
* New `--exclude-classname` (`--N`) option added to the `ConsoleLauncher` accepting a regular
  expression to exclude those classes whose fully qualified names match. When this option is
  repeated, all patterns will be combined using OR semantics.
* Introduce JUnit Platform support package `org.junit.platform.commons.support` which contains
  maintained utility methods handling `Annotation`, reflection and classpath scanning tasks.
  `TestEngine` and `Extension` authors are encouraged to use these supported methods
  to align the behaviour with the JUnit Platform.

[[release-notes-5.0.0-m4-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Fix bug that prevented discovery of two or more methods of the same class.
* Enforce correct execution order of overridden `@BeforeEach`/`@AfterEach` methods when declared
  at multiple class hierarchy levels. It's now always `super.before`, `this.before`, `this.test`,
  `this.after` and `super.after`, even when the compiler added synthetic methods.

===== Deprecations and Breaking Changes

* Removed deprecated `Assertions.expectThrows()` method in favor of `Assertions.assertThrows()`.
* `ExtensionContext.Namespace`s with the same parts but in a different order are no longer considered
  equal to each other.

===== New Features and Improvements

* `Assertions.assertThrows()` now uses canonical names for exception types when
  generating assertion failure messages.
* `TestInstancePostProcessors` registered on test methods are now invoked.
* There are two new signatures `Assertions.fail` - `Assertions.fail(Throwable cause)` and
  `Assertions.fail(String message, Throwable cause)`.


[[release-notes-5.0.0-m4-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* Fix bug that caused only the last failure of a test to be reported, e.g. when using the
  `ErrorCollector` rule only the last failed check was reported. Now, all failures are reported
  using an `org.opentest4j.MultipleFailuresError`.
