[[release-notes-5.0.0-m5]]
=== 5.0.0-M5

*Date of Release:* ❓

*Scope:* Fifth milestone release of JUnit 5 with a focus on ❓.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/8?closed=1+[5.0 M5] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m5-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* A `NullPointerException` thrown by `ConsoleLauncher` in `Details.TREE` mode was fixed
  by falling back to printing throwable's `toString()` representation.
* `DefaultLauncher` now catches and warns about exceptions generated by an engine in its
  discovery and execution phases. Other engines are processed normally.

===== Deprecations and Breaking Changes

* The deprecated `--hide-details` option of the `ConsoleLauncher` has been removed; use
  `--details none` instead.
* The following previously deprecated methods have been removed.
  - `junit-platform-engine`: `Node.execute(EngineExecutionContext)`
  - `junit-platform-commons`: `ReflectionUtils.findAllClassesInClasspathRoot(Path, Predicate, Predicate)`
* The `junit-platform-surefire-provider` now requires `maven-surefire-plugin` version
  2.20 or higher.


===== New Features and Improvements

* The JUnit Platform Gradle plugin task `junitPlatformTest` can now be accessed
  directly during the configuration phase of a build.
* When a `TestEngine` is discovered via Java's `ServiceLoader` mechanism, an attempt
  will now be made to determine the location from which the engine class was loaded,
  and if the location URL is available, it will be logged at configuration-level.


[[release-notes-5.0.0-m5-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* In order to ensure the _composability_ of all supported extension APIs in JUnit
  Jupiter, several methods in existing APIs have been renamed.
** See <<release-notes-5.0.0-m5-migration-extension-api>> for details.
* The `arguments()` method in the `ArgumentsProvider` API in the `junit-jupiter-params`
  module has been renamed to `provideArguments()`.
* The `create()` factory method in `ObjectArrayArguments` in the `junit-jupiter-params`
  module has been renamed to `arguments()`.

[[release-notes-5.0.0-m5-migration-extension-api]]
.Extension API Migration
[cols="42,15,45"]
|===
| Extension API                           | Old Name     | New Name

| `ParameterResolver`                     | `supports()` | `supportsParameter()`
| `ParameterResolver`                     | `resolve()`  | `resolveParameter()`
| `ContainerExecutionCondition`           | `evaluate()` | `evaluateContainerExecutionCondition()`
| `TestExecutionCondition`                | `evaluate()` | `evaluateTestExecutionCondition()`
| `TestTemplateInvocationContextProvider` | `supports()` | `supportsTestTemplate()`
| `TestTemplateInvocationContextProvider` | `provide()`  | `provideTestTemplateInvocationContexts()`
|===

===== New Features and Improvements

* `Assertions.assertAll()` now tracks exceptions of any type (as opposed to only tracking
  exceptions of type `AssertionError`), unless the exception is a _blacklisted_ exception
  in which case it will be immediately rethrown.


[[release-notes-5.0.0-m5-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* The `VintageTestEngine` no longer filters out test classes declared as static member
  classes, since they are valid JUnit 4 test classes.
* The `VintageTestEngine` no longer attempts to execute abstract classes as test classes.
  Instead, a warning is now logged stating that such classes are excluded.
