[[release-notes-5.0.0-m5]]
=== 5.0.0-M5

*Date of Release:* ❓

*Scope:* Fifth milestone release of JUnit 5 with a focus on ❓.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/8?closed=1+[5.0 M5] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m5-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* The deprecated `execute(LauncherDiscoveryRequest)` method has been removed from the
  `org.junit.platform.launcher.Launcher` API; use
  `execute(LauncherDiscoveryRequest, TestExecutionListener...)` instead.
* The deprecated `--hide-details` option of the `ConsoleLauncher` has been removed; use
  `--details none` instead.

===== New Features and Improvements

* ❓


[[release-notes-5.0.0-m5-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* The `arguments()` method in the `ArgumentsProvider` API in the `junit-jupiter-params`
  module has been renamed to `provideArguments()`.
* The `create()` factory method in `ObjectArrayArguments` in the `junit-jupiter-params`
  module has been renamed to `arguments()`.

===== New Features and Improvements

* ❓


[[release-notes-5.0.0-m5-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* Fixed a bug where static member classes were incorrectly being filtered out.
  They are now considered valid JUnit Vintage test classes.
