[[release-notes-5.0.0-rc3]]
=== 5.0.0-RC3

*Date of Release:* August 23, 2017

*Scope:* Configuration parameters and bug fixes.

WARNING: This is a pre-release and contains a few breaking changes. Please refer to the
<<running-tests-ide-intellij-idea,instructions>> above to use this version in a version of
IntelliJ IDEA that bundles an older milestone or release candidate.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/13?closed=1+[5.0 RC3] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-rc3-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* Source JARs no longer contain every source file twice.
* The Maven Surefire provider now reports a failed test with a cause that is not an
  instance of `AssertionError` as an _error_ instead of a _failure_ for compatibility
  reasons.

===== New Features and Improvements

* _Configuration parameters_ can now be supplied in a number of new ways:
** via a file named `junit-platform.properties` in the root of the class path. See
   <<running-tests-config-params>> for details.
** via the `--config` command-line option when using the
   <<running-tests-console-launcher,Console Launcher>>.
** via the `configurationParameter` or `configurationParameters` DSL when using the
   <<running-tests-build-gradle-config-params,Gradle plugin>>.
** via the `configurationParameters` property when using the
   <<running-tests-build-maven-config-params,Maven Surefire provider>>.


[[release-notes-5.0.0-rc3-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* Source JARs no longer contain every source file twice.
* `ExecutionContext.Store.getOrComputeIfAbsent()` now looks for values in a grandparent
  context (and recursively in its parents) before computing a value.
* `ExecutionContext.Store.getOrComputeIfAbsent()` is now thread safe.
* The `JupiterTestEngine` no longer attempts to resolve a Unique ID selected via one of
  the `DiscoverySelectors.selectUniqueId()` methods if the Unique ID belongs to a
  different test engine.

===== Deprecations and Breaking Changes

* Revert change introduced in RC1: test classes written in the Kotlin programming
  language are now executed with the same default test instance lifecycle mode as Java
  classes again (i.e., "per-method").
* The `junit.conditions.deactivate` configuration parameter has been renamed to
  `junit.jupiter.conditions.deactivate`.
* The `junit.extensions.autodetection.enabled` configuration parameter has been renamed
  to `junit.jupiter.extensions.autodetection.enabled`.
* The default, global extension namespace constant in `ExtensionContext` has been renamed
  from `Namespace.DEFAULT` to `Namespace.GLOBAL`.
* The default `getStore()` method has been removed from the `ExtensionContext` interface.
  To access the global store, use an explicit call to `getStore(Namespace.GLOBAL)`
  instead.

===== New Features and Improvements

* The _default_ test instance lifecycle mode can now be set via a _configuration
  parameter_ or JVM system property named `junit.jupiter.testinstance.lifecycle.default`.
  See <<writing-tests-test-instance-lifecycle-changing-default>> for details.
* When using `@CsvSource` or `@CsvFileSource` in a parameterized test, if the CSV parser
  does not read any character from the input, and the input is within quotes, an empty
  string `""` is returned instead of `null`.


[[release-notes-5.0.0-rc3-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* Source JARs no longer contain every source file twice.
* It is now possible to select a single method in a JUnit 4 parameterized test class via
  the `selectMethod()` variants in `DiscoverySelectors`.
