[[release-notes-5.0.0-m3]]
=== 5.0.0-M3

*Date of Release:* September 30, 2016

*Scope:* Third milestone release of JUnit 5 with a focus on JUnit 4 interoperability,
additional discovery selectors, and documentation.

[[release-notes-5.0.0-m3-summary]]
==== Summary of Changes

The following is a list of global changes. For details regarding changes specific to the
Platform, Jupiter, and Vintage, consult the dedicated subsections below. For a complete
list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/6?closed=1+[5.0 M3] milestone page in the JUnit repository
on GitHub.

* ❓


[[release-notes-5.0.0-m3-junit-platform]]
===== JUnit Platform

====== Bug Fixes

* ❓

====== Deprecations and Breaking Changes

* `ClasspathSelector` has been renamed to `ClasspathRootSelector`.

====== New Features

* New `selectClasspathResource(String)` method in `DiscoverySelectors` for selecting
  _classpath resources_ such as XML or JSON files by name, where the name is a
  `/`-separated path name for the resource within the current classpath. A `TestEngine`
  can retrieve such values by querying registered instances of `ClasspathResourceSelector`.
* The `selectMethod(String)` method in `DiscoverySelectors` now supports selection of
  a _fully qualified method name_ for a method that accepts parameters -- for example,
  `"org.example.TestClass#testMethod(org.junit.jupiter.api.TestInfo)"`.
* The `TestExecutionSummary` used by the `ConsoleLauncher` and the JUnit Platform Gradle
  plugin now includes statistics for all container events in addition to test events.


[[release-notes-5.0.0-m3-junit-jupiter]]
===== JUnit Jupiter

====== Bug Fixes

* The `JupiterTestEngine` now supports selection of test methods via their unique ID for
  methods that accept arrays or primitive types as parameters.

====== New Features

* Support for lazy and preemptive _timeouts_ with lambda expressions in `Assertions`. See
  examples in <<writing-tests-assertions,`AssertionsDemo`>> and consult the
  `{Assertions}` Javadoc for further details.


[[release-notes-5.0.0-m3-junit-vintage]]
===== JUnit Vintage

_No changes since 5.0.0-M2_
