[[release-notes-5.0.0-m6]]
=== 5.0.0-M6

*Date of Release:* ❓

*Scope:* Sixth milestone release of JUnit 5 with a focus on Java 9 compatibility and
additional extension APIs for JUnit Jupiter.

WARNING: This is a milestone release and contains breaking changes. Please refer to the
<<running-tests-ide-intellij-idea,instructions>> above to use this version in a version of
IntelliJ IDEA that bundles an older milestone release.

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit5-repo}+/milestone/11?closed=1+[5.0 M6] milestone page in the JUnit repository
on GitHub.


[[release-notes-5.0.0-m6-junit-platform]]
==== JUnit Platform

===== Bug Fixes

* All tags are now trimmed in order to remove leading and trailing whitespace. This
  applies to any tag supplied _directly_ to the `Launcher` via `TagFilter.includeTags()`
  and `TagFilter.excludeTags()` or _indirectly_ via `@IncludeTags`, `@ExcludeTags`, the
  JUnit Platform Console Launcher, the JUnit Platform Gradle plugin, and the JUnit
  Platform Maven Surefire provider. Furthermore, blank tags are now ignored.

===== Deprecations and Breaking Changes

* The method `getDiscoveryFiltersByType` of `EngineDiscoveryRequest` has been renamed to
  `getFiltersByType`.
* The method `getSegments()` of `UniqueId` now returns an immutable list.

===== New Features and Improvements

* The `findAnnotation()` method in `AnnotationSupport` now searches on interfaces
  implemented by a class if the supplied element is a class.

* The following methods of `org.junit.platform.commons.util.ReflectionUtils` are now
  exposed via `org.junit.platform.commons.support.ReflectionSupport`:
** `public static Optional<Class<?>> loadClass(String name)`
** `public static Optional<Method> findMethod(Class<?> clazz, String methodName, String parameterTypeNames)`
** `public static Optional<Method> findMethod(Class<?> clazz, String methodName, Class<?>... parameterTypes)`
** `public static <T> T newInstance(Class<T> clazz, Object... args)`
** `public static Object invokeMethod(Method method, Object target, Object... args)`
** `public static List<Class<?>> findNestedClasses(Class<?> clazz, Predicate<Class<?>> predicate)`

[[release-notes-5.0.0-m6-junit-jupiter]]
==== JUnit Jupiter

===== Bug Fixes

* All tags declared via `@Tag` are now trimmed in order to remove leading and trailing
  whitespace. Furthermore, blank tags are now ignored.

===== Deprecations and Breaking Changes

* A `void` return type is now enforced for `@Test` and lifecycle methods.

===== New Features and Improvements

* All `fail(...)` methods in `Assertions` can now be used to implement single-statement
  lambda expressions, thereby avoiding the need to implement a code block with an
  explicit return value.
* New `getRoot()` method in `ExtensionContext` lets extension authors easily access the
  top-most, _root_ extension context.
* New `getRequiredTestClass()`, `getRequiredTestInstance()`, and
  `getRequiredTestMethod()` convenience methods in the `ExtensionContext` API that
  provide extension authors shortcuts for retrieving the test class, test instance, and
  test method in use cases for which such elements are _required_ to be present.
* Type-level annotations such as `@TestInstance` and `@Disabled` may now be declared on
  test interfaces (a.k.a., _testing traits_).


[[release-notes-5.0.0-m6-junit-vintage]]
==== JUnit Vintage

===== Bug Fixes

* ❓

===== Deprecations and Breaking Changes

* ❓

===== New Features and Improvements

* ❓
