[[running-tests]]
== Running Tests

=== IDE Support

At this stage there is no direct support for running JUnit 5 tests in IDEs. However, the
JUnit team provides two intermediate solutions so that you can go ahead and try out the
current snapshot today. You can use the <<running-tests-console-runner>> or execute JUnit
5 tests with a <<running-tests-junit4-runner,JUnit 4 based Runner>>.

=== Build Support

==== Gradle

The JUnit team has developed a very basic `JUnit5Plugin` that lets you run JUnit 4 and
JUnit 5 tests in Gradle builds. See `build.gradle` in the `{junit5-gradle-consumer}`
project for an example of the plugin in action.

===== Enabling the `JUnit5Plugin`

To use the `JUnit5Plugin`, you first need to configure `build.gradle` as follows.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
buildscript {
	repositories {
		maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
	}
	dependencies {
		classpath 'org.junit:junit-gradle:{junit-version}'
	}
}

apply plugin: 'org.junit.gen5.gradle'
----

===== Configuring the `JUnit5Plugin`

Once the `JUnit5Plugin` has been applied, you can configure it as follows.

_Caution:_ These options are very likely to change as we continue to work towards the
final release.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
junit5 {
	version '{junit-version}'
	logManager 'org.apache.logging.log4j.jul.LogManager'
	runJunit4 true
	matchClassName '.*Test'
	includeTag 'fast'
}

----

Setting `logManager` instructs the `JUnit5Plugin` to set the `java.util.logging.manager`
system property to the supplied fully qualified class name of the `java.util.logging.LogManager`
implementation to use. The above example demonstrates how to configure log4j as the
`LogManager`.

Setting `runJunit4` to `true` instructs the `JUnit5Plugin` to run JUnit 4 based tests as
well. However, you will still need to configure a `testCompile` dependency on JUnit 4 in
your project similar to the following.

[source,java,indent=0]
[subs="verbatim"]
----
dependencies {
	testCompile('junit:junit:4.12')
}
----

If you supply a _tag_ to the `includeTag` configuration method, the `JUnit5Plugin` will
only run JUnit 5 based tests that are _tagged_ accordingly via the `@Tag` annotation.

===== Using the `JUnit5Plugin`

Once the `JUnit5Plugin` has been applied and configured, you have a new `junit5Test` task
at your disposal.

Invoking `gradlew clean junit5Test` (or `gradlew clean check`) from the command line will
execute all tests within the project whose class names match the regular expression
supplied via `matchClassName`.

Executing the `junit5Test` task in the `{junit5-gradle-consumer}` project results in
output similar to the following:

[subs="none"]
----
:junit5Test

Test run finished after 50 ms
[         3 tests found     ]
[         2 tests started   ]
[         1 tests skipped   ]
[         0 tests aborted   ]
[         2 tests successful]
[         0 tests failed    ]

BUILD SUCCESSFUL
----

If a test fails, the build will fail with output similar to the following:

[subs="none"]
----
:junit5Test

Test failures (1):
  junit5:com.example.project.SecondTest:mySecondTest
    com.example.project.SecondTest#mySecondTest
    => Exception: 2 is not equal to 1 ==> expected:<2> but was:<1>

Test run finished after 50 ms
[         3 tests found     ]
[         3 tests started   ]
[         0 tests skipped   ]
[         0 tests aborted   ]
[         2 tests successful]
[         1 tests failed    ]

:junit5Test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':junit5Test'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
----

*Note*: the _exit value_ corresponds to the number of _tests failed_.

===== Current Limitations of the `JUnit5Plugin`

* Even though the build will fail if a test fails, the results will not be included in
  the test report generated by Gradle.
* With `runJunit4` set to `true`, the `JUnit5Plugin` takes over the responsibility of
  running JUnit 4 tests, and the `check` Gradle task will no longer depend on the Gradle
  `test` task. Consequently, the results for JUnit 4 tests will not be included in the
  test report generated by Gradle.

==== Maven

The JUnit team has developed a very basic provider for Maven Surefire that lets you run
JUnit 4 and JUnit 5 tests via `mvn test`. The `pom.xml` file in the
`{junit5-maven-consumer}` project demonstrates how to use it and can serve as a starting
point.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<build>
		<plugins>
			...
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<dependencies>
					<dependency>
						<groupId>org.junit</groupId>
						<artifactId>surefire-junit5</artifactId>
						<version>{junit-version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
	...
----

[[running-tests-console-runner]]
=== Console Runner

The `{ConsoleRunner}` is a command-line Java application that lets you run JUnit 4 and
JUnit 5 tests and prints test execution results to the console.

Here's an example of its output:

[subs="none"]
----
Test execution started. Number of static tests: 2
Engine started: junit5
Test started:     My 1st JUnit 5 test! 😎 [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test succeeded:   My 1st JUnit 5 test! 😎 [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test skipped:     mySecondTest [junit5:com.example.project.SecondTest#mySecondTest()]
                  => Exception:   Skipped test method [void com.example.project.SecondTest.mySecondTest()] due to failed condition
Engine finished: junit5
Test execution finished.

Test run finished after 29 ms
[         2 tests found     ]
[         1 tests started   ]
[         1 tests skipped   ]
[         0 tests aborted   ]
[         1 tests successful]
[         0 tests failed    ]
----

==== Options

_Caution:_ These options are very likely to change as we continue to work towards the
final release.

[subs="none"]
----
Non-option arguments:
Test classes, methods, or packages to execute. If --all|-a has been provided,
  arguments can list all classpath roots that should be considered for test
  scanning, or none if the full classpath should be scanned.

Option                       Description
------                       -----------
-a, --all                    Run all tests
-p, --classpath              Provide additional classpath entries -- for example,
                               for adding engines and their dependencies.
-n, --filter-classname       Provide a regular expression to include only
                               classes whose fully qualified names match.
                               By default any class name is accepted, and
                               thus all classes with tests are included.
-t, --require-tag            Provide a tag to be required in the test run. This
                               option can be repeated.
-T, --exclude-tag            Provide a tag to be excluded from the test run. This
                               option can be repeated.
-e, --require-engine         Provide the ID of an engine to be required in the test
                               run. This option can be repeated.
-E, --exclude-engine         Provide the ID of an engine to be excluded from the
                               test run. This option can be repeated.
-r, --xml-reports-dir        Enable XML report output into a specified local
                               directory (will be created if it does not
                               exist).
-x, --enable-exit-code       Exit process with number of failing tests as
                               exit code.
-C, --disable-ansi-colors    Disable colored output (not supported by all
                               terminals).
-D, --hide-details           Hide details while tests are being executed.
                               Only show the summary and test failures.
-h, --help                   Display help information.
----


[[running-tests-junit4-runner]]
=== Using JUnit 4 to Run JUnit 5 Tests

The `JUnit5` runner lets you run JUnit 5 tests with JUnit 4. This way you can run JUnit 5
tests in IDEs and build tools that only know about JUnit 4. As soon as we add reporting
features to JUnit 5 that JUnit 4 does not have, the runner will only be able to support a
subset of the JUnit 5 functionality. But for the time being the `JUnit5` runner is an
easy way to get started.

==== Setup

You need the following artifacts and their dependencies on the classpath. See
<<dependency-metadata>> for details regarding group IDs, artifact IDs, and
versions.

* `junit5-api` in _test_ scope: API for writing tests, including `@Test`, etc.
* `junit4-runner` in _test_ scope: location of the `JUnit5` runner
* `junit5-engine` in _test runtime_ scope: implementation of the Engine API for JUnit 5

==== Single Test Class

One way to use the `JUnit5` runner is to annotate a JUnit 5 test class with
`@RunWith(JUnit5.class)` directly. Please note that the test methods are annotated with
`org.junit.gen5.api.Test` (JUnit 5), not `org.junit.Test` (JUnit 4). Moreover, in this
case the test class must be `public` because; otherwise, the IDEs won't recognize it as a
test class.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/JUnit4ClassDemo.java[tags=user_guide]
----

==== Test Suite

If you have multiple JUnit 5 test classes you can create a test suite.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/JUnit4SuiteDemo.java[tags=user_guide]
----

The `JUnit4SuiteDemo` will discover and run all tests in the `example` package
and its subpackages.

There are more configuration options for discovering and filtering tests than just
`@Packages`. Please consult the
{javadoc-root}/org/junit/gen5/junit4/runner/package-summary.html[Javadoc] or the source
code for the `{JUnit5-Runner}` runner for further details.
