[[running-tests]]
== Running Tests

[[running-tests-ide]]
=== IDE Support

==== IntelliJ IDEA

IntelliJ IDEA supports running tests on the JUnit Platform since version 2016.2.
For details please see the https://blog.jetbrains.com/idea/2016/08/using-junit-5-in-intellij-idea/[post on the IntelliJ IDEA blog].

==== Other IDEs

At the time of this writing, there is no direct support for running tests on the JUnit
Platform within IDEs other than IntelliJ IDEA.
However, the JUnit team provides two intermediate solutions so that
you can go ahead and try out JUnit 5 within your IDE today. You can use the
<<running-tests-console-launcher>> manually or execute tests with a
<<running-tests-junit-platform-runner,JUnit 4 based Runner>>.

[[running-tests-build]]
=== Build Support

[[running-tests-build-gradle]]
==== Gradle

The JUnit team has developed a very basic Gradle plugin that allows you to run any kind
of test that is supported by a `TestEngine` (e.g., JUnit 3, JUnit 4, JUnit Jupiter, Specsy,
etc.). See `build.gradle` in the `{junit5-gradle-consumer}` project for an example of the
plugin in action.

[[running-tests-build-gradle-junit-enable]]
===== Enabling the JUnit Gradle Plugin

To use the JUnit Gradle plugin, you first need to make sure that you are running Gradle
2.5 or higher. Once you've done that, you can configure `build.gradle` as follows.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
buildscript {
	repositories {
		mavenCentral()
		// The following is only necessary if you want to use SNAPSHOT releases.
		// maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
	}
	dependencies {
		classpath 'org.junit.platform:junit-platform-gradle-plugin:{platform-version}'
	}
}

apply plugin: 'org.junit.platform.gradle.plugin'
----

[[running-tests-build-gradle-junit-configure]]
===== Configuring the JUnit Gradle Plugin

Once the JUnit Gradle plugin has been applied, you can configure it as follows.

WARNING: These options are very likely to change as we continue to work towards the
final release.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
junitPlatform {
	platformVersion 1.0
	logManager 'org.apache.logging.log4j.jul.LogManager'
	reportsDir file('build/test-results/junit-platform') // this is the default
	// enableStandardTestTask true
	// selectors (optional)
	// filters (optional)
}
----

Setting `logManager` instructs the JUnit Gradle plugin to set the
`java.util.logging.manager` system property to the supplied fully qualified class name of
the `java.util.logging.LogManager` implementation to use. The above example demonstrates
how to configure log4j as the `LogManager`.

By default, the JUnit Gradle plugin disables the standard Gradle `test` task, but this be
overridden via the `enableStandardTestTask` flag.

[[running-tests-build-gradle-selectors]]
===== Configuring Selectors

By default, the plugin will scan your project's output directories for tests. However, you can
specify which tests to execute explicitly using the `selectors` extension element.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
junitPlatform {
	// ...
	selectors {
		uris 'file:///foo.txt', 'http://example.com/'
		uri 'foo:resource' <1>
		files 'foo.txt', 'bar.csv'
		file 'qux.json' <2>
		directories 'foo/bar', 'bar/qux'
		directory 'qux/bar' <3>
		packages 'com.acme.foo', 'com.acme.bar'
		aPackage 'com.example.app' <4>
		classes 'com.acme.Foo', 'com.acme.Bar'
		aClass 'com.example.app.Application' <5>
		methods 'com.acme.Foo#a', 'com.acme.Foo#b'
		method 'com.example.app.Application#run(java.lang.String[])' <6>
		resources '/bar.csv', '/foo/input.json'
		resource '/com/acme/my.properties' <7>
	}
	// ...
}
----
<1> URIs
<2> Local files
<3> Local directories
<4> Packages
<5> Classes, fully qualified
<6> Methods, fully qualified (see {DiscoverySelectors_selectMethod})
<7> Classpath resources

[[running-tests-build-gradle-filters]]
===== Configuring Filters

You can configure filters for the test plan by using the `filters` extension. By default, all
engines and tags are included in the test plan. Only the default `includeClassNamePattern`
(`{standard-include-class-name-pattern}`) is applied. You can overwrite its value as in the
following example. When you specify multiple patterns, they are combined using OR semantics.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
junitPlatform {
	// ...
	filters {
		engines {
			include 'junit-jupiter'
			// exclude 'junit-vintage'
		}
		tags {
			include 'fast', 'smoke'
			// exclude 'slow', 'ci'
		}
		packages {
			include 'com.sample.included1', 'com.sample.included2'
			// exclude 'com.sample.excluded1', 'com.sample.excluded2'
		}
		includeClassNamePattern '.*Spec'
		includeClassNamePatterns '.*Test', '.*Tests'
	}
	// ...
}
----

If you supply a _Test
Engine ID_ via `engines {include ...}` or `engines {exclude ...}`, the JUnit Gradle
plugin will only run tests for the desired test engines. Similarly, if you supply a _tag_
via `tags {include ...}` or `tags {exclude ...}`, the JUnit Gradle plugin will only run
tests that are _tagged_ accordingly (e.g., via the `@Tag` annotation for JUnit Jupiter based
tests). The same applies to package names that can be included or excluded using
`packages {include ...}` or `packages {exclude ...}`.

[[running-tests-build-gradle-engines-configure]]
===== Configuring Test Engines

In order to have the JUnit Gradle plugin run any tests at all, a `TestEngine`
implementation must be on the classpath.

To configure support for JUnit Jupiter based tests, configure a `testCompile` dependency on the
JUnit Jupiter API and a `testRuntime` dependency on the JUnit Jupiter `TestEngine` implementation
similar to the following.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
dependencies {
	testCompile("org.junit.jupiter:junit-jupiter-api:{jupiter-version}")
	testRuntime("org.junit.jupiter:junit-jupiter-engine:{jupiter-version}")
}
----

The JUnit Gradle plugin can run JUnit 4 based tests as long as you configure a
`testCompile` dependency on JUnit 4 and a `testRuntime` dependency on the JUnit Vintage
`TestEngine` implementation similar to the following.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
dependencies {
	testCompile("junit:junit:{junit4-version}")
	testRuntime("org.junit.vintage:junit-vintage-engine:{vintage-version}")
}
----

[[running-tests-build-gradle-junit-using]]
===== Using the JUnit Gradle Plugin

Once the JUnit Gradle plugin has been applied and configured, you have a new
`junitPlatformTest` task at your disposal.

Invoking `gradlew clean junitPlatformTest` (or `gradlew clean test`) from the command
line will execute all tests within the project whose class names match the regular
expression supplied via `includeClassNamePattern` (defaults to `{standard-include-class-name-pattern}`).

Executing the `junitPlatformTest` task in the `{junit5-gradle-consumer}` project results
in output similar to the following:

[subs="none"]
----
:junitPlatformTest

Test run finished after 93 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         3 tests found           ]
[         1 tests skipped         ]
[         2 tests started         ]
[         0 tests aborted         ]
[         2 tests successful      ]
[         0 tests failed          ]

BUILD SUCCESSFUL
----

If a test fails, the build will fail with output similar to the following:

[subs="none"]
----
:junitPlatformTest

Test failures (1):
  JUnit Jupiter:SecondTest:mySecondTest()
    MethodSource [className = 'com.example.project.SecondTest', methodName = 'mySecondTest', methodParameterTypes = '']
    => Exception: 2 is not equal to 1 ==> expected: <2> but was: <1>

Test run finished after 99 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
[         0 containers aborted    ]
[         3 containers successful ]
[         0 containers failed     ]
[         3 tests found           ]
[         0 tests skipped         ]
[         3 tests started         ]
[         0 tests aborted         ]
[         2 tests successful      ]
[         1 tests failed          ]

:junitPlatformTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':junitPlatformTest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
----

NOTE: The _exit value_ is `1` if any containers or tests failed; otherwise, it is `0`.

.Current Limitations of the JUnit Gradle Plugin
WARNING: The results of any tests run via the JUnit Gradle plugin will not be included
         in the standard test report generated by Gradle; however, the test results can
		 be aggregated. See the `reportsDir` property of the plugin.

[[running-tests-build-maven]]
==== Maven

The JUnit team has developed a very basic provider for Maven Surefire that lets you run
JUnit 4 and JUnit Jupiter tests via `mvn test`. The `pom.xml` file in the
`{junit5-maven-consumer}` project demonstrates how to use it and can serve as a starting
point.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<build>
		<plugins>
			...
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<dependencies>
					<dependency>
						<groupId>org.junit.platform</groupId>
						<artifactId>junit-platform-surefire-provider</artifactId>
						<version>{platform-version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
	...
----

[[running-tests-build-maven-engines-configure]]
===== Configuring Test Engines

In order to have Maven Surefire run any tests at all, a `TestEngine` implementation must be added
to the runtime classpath.

To configure support for JUnit Jupiter based tests, configure a `test` dependency on the JUnit
Jupiter API and add the JUnit Jupiter `TestEngine` implementation to the dependencies of the
`maven-surefire-plugin` similar to the following.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<build>
		<plugins>
			...
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<dependencies>
					<dependency>
						<groupId>org.junit.platform</groupId>
						<artifactId>junit-platform-surefire-provider</artifactId>
						<version>{platform-version}</version>
					</dependency>
					<dependency>
						<groupId>org.junit.jupiter</groupId>
						<artifactId>junit-jupiter-engine</artifactId>
						<version>{jupiter-version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
	...
	<dependencies>
		...
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>{jupiter-version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	...
----

The JUnit Platform Surefire Provider can run JUnit 4 based tests as long as you configure a
`test` dependency on JUnit 4 and add the JUnit Vintage `TestEngine` implementation to the
dependencies of the `maven-surefire-plugin` similar to the following.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<build>
		<plugins>
			...
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<dependencies>
					<dependency>
						<groupId>org.junit.platform</groupId>
						<artifactId>junit-platform-surefire-provider</artifactId>
						<version>{platform-version}</version>
					</dependency>
					...
					<dependency>
						<groupId>org.junit.vintage</groupId>
						<artifactId>junit-vintage-engine</artifactId>
						<version>{vintage-version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
	...
	<dependencies>
		...
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>{junit4-version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	...
----

[[running-tests-build-maven-filter-tags]]
===== Filtering by tag

You can filter tests by tags using the following configuration properties:

- to include use either `groups` or `includeTags`
- to exclude use either `excludedGroups` or `excludeTags`

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<build>
		<plugins>
			...
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<configuration>
			        <properties>
						<includeTags>acceptance</includeTags>
			            <excludeTags>integration, regression</excludeTags>
			        </properties>
			    </configuration>
				<dependencies>
					...
				</dependencies>
			</plugin>
		</plugins>
	</build>
	...
----

==== Ant

The JUnit team has developed a very basic Ant plugin that allows you to run any kind
of test that is supported by `TestEngine` (e.g., JUnit 3, JUnit 4, JUnit Jupiter, Specsy,
etc.).

[[running-tests-build-ant-junit-enable]]
===== Enabling the JUnit Ant Plugin

To use the JUnit Ant plugin, you first need to make sure that you have Apache Ant installed.
Once installed, you can configure `build.xml` as follows.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
    ...
    <path id="taskdef.classpath">
		<fileset dir="libs">
			<include name="junit-platform-ant-plugin-${ant.plugin.version}.jar"/>
			<include name="junit-platform-console-${junit.platform.version}.jar"/>
			<include name="junit-platform-launcher-${junit.platform.version}.jar"/>
		</fileset>
	</path>
    ...
    <taskdef name="junit" classname="org.junit.platform.ant.plugin.JUnitPlatformPlugin">
		<classpath refid="taskdef.classpath" />
	</taskdef>
    ...
----

[[running-tests-build-ant-junit-configure]]
===== Configuring the JUnit Ant Plugin

Once the JUnit Ant plugin has been applied, you can configure it as follows.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<junit reportsdir="reportsDirectory" hidedetails="false">
		<!-- optional scanclasspath -->
		<scanclasspath>
			...
		</scanclasspath>
		<!-- optional filters -->
		<filters>
			...
		</filters>
		<!-- optional selectors -->
		<selectors>
			...
		</selectors>
	</junit>
	...
----

[[running-tests-build-ant-selectors]]
===== Configuring Selectors

By default, the plugin will scan your project's classpath i.e. `$CLASSPATH` environment variable.
However, you can specify which tests to execute explicitly using the `selectors` extension element.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<selectors
		uris="u:foo,u:bar"
		uri="u:qux" <1>
		files="foo.txt,bar.csv"
		file="qux.json" <2>
		directories="foo/bar,bar/qux"
		directory="qux/bar" <3>
		packages="com.acme.foo,com.acme.bar"
		package="com.example.app" <4>
		classes="com.acme.Foo,com.acme.Bar"
		class="com.example.app.Application" <5>
		methods="com.acme.Foo#a,com.acme.Foo#b"
		method="com.example.app.Application#run(java.lang.String[])" <6>
		resources="/bar.csv,/foo/input.json"
		resource="/com/acme/my.properties"> <7>
	</selectors>
	...
----
<1> URIs
<2> Local files
<3> Local directories
<4> Packages
<5> Classes, fully qualified
<6> Methods, fully qualified
<7> Classpath resources

[[running-tests-build-ant-filters]]
===== Configuring Filters

You can configure filters for the test plan by using the `filters` element. By default, all
engines, packages, and tags are included in the test plan. When you specify multiple patterns,
they are combined using OR semantics.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<filters includeclassnamepattern=".*Spec" includeclassnamepatterns=".*TestCase,.*Tests">
		<packages include="com.include.p1,com.include.p2" exclude="com.exclude.p1,com.exclude.p2"/>
		<engines include="junit-jupiter,junit-vintage" exclude="junit-engine1,junit-engine2"/>
		<tags include="fast,module1" exclude="slow,module2"/>
	</filters>
	...
----

If you supply a _Test
Engine ID_ via `<engines include="..."/>` or `<engines exclude="..."/>`, the JUnit Ant
plugin will only run tests for the desired test engines. Similarly, if you supply a _tag_
via `<tags include="..."/>` or `<tags exclude="..."/>`, the JUnit Ant plugin will only run
tests that are _tagged_ accordingly (e.g., via the `@Tag` annotation for JUnit Jupiter based
tests). The same applies to package names that can be included or excluded using
`<packages include="..."/>` or `<packages exclude="..."/>`.

[[running-tests-build-ant-engines-configure]]
===== Configuring Test Engines

In order to have the JUnit Ant plugin run any tests at all, a `TestEngine`
implementation must be on the classpath i.e. `$CLASSPATH` environment variable.

To configure support for JUnit Jupiter based tests, make sure that the JUnit Jupiter `TestEngine`
is in your classpath environment variable along with other additional classpath and dependencies
similar to the following:

[subs="none"]
----
export CLASSPATH="build/classes/main:build/classes/test:libs/junit-platform-commons-1.0.0-SNAPSHOT.jar:libs/junit-platform-engine-1.0.0-SNAPSHOT.jar:libs/junit-jupiter-engine-5.0.0-SNAPSHOT.jar:libs/junit-jupiter-api-5.0.0-SNAPSHOT.jar:libs/junit-vintage-engine-4.12.0-SNAPSHOT.jar:libs/junit-4.12.jar:libs/opentest4j-1.0.0-M1.jar:libs/hamcrest-core-1.3.jar"
----

Then, configure your `javac` ant task's classpath reference to use JUnit Jupiter API:

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<path id="compile.test.classpath">
		<fileset dir="libs">
			<include name="junit-jupiter-api-${junit.jupiter.version}.jar"/>
			<include name="junit-4.12.jar"/>
		</fileset>
		<pathelement location="build/classes/main"/>
	</path>

	<target name="compile.src">
        <mkdir dir="build/classes/main"/>
        <javac srcdir="src/main/java" destdir="build/classes/main"/>
    </target>

	<target name="compile.test" depends="compile.src">
        <mkdir dir="build/classes/test" />
        <javac srcdir="src/test/java" destdir="build/classes/test"
        	classpathref="compile.test.classpath"/>
    </target>
	...
----

[[running-tests-build-ant-junit-using]]
===== Running the JUnit Ant Plugin

Executing the `junit` task results in output similar to the following:

[subs="none"]
----
[junit] org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
[junit] INFO: Discovered TestEngines with IDs: [junit-jupiter (group ID: org.junit.jupiter, artifact ID: junit-jupiter-engine, version: 5.0.0-SNAPSHOT), junit-vintage (group ID: org.junit.vintage, artifact ID: junit-vintage-engine, version: 4.12.0-SNAPSHOT)]
[junit]
[junit] Test run finished after 210 ms
[junit] [         3 containers found      ]
[junit] [         0 containers skipped    ]
[junit] [         3 containers started    ]
[junit] [         0 containers aborted    ]
[junit] [         3 containers successful ]
[junit] [         0 containers failed     ]
[junit] [         3 tests found           ]
[junit] [         1 tests skipped         ]
[junit] [         2 tests started         ]
[junit] [         0 tests aborted         ]
[junit] [         2 tests successful      ]
[junit] [         0 tests failed          ]
[junit]

BUILD SUCCESSFUL
----

If a test fails, the build will fail with output similar to the following:

[subs="none"]
----
[junit] org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
[junit] INFO: Discovered TestEngines with IDs: [junit-jupiter (group ID: org.junit.jupiter, artifact ID: junit-jupiter-engine, version: 5.0.0-SNAPSHOT), junit-vintage (group ID: org.junit.vintage, artifact ID: junit-vintage-engine, version: 4.12.0-SNAPSHOT)]
[junit]
[junit] Failures (1):
[junit]   JUnit Jupiter:SecondTest:mySecondTest()
[junit]     MethodSource [className = 'com.example.project.SecondTest', methodName = 'mySecondTest', methodParameterTypes = '']
[junit]     => org.opentest4j.AssertionFailedError: 2 is not equal to 1 ==> expected: <2> but was: <1>
[junit]
[junit] Test run finished after 210 ms
[junit] [         3 containers found      ]
[junit] [         0 containers skipped    ]
[junit] [         3 containers started    ]
[junit] [         0 containers aborted    ]
[junit] [         3 containers successful ]
[junit] [         0 containers failed     ]
[junit] [         3 tests found           ]
[junit] [         0 tests skipped         ]
[junit] [         2 tests started         ]
[junit] [         0 tests aborted         ]
[junit] [         2 tests successful      ]
[junit] [         1 tests failed          ]
[junit]
----

[[running-tests-console-launcher]]
=== Console Launcher

The `{ConsoleLauncher}` is a command-line Java application that lets you launch
the JUnit Platform from the console. For example, it can be used to run JUnit
Vintage and JUnit Jupiter tests and print test execution results to the console.

Here's an example of its output:

[subs="none"]
----
Test execution started. Number of static tests: 2
Engine started: junit-jupiter
Test started:     My 1st JUnit 5 test! 😎 [junit-jupiter:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test succeeded:   My 1st JUnit 5 test! 😎 [junit-jupiter:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test skipped:     mySecondTest [junit-jupiter:com.example.project.SecondTest#mySecondTest()]
                  => Exception:   Skipped test method [void com.example.project.SecondTest.mySecondTest()] due to failed condition
Engine finished: junit-jupiter
Test execution finished.

Test run finished after 29 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         2 tests found           ]
[         1 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         0 tests failed          ]
----

.Exit Code
NOTE: The `{ConsoleLauncher}` exits with a status code of `1` if any containers or tests
failed. Otherwise the exit code is `0`.

[[running-tests-console-launcher-options]]
==== Options

WARNING: These options are very likely to change as we continue to work towards the
final release.

[subs="specialchars"]
----
Option                                        Description
------                                        -----------
-h, --help                                    Display help information.
--disable-ansi-colors                         Disable ANSI colors in output (not
                                                supported by all terminals).
--hide-details                                Hide details while tests are being
                                                executed. Only show the summary and test
                                                failures.
--class-path, --classpath, --cp <Path:        Provide additional classpath entries --
  path1:path2:...>                              for example, for adding engines and
                                                their dependencies. This option can be
                                                repeated.
--reports-dir <Path>                          Enable report output into a specified
                                                local directory (will be created if it
                                                does not exist).
--scan-class-path, --scan-classpath [Path:    Scan all directories on the classpath or
  path1:path2:...]                              explicit classpath roots. Without
                                                arguments, only directories on the
                                                system classpath as well as additional
                                                classpath entries supplied via -cp
                                                (directories and JAR files) are scanned.
                                                Explicit classpath roots that are not on
                                                the classpath will be silently ignored.
                                                This option can be repeated.
-u, --select-uri <URI>                        Select a URI for test discovery. This
                                                option can be repeated.
-f, --select-file <String>                    Select a file for test discovery. This
                                                option can be repeated.
-d, --select-directory <String>               Select a directory for test discovery.
                                                This option can be repeated.
-p, --select-package <String>                 Select a package for test discovery. This
                                                option can be repeated.
-c, --select-class <String>                   Select a class for test discovery. This
                                                option can be repeated.
-m, --select-method <String>                  Select a method for test discovery. This
                                                option can be repeated.
-r, --select-resource <String>                Select a classpath resource for test
                                                discovery. This option can be repeated.
-n, --include-classname <String>              Provide a regular expression to include
                                                only classes whose fully qualified names
                                                match. To avoid loading classes
                                                unnecessarily, the default pattern only
                                                includes class names that end with
                                                "Test" or "Tests". When this option is
                                                repeated, all patterns will be combined
                                                using OR semantics. (default: ^.*Tests?$)
--include-package <String>                    Provide a package to be included in the
                                                test run. This option can be repeated.
--exclude-package <String>                    Provide a package to be excluded from the
                                                test run. This option can be repeated.
-t, --include-tag <String>                    Provide a tag to be included in the test
                                                run. This option can be repeated.
-T, --exclude-tag <String>                    Provide a tag to be excluded from the test
                                                run. This option can be repeated.
-e, --include-engine <String>                 Provide the ID of an engine to be included
                                                in the test run. This option can be
                                                repeated.
-E, --exclude-engine <String>                 Provide the ID of an engine to be excluded
                                                from the test run. This option can be
                                                repeated.
----


[[running-tests-junit-platform-runner]]
=== Using JUnit 4 to Run the JUnit Platform

The `JUnitPlatform` runner is a JUnit 4 based `Runner` which enables you to run any test
whose programming model is supported on the JUnit Platform in a JUnit 4 environment --
for example, a JUnit Jupiter test class.

Annotating a class with `@RunWith(JUnitPlatform.class)` allows it to be run with IDEs and
build systems that support JUnit 4 but do not yet support the JUnit Platform directly.

NOTE: Since the JUnit Platform has features that JUnit 4 does not have, the runner is
only able to support a subset of the JUnit Platform functionality, especially with regard
to reporting (see <<running-tests-junit-platform-runner-technical-names>>). But for the
time being the `JUnitPlatform` runner is an easy way to get started.

[[running-tests-junit-platform-runner-setup]]
==== Setup

You need the following artifacts and their dependencies on the classpath. See
<<dependency-metadata>> for details regarding group IDs, artifact IDs, and
versions.

===== Explicit Dependencies

* `junit-{junit4-version}.jar` in _test_ scope: to run tests using JUnit 4.
* `junit-platform-runner` in _test_ scope: location of the `JUnitPlatform` runner
* `junit-jupiter-api` in _test_ scope: API for writing tests, including `@Test`, etc.
* `junit-jupiter-engine` in _test runtime_ scope: implementation of the Engine API for JUnit Jupiter

===== Transitive Dependencies

* `junit-platform-launcher` in _test_ scope
* `junit-platform-engine` in _test_ scope
* `junit-platform-commons` in _test_ scope
* `opentest4j` in _test_ scope

[[running-tests-junit-platform-runner-technical-names]]
==== Display Names vs. Technical Names

By default, _display names_ will be used for test artifacts; however, when the
`JUnitPlatform` runner is used to execute tests with a build tool such as Gradle or
Maven, the generated test report often needs to include the _technical names_ of test
artifacts — for example, fully qualified class names — instead of shorter display names
like the simple name of a test class or a custom display name containing special
characters. To enable technical names for reporting purposes, simply declare the
`@UseTechnicalNames` annotation alongside `@RunWith(JUnitPlatform.class)`.

[[running-tests-junit-platform-runner-single-test]]
==== Single Test Class

One way to use the `JUnitPlatform` runner is to annotate a test class with
`@RunWith(JUnitPlatform.class)` directly. Please note that the test methods in the
following example are annotated with `org.junit.jupiter.api.Test` (JUnit Jupiter), not
`org.junit.Test` (JUnit Vintage). Moreover, in this case the test class must be `public`;
otherwise, IDEs won't recognize it as a test class.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/JUnit4ClassDemo.java[tags=user_guide]
----

[[running-tests-junit-platform-runner-test-suite]]
==== Test Suite

If you have multiple test classes you can create a test suite as can be seen in the
following example.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/JUnit4SuiteDemo.java[tags=user_guide]
----

The `JUnit4SuiteDemo` will discover and run all tests in the `example` package
and its subpackages. By default, it will only include test classes whose names match the
pattern `{standard-include-class-name-pattern}`.

.Additional Configuration Options
NOTE: There are more configuration options for discovering and filtering tests than just
`@SelectPackages`. Please consult the
{javadoc-root}/org/junit/platform/runner/package-summary.html[Javadoc] for further
details.
