[[running-tests]]
== Running Tests

=== IDE Support

At the time of this writing there is no direct support for running JUnit Jupiter tests in IDEs.
However, the JUnit team provides two intermediate solutions so that you can go ahead and
try out JUnit 5 within your IDE today. You can use the <<running-tests-console-launcher>>
or execute JUnit Jupiter tests with a <<running-tests-junit-platform-runner,JUnit 4 based Runner>>.

=== Build Support

==== Gradle

The JUnit team has developed a very basic Gradle plugin that allows you to run any kind
of test that is supported by a `TestEngine` (e.g., JUnit 3, JUnit 4, JUnit Jupiter, Specsy,
etc.). See `build.gradle` in the `{junit5-gradle-consumer}` project for an example of the
plugin in action.

===== Enabling the JUnit Gradle Plugin

To use the JUnit Gradle plugin, you first need to configure `build.gradle` as follows.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
buildscript {
	repositories {
		mavenCentral()
		// The following is only necessary if you want to use SNAPSHOT releases.
		// maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
	}
	dependencies {
		classpath 'org.junit.platform:junit-platform-gradle-plugin:{platform-version}'
	}
}

apply plugin: 'org.junit.platform.gradle.plugin'
----

===== Configuring the JUnit Gradle Plugin

Once the JUnit Gradle plugin has been applied, you can configure it as follows.

_Caution:_ These options are very likely to change as we continue to work towards the
final release.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
junitPlatform {
	platformVersion 1.0
	logManager 'org.apache.logging.log4j.jul.LogManager'
	reportsDir "build/test-results/junit-platform" // this is the default
	// enableStandardTestTask true
	engines {
		include 'junit-jupiter'
		// exclude 'junit-vintage'
	}
	tags {
		include 'fast', 'smoke'
		// exclude 'slow', 'ci'
	}
	includeClassNamePattern '.*Tests'
}
----

Setting `logManager` instructs the JUnit Gradle plugin to set the
`java.util.logging.manager` system property to the supplied fully qualified class name of
the `java.util.logging.LogManager` implementation to use. The above example demonstrates
how to configure log4j as the `LogManager`.

By default, the JUnit Gradle plugin disables the standard Gradle `test` task, but this be
overridden via the `enableStandardTestTask` flag.

By default all engines and tags are included in the test plan. If you supply a _Test
Engine ID_ via `engines {include ...}` or `engines {exclude ...}`, the JUnit Gradle
plugin will only run tests for the desired test engines. Similarly, if you supply a _tag_
via `tags {include ...}` or `tags {exclude ...}`, the JUnit Gradle plugin will only run
tests that are _tagged_ accordingly (e.g., via the `@Tag` annotation for JUnit Jupiter based
tests).

===== Configuring Test Engines

In order to have the JUnit Gradle plugin run any tests at all, a `TestEngine`
implementation must be on the classpath.

To configure support for JUnit Jupiter based tests, configure a `testCompile` dependency on the
JUnit Jupiter API and a `testRuntime` dependency on the JUnit Jupiter `TestEngine` implementation
similar to the following.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
dependencies {
	testCompile("org.junit.jupiter:junit-jupiter-api:{jupiter-version}")
	testRuntime("org.junit.jupiter:junit-jupiter-engine:{jupiter-version}")
}
----

The JUnit Gradle plugin can run JUnit 4 based tests as long as you configure a
`testCompile` dependency on JUnit 4 and a `testRuntime` dependency on the JUnit 4
TestEngine implementation similar to the following.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
dependencies {
	testCompile("junit:junit:4.12")
	testRuntime("org.junit.vintage:junit-vintage-engine:{vintage-version}")
}
----

===== Using the JUnit Gradle Plugin

Once the JUnit Gradle plugin has been applied and configured, you have a new
`junitPlatformTest` task at your disposal.

Invoking `gradlew clean junitPlatformTest` (or `gradlew clean test`) from the command
line will execute all tests within the project whose class names match the regular
expression supplied via `includeClassNamePattern`.

Executing the `junitPlatformTest` task in the `{junit5-gradle-consumer}` project results
in output similar to the following:

[subs="none"]
----
:junitPlatformTest

Test run finished after 93 ms
[         3 tests found     ]
[         1 tests skipped   ]
[         2 tests started   ]
[         0 tests aborted   ]
[         2 tests successful]
[         0 tests failed    ]

BUILD SUCCESSFUL
----

If a test fails, the build will fail with output similar to the following:

[subs="none"]
----
:junitPlatformTest

Test failures (1):
  JUnit Jupiter:SecondTest:mySecondTest()
    JavaMethodSource [javaClass = 'com.example.project.SecondTest', javaMethodName = 'mySecondTest', javaMethodParameterTypes = '']
    => Exception: 2 is not equal to 1 ==> expected: <2> but was: <1>

Test run finished after 99 ms
[         3 tests found     ]
[         0 tests skipped   ]
[         3 tests started   ]
[         0 tests aborted   ]
[         2 tests successful]
[         1 tests failed    ]

:junitPlatformTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':junitPlatformTest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
----

*Note*: the _exit value_ corresponds to the number of _tests failed_.

===== Current Limitations of the JUnit Gradle Plugin

* The results of any tests run via the JUnit Gradle plugin will not be included in the
  standard test report generated by Gradle; however, the test results can be aggregated.
  See the `reportsDir` property of the plugin.

==== Maven

The JUnit team has developed a very basic provider for Maven Surefire that lets you run
JUnit 4 and JUnit Jupiter tests via `mvn test`. The `pom.xml` file in the
`{junit5-maven-consumer}` project demonstrates how to use it and can serve as a starting
point.

[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	...
	<build>
		<plugins>
			...
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<dependencies>
					<dependency>
						<groupId>org.junit</groupId>
						<artifactId>junit-platform-surefire-provider</artifactId>
						<version>{platform-version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
	...
----

[[running-tests-console-launcher]]
=== Console Launcher

The `{ConsoleLauncher}` is a command-line Java application that lets you launch
the JUnit Platform from the console. For example, it can be used to run JUnit
Vintage and JUnit Jupiter tests and print test execution results to the console.

Here's an example of its output:

[subs="none"]
----
Test execution started. Number of static tests: 2
Engine started: junit-jupiter
Test started:     My 1st JUnit 5 test! 😎 [junit-jupiter:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test succeeded:   My 1st JUnit 5 test! 😎 [junit-jupiter:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test skipped:     mySecondTest [junit-jupiter:com.example.project.SecondTest#mySecondTest()]
                  => Exception:   Skipped test method [void com.example.project.SecondTest.mySecondTest()] due to failed condition
Engine finished: junit-jupiter
Test execution finished.

Test run finished after 29 ms
[         2 tests found     ]
[         1 tests started   ]
[         1 tests skipped   ]
[         0 tests aborted   ]
[         1 tests successful]
[         0 tests failed    ]
----

The `{ConsoleLauncher}` exits with status code 0 if no test failed. In case of at
least one failing test the status code is 1.

==== Options

_Caution:_ These options are very likely to change as we continue to work towards the
final release.

[subs="none"]
----
Non-option arguments:
Test classes, methods, or packages to execute. If --all|-a has been provided,
  arguments can list all classpath roots that should be considered for test
  scanning, or none if the full classpath should be scanned.

Option                       Description
------                       -----------
-a, --all                    Run all tests
-p, --classpath              Provide additional classpath entries -- for example,
                               for adding engines and their dependencies.
-n, --include-classname      Provide a regular expression to include only
                               classes whose fully qualified names match.
                               By default any class name is accepted, and
                               thus all classes with tests are included.
-t, --include-tag            Provide a tag to be included in the test run. This
                               option can be repeated.
-T, --exclude-tag            Provide a tag to be excluded from the test run. This
                               option can be repeated.
-e, --include-engine         Provide the ID of an engine to be included in the test
                               run. This option can be repeated.
-E, --exclude-engine         Provide the ID of an engine to be excluded from the
                               test run. This option can be repeated.
-r, --xml-reports-dir        Enable XML report output into a specified local
                               directory (will be created if it does not
                               exist).
-C, --disable-ansi-colors    Disable colored output (not supported by all
                               terminals).
-D, --hide-details           Hide details while tests are being executed.
                               Only show the summary and test failures.
-h, --help                   Display help information.
----


[[running-tests-junit-platform-runner]]
=== Using JUnit 4 to Run the JUnit Platform

The `JUnitPlatform` runner is a JUnit 4 based `Runner` which enables you to run any test
whose programming model is supported on the JUnit Platform in a JUnit 4 environment --
for example, a JUnit Jupiter test class.

Annotating a class with `@RunWith(JUnitPlatform.class)` allows it to be run with IDEs and
build systems that support JUnit 4 but do not yet support the JUnit Platform directly.

Since the JUnit Platform has features that JUnit 4 does not have, the runner is only able
to support a subset of the JUnit Platform functionality, especially with regard to
reporting. But for the time being the `JUnitPlatform` runner is an easy way to get
started.

==== Setup

You need the following artifacts and their dependencies on the classpath. See
<<dependency-metadata>> for details regarding group IDs, artifact IDs, and
versions.

* `junit-jupiter-api` in _test_ scope: API for writing tests, including `@Test`, etc.
* `junit-platform-runner` in _test_ scope: location of the `JUnitPlatform` runner
* `junit-jupiter-engine` in _test runtime_ scope: implementation of the Engine API for JUnit Jupiter

==== Single Test Class

One way to use the `JUnitPlatform` runner is to annotate a test class with
`@RunWith(JUnitPlatform.class)` directly. Please note that the test methods in the
following example are annotated with `org.junit.jupiter.api.Test` (JUnit Jupiter), not
`org.junit.Test` (JUnit Vintage). Moreover, in this case the test class must be `public`;
otherwise, IDEs won't recognize it as a test class.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/JUnit4ClassDemo.java[tags=user_guide]
----

==== Test Suite

If you have multiple test classes you can create a test suite as can be seen in the
following example.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/JUnit4SuiteDemo.java[tags=user_guide]
----

The `JUnit4SuiteDemo` will discover and run all tests in the `example` package
and its subpackages.

There are more configuration options for discovering and filtering tests than just
`@SelectPackages`. Please consult the
{javadoc-root}/org/junit/platform/runner/package-summary.html[Javadoc] or the source
code for the `{JUnitPlatform-Runner}` runner for further details.
