[[writing-tests]]
== Writing Tests

[source,java,indent=0]
[subs="verbatim"]
.A first test case
----
include::{testDir}/example/FirstJUnit5Tests.java[tags=user_guide]
----

[[annotations]]
=== Annotations

JUnit 5 supports the following annotations for configuring tests and extending the framework.

All core annotations are located in the `{api-package}` package in the `junit5-api`
module.

[cols="20,80"]
|===
| Annotation         | Description

| `@Test`            | Denotes that a method is a test method. Unlike JUnit 4's `@Test` annotation, this annotation does not declare any attributes, since test extensions in JUnit 5 operate based on their own dedicated annotations.
| `@DisplayName`     | Declares a custom display name for the test class or test method
| `@BeforeEach`      | Denotes that the annotated method should be executed _before_ *each* `@Test` method in the current class or class hierarchy
| `@AfterEach`       | Denotes that the annotated method should be executed _after_ *each* `@Test` method in the current class or class hierarchy
| `@BeforeAll`       | Denotes that the annotated method should be executed _before_ *all* `@Test` methods in the current class or class hierarchy; analogous to JUnit 4's `@BeforeClass`. Such methods must be `static`.
| `@AfterAll`        | Denotes that the annotated method should be executed _after_ *all* `@Test` methods in the current class or class hierarchy; analogous to JUnit 4's `@AfterClass`. Such methods must be `static`.
| `@Nested`          | Denotes that the annotated class is a nested, non-static test class. Due to restrictions of the Java language, `@BeforeAll` and `@AfterAll` methods cannot be used in a `@Nested` test class.
| `@Tag` and `@Tags` | Used to declare _tags_ for filtering tests, either at the class or method level; analogous to test groups in TestNG or Categories in JUnit 4
| `@Disabled`        | Used to _disable_ a test class or test method; analogous to JUnit 4's `@Ignore`
| `@ExtendWith`      | Used to register custom <<extension-model, extensions>> to the framework.
|===

[[meta-annotations]]
==== Meta-Annotations and Composed Annotations

JUnit 5 annotations can be used as _meta-annotations_. That means that you can define
your own _composed annotation_ that will automatically _inherit_ the semantics of its
meta-annotations.

For example, instead of copying and pasting `@Tag("fast")` throughout your code base (see
<<tagging-and-filtering>>), you can create a custom _composed annotation_ named `@Fast`
as follows. `@Fast` can then be used as a drop-in replacement for `@Tag("fast")`.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/Fast.java[tags=user_guide]
----


=== Standard Test Class

[source,java,indent=0]
[subs="verbatim"]
.A standard test case
----
include::{testDir}/example/StandardTests.java[tags=user_guide]
----

Notice that neither the test class nor the test method need to be `public`.


=== Custom Names

Test classes and test methods can declare a custom name -- with spaces, special
characters, and even emojis -- that will be displayed by test runners and test reporting:

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/DisplayNameDemo.java[tags=user_guide]
----


=== Assertions

JUnit 5 comes with many of the assertion methods that JUnit 4 has and adds a few that
lend themselves well to being used with Java 8 lambdas. All JUnit 5 assertions are static
methods in the `{Assertions}` class.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/AssertionsDemo.java[tags=user_guide]
----


=== Assumptions

JUnit 5 comes with a subset of the assumption methods that JUnit 4 provides and adds a
few that lend themselves well to being used with Java 8 lambdas. All JUnit 5 assumptions
are static methods in the `{Assumptions}` class.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/AssumptionsDemo.java[tags=user_guide]
----


=== Disabling Tests

Here's a disabled test case:

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/DisabledClassDemo.java[tags=user_guide]
----

And here's a test case with a disabled test method:

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/DisabledTestsDemo.java[tags=user_guide]
----

[[tagging-and-filtering]]
=== Tagging and Filtering

Test classes and methods can be tagged. Those tags can later be used to filter
<<running-tests,test discovery and execution>>:

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/TaggingDemo.java[tags=user_guide]
----



=== Nested Tests

Nested tests give the test writer more capabilities to express the relationship among
several group of tests. Here's an elaborate example:

[source,java,indent=0]
[subs="verbatim"]
.Nested test suite for testing a stack
----
include::{testDir}/example/TestingAStack.java[tags=user_guide]
----

Notice that _only non-static inner classes_ can serve as nested tests. Nesting can be
arbitrarily deep, and those inner classes can be considered as full members of the test
class family with one exception: `@BeforeAll` and `@AfterAll` do not work, because Java
does not allow static members in non-static inner classes.

=== Dependency Injection for Constructors and Methods

In all prior JUnit versions, test constructors or methods were not allowed to have
parameters (at least not with the standard `Runner` implementations). As one of the major
changes in JUnit 5, both test constructors and methods are now permitted to have
parameters. This allows for greater flexibility and enables _Dependency Injection_ for
constructors and methods.

`{ParameterResolver}` defines the API for test extensions that wish to _dynamically_
resolve parameters at runtime. If a test constructor or a `@Test`, `@BeforeEach`,
`@AfterEach`, `@BeforeAll`, or `@AfterAll` method accepts a parameter, the parameter must
be resolved at runtime by a registered `ParameterResolver`.

There are currently two built-in resolvers that are registered automatically.

* `{TestInfoParameterResolver}`: if a method parameter is of type `{TestInfo}`, the
  `TestInfoParameterResolver` will supply an instance of `TestInfo` corresponding to the
  current test as the value for the parameter. The `TestInfo` can then be used to retrieve
  information about the current test such as the test's display name, the test class, the
  test method, or associated tags. The display name is either a technical name, such as
  the name of the test class or test method, or a custom name configured via `@DisplayName`.
+
`{TestInfo}` acts as a drop-in replacement for the `TestName`
rule from JUnit 4. Here is an example of its usage:

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/TestInfoDemo.java[tags=user_guide]
----

* `{TestReporterParameterResolver}`: if a method parameter is of type `{TestReporter}`, the
  `TestReporterParameterResolver` will supply an instance of `TestReporter`.
  The `TestReporter` can be used to publish additional data about the current test run.
  The data can be consumed through `{TestExecutionListener}.reportingEntryPublished()` and thus
  be viewed by IDEs or included in reports.
+
In JUnit 5 you should use `TestReporter` where
you used to print information to `stdout` or `stderr` in JUnit 4.
Using `@RunWith(JUnit5.class)` will even output all reported entries to `stdout`.

[source,java,indent=0]
[subs="verbatim"]
----
include::{testDir}/example/TestReporterDemo.java[tags=user_guide]
----


Other parameter resolvers must be explicitly enabled by registering a <<extension-model,
test extension>> via `@ExtendWith`.

* Check out the `{MockitoExtension}` for an example of a `{ParameterResolver}`. While not
  intended to be production-ready, it demonstrates the simplicity and expressiveness of
  both the extension model and the parameter resolution process. `MyMockitoTest`
  demonstrates how to inject Mockito mocks into `@BeforeEach` and `@Test` methods.

[source,java,indent=0]
[subs="verbatim"]
----
import org.junit.gen5.api.*;

import static org.mockito.Mockito.when;
import com.example.mockito.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class MyMockitoTest {

	@BeforeEach
	void init(@InjectMock Person person) {
		when(person.getName()).thenReturn("Dilbert");
	}

	@Test
	void simpleTestWithInjectedMock(@InjectMock Person person) {
		assertEquals("Dilbert", person.getName());
	}

}
----

=== Interface Default Methods

JUnit 5 allows tests to be declared in interface default methods. One possible
application of this feature is to write tests for interface contracts. For example, you
can write tests for how implementations of `Object.equals` or `Comparable.compareTo`
should behave as follows:

[source,java]
[subs="verbatim"]
----
include::{testDir}/example/defaultmethods/Testable.java[tags=user_guide]
----

[source,java]
[subs="verbatim"]
----
include::{testDir}/example/defaultmethods/EqualsContract.java[tags=user_guide]
----

[source,java]
[subs="verbatim"]
----
include::{testDir}/example/defaultmethods/ComparableContract.java[tags=user_guide]
----

In your test class you can then implement both contract interfaces thereby inheriting the
corresponding tests. Of course you'll have to implement the abstract methods:

[source,java]
[subs="verbatim"]
----
include::{testDir}/example/defaultmethods/StringTests.java[tags=user_guide]
----

The above tests are merely meant as examples and therefore not complete.


=== Dynamic Tests

The standard `@Test` annotation of JUnit 5 described in <<annotations>>
is very similar to the `@Test` annotation of JUnit 4.
Both describe methods implementing test cases.
These test cases are static in the sense that they are fully specified at compile-time,
and their behavior cannot be changed by anything happening at run-time.
_Assumptions provide a basic form of dynamic behavior but are intentionally rather limited in their expressiveness._

In addition to these standard tests a completely new kind of test programming model is introduced in JUnit 5.
This new kind of test is a _dynamic test_ which is generated at run-time by a test factory method
which must be annotated with `@TestFactory`.

In contrast to `@Test` such a factory is not itself a test case but rather creates test cases.
Thus, dynamic tests are the products of a factory.
Technically speaking, a `@TestFactory` method must return a `Stream`,
`Collection`, `Iterable`, or `Iterator` of `DynamicTest` instances.
These `DynamicTest` instances will then be executed lazily,
enabling dynamic and even non-deterministic generation of test cases.

As with `@Test` methods, `@TestFactory` methods must not be `private` or `static`
and may optionally declare parameters to be resolved by `ParameterResolvers`.

A `DynamicTest` is a test case generated at runtime.
It is composed of a _display name_ and an `Executable` which is a `@FunctionalInterface`.
Note that the execution lifecycle of dynamic tests is quite different than it is for standard `@Test` cases.
Specifically, `@BeforeEach` and `@AfterEach` methods and their corresponding extension callbacks
are not executed for dynamic tests.
The execution of those callbacks would not be useful in most dynamic testing scenarios
since variables used in lambdas are bound to instance variables at execution time of the factory method
rather than execution time of the lambda itself.

==== Dynamic Test Examples

The following `DynamicTestsDemo` class demonstrates several examples of test factories and dynamic tests.

The first method returns an invalid return type.
Since invalid return types cannot be detected at compile-time
a `JUnitException` is thrown when it is detected at run-time.

The next four methods are very simple examples that demonstrate the generation of a
`Stream`, a `Collection`, an `Iterable`, and an `Iterator` of `DynamicTest` instances, respectively.
These examples do not really exhibit dynamic behavior
but merely demonstrate the supported return types in principle.

The last two methods are truly dynamic in nature.
`dynamicTestsFromCustomIterator()` implements a custom `Iterator` that generates `DynamicTest` instances;
whereas, `generateRandomNumberOfTests()` implements an `Iterator` that generates random numbers, a custom
display name generator, and a test generator and provides all three to `DynamicTest.stream()`.
Although the non-deterministic behavior of `generateRandomNumberOfTests()` is of course in conflict with
test repeatability and should thus be used with care, it serves to demonstrate the expressiveness of dynamic tests.

As of M1, dynamic tests must always be created by factory methods.
This might be complemented by a registration facility in one of the upcoming releases.

[source,java]
[subs="verbatim"]
----
include::{testDir}/example/DynamicTestsDemo.java[tags=user_guide]
----
