name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
inputs:
  distribution:
    required: true
    description: 'The JDK distribution to use'
    default: 'liberica'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: 8
        check-latest: true
    - shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
