name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
inputs:
  distribution:
    required: true
    description: 'The JDK distribution to use'
    default: 'liberica'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: 8
        check-latest: true
    - shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV # zizmor: ignore[github-env]
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: 17
        check-latest: true
    - shell: bash
      run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV # zizmor: ignore[github-env]
