#!/bin/bash

# The -Xdebug option disables a ReportEntry from DisableOnDebugJupiterDemo that would normally
# be generated by ExtensionClassA.

java \
	-Xdebug \
	-jar ../junit-platform-console/build/libs/junit-platform-console-1.0.0-SNAPSHOT-standalone.jar \
	--scan-classpath \
	--classpath ../junit-platform-runner/build/libs/junit-platform-runner-1.0.0-SNAPSHOT.jar:build/classes/test \
	--include-classname '^.+(Tests|Demo)$' \
        --exclude-tag exclude
