package junitbuild.generator

import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.module.kotlin.KotlinModule
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateJreRelatedSourceCode : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val jreYaml: RegularFileProperty

    @get:OutputDirectory
    abstract val mainTargetDir: DirectoryProperty

    // Generate java file based on YAML file
    @TaskAction
    fun generate() {
        val mapper = ObjectMapper(YAMLFactory())
        mapper.registerModule(KotlinModule.Builder().build())
        val yamlFile = jreYaml.get().asFile

        val jres = mapper.readValue(yamlFile, object : TypeReference<List<JRE>>() {})

        val mainTargetDir = mainTargetDir.get().asFile
        mainTargetDir.deleteRecursively()
        mainTargetDir.resolve("generated").mkdirs()
        val targetFile = mainTargetDir.resolve("generated/Generated.java")

        targetFile.printWriter().use { out ->
            out.println("""
                // This file is generated by GenerateJreRelatedSourceCode task
                // Do not modify this file manually
                
                package generated;
                
                public class Generated {
                    public static void main(String[] args) {
            """.trimIndent())
            jres.forEach { jre ->
                out.println("        System.out.println(\"JRE ${jre.version} was released since ${jre.since ?: "unknown"}\");")
            }
            out.println("""
                    }
                }
            """.trimIndent())
        }
    }

    data class JRE(val version: String, val since: String?)

}
